"""Guide content — career, freight operations, automation, and body composition."""

NAV_CAREER = [("/", "Work"), ("/guides.html", "Guides"), ("/resume.html", "Resume"), ("/apply.html", "Apply OS")]
NAV_FREIGHT = [("/", "Work"), ("/guides.html", "Guides"), ("/freight-tools.html", "Calculators"), ("/freightdesk.html", "FreightDesk")]
NAV_AI = [("/", "Work"), ("/guides.html", "Guides"), ("/stack.html", "Stack"), ("/store.html", "Store")]
NAV_BODY = [("/", "Work"), ("/guides.html", "Guides"), ("/apps.html", "Apps"), ("/media-kit.html", "Media Kit")]

GUIDES = [

{
 "slug": "ats-resume",
 "title": "ATS Resume Rules That Actually Matter (and Myths)",
 "desc": "What applicant tracking systems really do to a resume, the formatting rules that matter, how to mirror a job description honestly, and the myths.",
 "og_title": "ATS Resume Rules That Actually Matter",
 "og_desc": "What ATS software really does, what breaks parsing, and which rules are folklore.",
 "headline": "ATS Resume Rules That Actually Matter, and the Myths That Do Not",
 "crumb": "ATS Resumes",
 "about": ["Resume writing", "Applicant tracking systems", "Job search"],
 "eyebrow": "Guide · Career",
 "h1": "What an ATS actually does to your resume",
 "lead": "Applicant tracking systems are databases with a parser attached, not gatekeeping robots that score your personality. Most advice about beating them is folklore. A few rules are real, and they are boring.",
 "nav": NAV_CAREER,
 "body": [
  ("h2", "What an ATS really is"),
  ("p", "An applicant tracking system stores applications and makes them searchable. When you upload a resume, a parser tries to extract structured fields — name, contact details, employers, dates, titles, education, skills — into a database record. A recruiter then searches and filters that database."),
  ("p", "<strong>The failure mode you should fear is a bad parse, not a low score.</strong> If the parser reads your two-column layout in the wrong order and files your job titles as skills, you are searchable for nothing, and no human ever sees the document."),
  ("h2", "The rules that are real"),
  ("ul", ["<strong>Single column.</strong> Multi-column layouts and text boxes are the single most reliable way to scramble a parse.",
          "<strong>Standard section headings.</strong> Experience, Education, Skills, Projects. Not \"My Journey\" or \"What I Bring\".",
          "<strong>Real text, not images.</strong> A resume exported as an image, or with contact details inside a graphic, parses as an empty document.",
          "<strong>Dates in a consistent format</strong>, with month and year, in one place per role.",
          "<strong>Standard fonts and no tables for layout.</strong> Tables often parse cell-by-cell into nonsense.",
          "<strong>A .pdf or .docx generated from a text document</strong> — not a scan, not a screenshot, not a design-tool export with outlined type.",
          "<strong>Terminology that matches the posting.</strong> If the job says \"Python\" and you wrote \"Py\", a keyword filter misses you. This is not gaming the system; it is speaking its language."]),
  ("h2", "The myths"),
  ("table", (["Myth", "Reality"],
             [["\"White-text keyword stuffing beats the ATS\"", "Trivially detected, and it is grounds for rejection when a human sees the document. Do not."],
              ["\"The ATS gives you a match score out of 100\"", "Some products compute a match score, most recruiters ignore it, and none of them reject solely on it."],
              ["\"Never use a PDF\"", "Modern parsers handle text-based PDFs fine. The problem is image-based or design-tool PDFs with outlined text."],
              ["\"One page or you are rejected\"", "One page is good advice for students because it forces editing, not because a parser counts pages."],
              ["\"Fancy templates get filtered out\"", "They get parsed badly, which is worse than filtered. The template is not judged; it is misread."]])),
  ("h2", "How to mirror a job description honestly"),
  ("ol", ["Pull the 8–12 concrete nouns from the posting: languages, frameworks, tools, domains, methods.",
          "Delete any you cannot defend in an interview. That is the whole ethics of this exercise.",
          "For the rest, make sure the exact term appears where you genuinely used it — in the bullet describing the work, not in a keyword dump.",
          "Match the posting's vocabulary for the same concept: if they say \"CI/CD\" and you wrote \"build pipelines\", include both.",
          "Keep a base resume and a per-role variant. Rewriting from scratch each time is how people stop applying."]),
  ("h2", "Bullets that survive a six-second read"),
  ("p", "A parser gets your bullets into the database; a human decides in seconds. The structure that works: <strong>action, object, method, result</strong> — and the result is a number wherever one honestly exists."),
  ("formula", "Weak:  Responsible for the team's data pipeline\nBetter: Built an NLP scoring pipeline over 50+ market sources per day,\n        cutting manual research time 60%"),
  ("p", "If there is no number, use scope: how many users, how many records, how many workflows, over what period. \"Improved performance\" is unreadable; \"cut page load from 4.2s to 1.1s\" is a fact."),
  ("h2", "For students specifically"),
  ("ul", ["Projects count as experience. Put them in their own section with links, and describe them like work.",
          "Coursework is only worth listing if it is relevant and specific. \"Data Structures, Algorithms, Machine Learning\" is fine; a list of fifteen course codes is not.",
          "Include the graduation month and year. Recruiters filter on it constantly.",
          "Put GitHub and portfolio links in the text, not only in a header graphic — headers are the most commonly dropped region in parsing.",
          "If you need sponsorship, say so plainly somewhere in the process. Discovering it at offer stage wastes everyone's time, including yours."]),
  ("p", 'I do this as a service if you want it done for you: <a href="/resume.html">an ATS-safe resume rebuild</a>, optionally with tailored applications. And <a href="/apply.html">Apply OS</a> is the free tracker for keeping the applications themselves straight.'),
 ],
 "tools": [("/resume.html", "Resume rebuild", "ATS-safe rebuild, optionally with tailored applications."),
           ("/apply.html", "Apply OS", "free deadline radar and application pipeline, browser-only."),
           ("/guides/swe-internship-international-student.html", "Internship guide", "the full search process for international students.")],
 "faqs": [
  ("What does an ATS actually do to a resume?", "An applicant tracking system parses your resume into structured database fields — name, contact details, employers, titles, dates, education, skills — and makes them searchable for recruiters. The real risk is a bad parse that files your information incorrectly, not a hidden score that rejects you."),
  ("What resume format is safest for an ATS?", "A single-column layout with standard section headings, real selectable text, consistent date formats, standard fonts, and no tables or text boxes used for layout. A text-based PDF or DOCX is fine; image-based exports are not."),
  ("Do ATS systems reject resumes automatically?", "Generally no. Most systems filter and rank rather than auto-reject, and recruiters do the rejecting. The common cause of an application vanishing is that the parse failed or the resume did not contain the terms the recruiter searched for."),
  ("Should you copy keywords from the job description?", "Use the posting's exact terminology for skills you genuinely have, placed in the bullets describing where you used them. Do not list skills you cannot defend in an interview, and never hide keywords in white text — it is detected and it is disqualifying."),
  ("Is a PDF bad for ATS?", "Text-based PDFs parse fine in modern systems. The problem is PDFs exported from design tools with outlined type, or scanned images, because there is no extractable text at all."),
  ("Should a student resume be one page?", "One page is good advice for students because it forces ruthless editing, not because a parser counts pages. Projects with links belong on it and count as experience."),
 ],
 "faq_cards": [
  ("What does an ATS do?", "Parses your resume into database fields recruiters search. The danger is a scrambled parse, not a secret rejection score."),
  ("Safest format?", "Single column, standard headings, real text, consistent dates, no tables or text boxes for layout."),
  ("Do they auto-reject?", "Mostly no — they filter and rank. Applications vanish because the parse failed or the search terms were missing."),
  ("Copy keywords?", "Use the posting's exact words for skills you actually have, inside real bullets. Never white-text stuffing — it is detected and disqualifying."),
  ("Is PDF bad?", "Text-based PDFs are fine. Design-tool exports with outlined type and scans are not, because there is no text to extract."),
  ("One page?", "For students, yes — because it forces editing. Projects with links belong on it and count as experience."),
 ],
},

{
 "slug": "swe-internship-international-student",
 "title": "SWE Internships as an International Student — A Plan",
 "desc": "How international students should run a SWE internship search: the timeline, the sponsorship question, who to target, and how work authorization fits.",
 "og_title": "SWE Internships as an International Student",
 "og_desc": "The timeline, the sponsorship question, and how work authorization actually fits an internship.",
 "headline": "Landing a SWE Internship as an International Student",
 "crumb": "SWE Internships",
 "about": ["Software engineering internships", "International students", "Job search strategy"],
 "eyebrow": "Guide · Career",
 "h1": "The internship search, run as a system",
 "lead": "Two things decide this: applying early enough, and knowing which door you are legally allowed to walk through. Most international students get the second part wrong late, which is the expensive way to learn it.",
 "nav": NAV_CAREER,
 "body": [
  ("h2", "The timeline is earlier than you think"),
  ("p", "Summer internship hiring in software runs roughly a year ahead. Large firms open applications in late summer and early autumn for the <em>following</em> summer, and many close when the pipeline fills rather than on the posted date. Quantitative finance is earlier still, with some programmes opening and closing before the academic year is properly underway."),
  ("table", (["Window", "What is happening", "What you should be doing"],
             [["Jul–Aug", "Earliest postings open", "Resume finished, portfolio live, list built"],
              ["Sep–Oct", "Peak volume; most large-firm deadlines", "Apply in volume; career fairs; referrals"],
              ["Nov–Jan", "Interviews; second wave of postings", "Interview loops; keep applying"],
              ["Feb–Apr", "Smaller companies and startups", "Where late applicants actually get hired"],
              ["May–Jun", "Backfills and short-notice roles", "Still worth working — offers do appear"]])),
  ("p", "<strong>The single biggest error is treating spring as the season.</strong> By spring the large programmes are done. The second biggest is optimising the resume for months instead of submitting it — materials are rarely the bottleneck, submissions are."),
  ("h2", "The sponsorship question, answered honestly"),
  ("p", "For an <em>internship</em>, the question is usually narrower than students assume. An F-1 student typically works an internship on CPT authorised by their school, or on pre-completion OPT — neither of which requires the employer to file an immigration petition. That is very different from the H-1B sponsorship question for full-time hiring."),
  ("p", "So there are two distinct questions on an application form, and they deserve different answers:"),
  ("ul", ["<strong>\"Are you legally authorised to work in the US?\"</strong> — with valid CPT or OPT in place for the internship period, yes.",
          "<strong>\"Will you now or in the future require sponsorship?\"</strong> — for most international students the honest answer for full-time employment is yes, and answering it truthfully is not optional."]),
  ("p", "Answer both accurately. Some employers screen out anyone who will ever need sponsorship, and that is a filter you cannot argue your way past — but plenty do not, and burning a real offer over a mis-stated answer is far worse than being filtered early."),
  ("p", 'The eligibility mechanics — the one-academic-year rule for CPT, the 12-month OPT allowance, the STEM extension — are in the <a href="/guides/cpt-vs-opt.html">CPT vs OPT guide</a>. Confirm your own case with your DSO; none of this is legal advice.'),
  ("h2", "Where to spend your applications"),
  ("ol", ["<strong>Companies that have hired international students before.</strong> Ask upperclassmen and student groups; this information travels by word of mouth, not by job board.",
          "<strong>Mid-size product companies.</strong> Less rigid than the largest firms about the sponsorship checkbox, and far less applicant volume per opening.",
          "<strong>Startups with a technical founder.</strong> Fast decisions, and the work is usually more interesting; the trade-off is less structure.",
          "<strong>University-adjacent research and lab roles.</strong> Often easier to authorise, and they compound into research output.",
          "<strong>Federal contractors and defence.</strong> Usually a hard no on citizenship grounds — do not spend applications here."]),
  ("h2", "The parts that actually move the needle"),
  ("ul", ["<strong>Referrals.</strong> One referral outperforms fifty cold applications. Ask specifically: \"Would you be comfortable referring me for req #12345?\" — a yes/no question is easier to answer than a favour.",
          "<strong>Shipped projects with links.</strong> A live URL beats a bullet point. Anything a reviewer can click in ten seconds is worth more than a paragraph.",
          "<strong>Research or publications.</strong> Rare among undergraduates and disproportionately memorable — it signals you can finish something hard and write it up.",
          "<strong>Interview reps.</strong> Pattern-based practice beats random problem grinding. Track which patterns you fail, not how many problems you did.",
          "<strong>A system for tracking it all.</strong> Which req, applied when, deadline type, next action. Applications die in the gaps between them."]),
  ("h2", "The mindset that survives it"),
  ("p", "The process is high-volume and mostly silent. Rejection rates are brutal for everyone and worse when a sponsorship filter is running against you. The only counter is throughput plus a small number of high-quality signals — the portfolio, the research, the referral — that make you unusual in a stack of similar resumes."),
  ("p", 'Everything I built for my own search is public: <a href="/apply.html">Apply OS</a> for the pipeline and deadlines, <a href="/visa.html">Visa Navigator</a> for the authorisation timeline, and <a href="/resume.html">the resume rebuild</a> if you would rather hand the document off.'),
 ],
 "tools": [("/apply.html", "Apply OS", "deadline radar and application pipeline, free and browser-only."),
           ("/visa.html", "Visa Navigator", "backward-planned CPT/OPT and change-of-status timeline."),
           ("/guides/ats-resume.html", "ATS resume guide", "what actually breaks a resume parse.")],
 "faqs": [
  ("When should international students apply for summer SWE internships?", "Roughly a year ahead. Large firms open applications in late summer and early autumn for the following summer and often close early when the pipeline fills. Quantitative finance runs earlier still. Spring is when smaller companies and startups hire, not when the large programmes are available."),
  ("Do internships require employer sponsorship?", "Usually not in the way full-time roles do. F-1 students typically work internships on CPT authorised by their school or on pre-completion OPT, neither of which requires the employer to file an immigration petition. Full-time hiring is where the sponsorship question becomes an employer cost."),
  ("How should you answer the work authorization question?", "Answer both questions accurately and separately: with valid CPT or OPT you are authorised to work for the internship period, and if you will need sponsorship for full-time employment in future, say so. Misstating either can cost a real offer later, which is far worse than being filtered early."),
  ("Which employers are realistic for international students?", "Companies that have hired international students before, mid-size product companies, startups with technical founders, and university-adjacent research roles. Federal contractors and defence work is usually restricted on citizenship grounds and is not worth spending applications on."),
  ("What matters more than the resume?", "Referrals, shipped projects with live links, and any research output. One referral typically outperforms fifty cold applications, and a clickable project beats a bullet describing one. Materials are rarely the bottleneck; submission volume usually is."),
  ("Is it harder to get an internship as an international student?", "Generally yes, because some employers filter on the sponsorship question regardless of the internship's actual requirements. The counter is applying earlier, applying in volume, and carrying one or two unusual signals such as research or a shipped product."),
 ],
 "faq_cards": [
  ("When do I apply?", "About a year ahead. Large firms open late summer and autumn for the next summer and close when full. Spring is startup season, not big-firm season."),
  ("Do internships need sponsorship?", "Usually not — F-1 interns typically work on CPT or pre-completion OPT, which the school authorises. Full-time hiring is the different question."),
  ("How do I answer the authorization question?", "Accurately, and treat the two questions separately: authorised now via CPT/OPT, and yes to future sponsorship if that is true."),
  ("Who should I target?", "Employers with a track record of hiring international students, mid-size product companies, technical-founder startups, and research roles. Skip defence contractors."),
  ("What beats a better resume?", "A referral, a shipped project with a live link, and research output. Submissions, not materials, are almost always the bottleneck."),
  ("Is it harder for us?", "Yes, because of blanket sponsorship filters. Volume plus one or two unusual signals is the only reliable counter."),
 ],
},

{
 "slug": "linkedin-profile-recruiters",
 "title": "A LinkedIn Profile That Gets Recruiter Replies",
 "desc": "How recruiters actually search LinkedIn, what belongs in the headline and About, why the first two lines decide everything, and what costs replies.",
 "og_title": "A LinkedIn Profile That Gets Recruiter Replies",
 "og_desc": "How recruiters actually search, and what the first two lines have to do.",
 "headline": "A LinkedIn Profile That Gets Recruiter Replies",
 "crumb": "LinkedIn Profiles",
 "about": ["LinkedIn", "Personal branding", "Job search"],
 "eyebrow": "Guide · Career",
 "h1": "Write the profile for how recruiters actually search",
 "lead": "A recruiter runs a keyword search, scans a list of one-line results, opens a few, and reads two lines of each before deciding. Optimise for that sequence and nothing else.",
 "nav": NAV_CAREER,
 "body": [
  ("h2", "How recruiters actually find people"),
  ("p", "The workflow is search, scan, open, skim. They search on concrete terms — a language, a framework, a title, a location, sometimes a school. The results list shows your <strong>name, headline, and location</strong>, and nothing else. That headline is doing all the work of getting you opened."),
  ("p", "So a headline of \"Aspiring Software Engineer | Passionate about technology\" fails twice: it contains no term anyone searches for, and it says nothing that would make someone click."),
  ("h2", "The headline"),
  ("formula", "[what you are] · [proof or specialisation] | [concrete stack] | [what you are building]"),
  ("p", "Concrete beats aspirational. Load it with the nouns a recruiter would type — the language, the framework, the domain, the credential — while still reading like a human wrote it. You have around 220 characters; use most of them."),
  ("ul", ["Include your actual stack in the words the industry uses.",
          "Include one credential or proof point if you have one: a publication, a shipped product, a named employer.",
          "Include what you are looking for if you are looking. Recruiters filter on \"open to\" language.",
          "Avoid: passionate, aspiring, enthusiast, ninja, guru. They occupy space and signal nothing."]),
  ("h2", "The About section: only the first two lines are read"),
  ("p", "LinkedIn truncates About behind a \"see more\" link. Whatever is above that fold is the entire section for most readers, so <strong>the first sentence must be the summary of you</strong>, written in plain declarative form."),
  ("p", "The structure that works below the fold: what you do now, one or two specific pieces of proof with numbers, your stack, and what you want next, ending with contact details. Short paragraphs. No walls of text — the mobile app renders them as a grey slab nobody finishes."),
  ("h2", "Experience entries are not job descriptions"),
  ("p", "Copying your duties from the job posting is the most common waste of space on LinkedIn. Write what changed because you were there. Action, object, method, result — with the result quantified when it honestly can be."),
  ("formula", "Instead of: Responsible for maintaining internal reporting tools\nWrite:      Rebuilt the internal reporting pipeline over 50+ daily sources,\n            cutting manual research time 60%"),
  ("h2", "The mechanical points that quietly matter"),
  ("ul", ["<strong>Custom URL.</strong> linkedin.com/in/yourname, not the string of digits. It goes on the resume.",
          "<strong>Photo and banner.</strong> A clear face and a banner that is not the default. This is a two-minute fix with outsized effect on reply rates.",
          "<strong>Skills section.</strong> It feeds the search index. Populate it with the terms you want to be found for.",
          "<strong>Featured section.</strong> Pin the portfolio, the paper, the repository. It is the only place a link gets real visual weight.",
          "<strong>Open-to-work settings.</strong> The recruiter-only version is visible in their tooling without the green banner.",
          "<strong>Location.</strong> Set it to where you can actually work. Recruiters filter hard on it."]),
  ("h2", "Activity, briefly"),
  ("p", "You do not need to post daily. But a profile with zero activity looks abandoned, and a profile with a handful of substantive posts about what you built reads as evidence. Posting the thing you made, with a link and what you learned, is the highest-value-per-minute activity on the platform — and it is the same content as your portfolio, so it costs you nothing new."),
  ("p", 'If you would rather have it done for you, I rewrite profiles end to end in 48 hours: <a href="/sprint.html">the LinkedIn Profile Rewrite Sprint →</a>'),
 ],
 "tools": [("/sprint.html", "LinkedIn Profile Rewrite Sprint", "a complete rewrite delivered in 48 hours."),
           ("/resume.html", "Resume rebuild", "the ATS-safe document that pairs with the profile."),
           ("/guides/ats-resume.html", "ATS resume guide", "what breaks a resume parse and what does not.")],
 "faqs": [
  ("How do recruiters search LinkedIn?", "They search concrete keywords — a language, framework, title, location, sometimes a school — then scan a results list that shows only name, headline, and location. Your headline is what decides whether your profile gets opened at all."),
  ("What should a LinkedIn headline contain?", "What you are, one proof point or specialisation, your concrete stack in the industry's own terms, and what you are building or seeking. Use most of the roughly 220 characters, and avoid words like passionate, aspiring, ninja, or guru, which are neither searched nor informative."),
  ("How long should the About section be?", "Structurally, only the first two lines matter, because LinkedIn truncates the rest behind a see-more link. Lead with a plain declarative summary of who you are, then use short paragraphs for proof with numbers, your stack, what you want next, and contact details."),
  ("What should go in Experience entries?", "What changed because you were there, not the duties from the job posting. Use action, object, method, result, and quantify the result whenever an honest number exists."),
  ("Do you need to post on LinkedIn to get noticed?", "Not daily. A profile with no activity reads as abandoned, but a handful of substantive posts about what you actually built is enough, and that content is usually the same as your portfolio work, so it costs nothing extra to produce."),
  ("What LinkedIn settings actually matter?", "A custom profile URL, a clear photo and non-default banner, a populated Skills section because it feeds search, a Featured section pinning your portfolio and any publications, the recruiter-visible open-to-work setting, and a location set to where you can genuinely work."),
 ],
 "faq_cards": [
  ("How do recruiters search?", "Keyword search, then a results list showing only name, headline, and location. The headline decides whether you get opened."),
  ("What goes in the headline?", "What you are, a proof point, your real stack in industry terms, and what you are building. Use most of the ~220 characters."),
  ("How long should About be?", "Only the first two lines are read before the fold. Lead with a plain declarative summary, then short paragraphs with numbers."),
  ("What about Experience?", "Not job duties — what changed because you were there, quantified wherever an honest number exists."),
  ("Do I need to post?", "Not daily. Zero activity looks abandoned; a few substantive build posts read as evidence and reuse your portfolio work."),
  ("Which settings matter?", "Custom URL, real photo and banner, populated Skills, a Featured section with your links, open-to-work for recruiters, correct location."),
 ],
},

{
 "slug": "freight-back-office",
 "title": "The Freight Broker Back Office — Where the Hours Go",
 "desc": "What a small brokerage does after the load books: confirmations, check calls, POD chasing, invoicing and AR — and what automates cleanly.",
 "og_title": "The Freight Broker Back Office",
 "og_desc": "What happens after the load books, and which of it a machine can do.",
 "headline": "The Freight Broker Back Office: Where the Hours Actually Go",
 "crumb": "Freight Back Office",
 "about": ["Freight brokerage", "Accounts receivable", "Back-office automation"],
 "eyebrow": "Guide · Freight",
 "h1": "After the load books, the real work starts",
 "lead": "Booking freight is the visible job. The invisible one — confirmations, documents, invoices, and chasing money — is where a small brokerage's margin quietly goes, and it is the part that automates best.",
 "nav": NAV_FREIGHT,
 "body": [
  ("h2", "The lifecycle after \"covered\""),
  ("ol", ["<strong>Rate confirmation</strong> out to the carrier; signed copy back and filed.",
          "<strong>Carrier vetting and documents</strong> — authority, insurance certificate, W-9 — verified and stored against expiry dates.",
          "<strong>Dispatch and check calls</strong> — pickup confirmed, in transit, delivered, with timestamps that matter later for detention.",
          "<strong>POD collection</strong> — the proof of delivery, which is the single most chased document in the industry.",
          "<strong>Invoice generation</strong> — customer rate, accessorials, references, and the POD attached in whatever format that specific customer demands.",
          "<strong>Carrier settlement</strong> — pay the carrier on their terms, or through a factoring company, correctly and on time.",
          "<strong>Accounts receivable</strong> — track the invoice to payment, dun at 30, 45, 60 days, reconcile short-pays and disputes."]),
  ("p", "Every step is small. There are just a great many of them, each with a deadline, each attached to an email thread, and each capable of costing real money when it slips."),
  ("h2", "Where the money actually leaks"),
  ("table", (["Leak", "Mechanism", "Cost"],
             [["Missing POD", "Invoice cannot be sent, or is sent and rejected", "Days to weeks of delay on every affected load"],
              ["Wrong invoice format", "Customer's AP system rejects or ignores it", "Re-work plus a full payment-cycle delay"],
              ["Unbilled accessorials", "Detention and layover never make it onto the invoice", "Pure lost margin, invisible in the P&L"],
              ["Late dunning", "Nobody chased at 30 days", "Cash tied up; occasionally never collected"],
              ["Expired carrier insurance", "Not caught before dispatch", "Potentially catastrophic liability"]])),
  ("p", "None of these are strategy failures. They are all attention failures — the predictable result of a small team handling a high volume of small deadlines through an inbox."),
  ("h2", "What automates cleanly"),
  ("p", "The rule of thumb: <strong>automate what is repetitive, structured, and deadline-driven; keep humans on judgement and relationships.</strong>"),
  ("ul", ["<strong>Reading billing email</strong> and extracting load numbers, references, amounts, and attachments.",
          "<strong>Matching documents to loads</strong> — POD to load number, rate confirmation to invoice.",
          "<strong>Drafting invoices</strong> in each customer's required format, with accessorials pulled from the timestamps already recorded.",
          "<strong>Chasing missing documents</strong> on a schedule, with escalation, so nobody has to remember.",
          "<strong>AR ageing and dunning</strong> — automatic at 30, 45, 60 days, with a human review before anything gets sharp.",
          "<strong>Compliance expiry monitoring</strong> — insurance and authority dates flagged before dispatch, not after."]),
  ("p", "What should stay human: negotiating rates, deciding whether to keep a difficult customer, handling a claim, and any conversation where the relationship is the asset."),
  ("h2", "Why the inbox is the wrong system of record"),
  ("p", "Most small brokerages run on email plus a spreadsheet. It works until volume rises, and then it fails in a specific way: information exists but is not <em>queryable</em>. Nobody can answer \"which loads are missing a POD right now\" without a person reading threads. Every leak in the table above is a version of that same problem."),
  ("p", "The fix is not necessarily new software with a login. It is turning the email stream into structured records — load, document, status, deadline — and letting something watch that structure instead of a human watching an inbox."),
  ("p", 'That is what <a href="/freightdesk.html">FreightDesk AI</a> does: it reads the billing inbox, drafts the invoice, chases the missing paperwork on a schedule, and hands a human the exceptions. The workflow-by-workflow case study — 18 AR and billing workflows — is <a href="/hwyhaul.html">here</a>, and the arithmetic behind the numbers themselves is in the <a href="/guides/freight-broker-margin.html">margin and rate-per-mile guide</a>.'),
 ],
 "tools": [("/freightdesk.html", "FreightDesk AI", "AI back office for small brokerages: reads billing email, drafts invoices, chases documents."),
           ("/freight-tools.html", "Freight calculators", "rate per mile, deadhead, margin, detention, FSC, break-even — free."),
           ("/hwyhaul.html", "HwyHaul LoadLink case study", "18 AR and billing workflows, documented.")],
 "faqs": [
  ("What does a freight broker do after a load is booked?", "Issue and collect a signed rate confirmation, verify carrier authority and insurance, run check calls through pickup and delivery, collect the proof of delivery, generate an invoice in the customer's required format, settle with the carrier or their factoring company, and then track the receivable to payment with dunning at 30, 45, and 60 days."),
  ("Why do freight invoices get paid late?", "Most commonly a missing proof of delivery, an invoice submitted in a format the customer's accounts-payable system rejects, or nobody chasing at 30 days. Each of these delays a full payment cycle, and none of them are visible until cash is already tight."),
  ("What is the most chased document in freight?", "The proof of delivery. Without it the invoice usually cannot be submitted at all, which is why POD collection is the step most worth automating in a small brokerage."),
  ("Which back-office tasks can AI handle in a brokerage?", "Reading billing email and extracting load references and amounts, matching documents to loads, drafting invoices in customer-specific formats, chasing missing documents on a schedule, running accounts-receivable ageing and dunning, and flagging expiring carrier insurance or authority before dispatch."),
  ("What should stay human in a brokerage?", "Rate negotiation, decisions about which customers and carriers to keep, claims handling, and any exchange where the relationship itself is the asset. Automation should handle repetition and deadlines, not judgement."),
  ("Why is email a bad system of record for freight?", "Because information in an inbox is not queryable. Nobody can answer 'which loads are missing a POD right now' without a person reading threads, so every deadline depends on someone remembering it, which is exactly where margin leaks."),
 ],
 "faq_cards": [
  ("What happens after booking?", "Rate confirmation, carrier vetting, check calls, POD collection, invoicing, carrier settlement, then AR and dunning at 30/45/60 days."),
  ("Why do invoices get paid late?", "Missing POD, wrong invoice format for the customer's AP system, or nobody chasing at 30 days. Each costs a full payment cycle."),
  ("What gets chased most?", "The proof of delivery. Without it the invoice usually cannot even be submitted."),
  ("What can AI actually do?", "Read billing email, match documents to loads, draft invoices, chase paperwork on a schedule, run AR ageing, flag expiring insurance."),
  ("What stays human?", "Rate negotiation, customer and carrier decisions, claims, and anything where the relationship is the asset."),
  ("Why is the inbox the problem?", "Information exists but is not queryable. 'Which loads are missing a POD?' requires a human reading threads — that gap is the leak."),
 ],
},

{
 "slug": "ai-automation-small-business",
 "title": "Where AI Automation Actually Pays Off in a Small Business",
 "desc": "A practical filter for which small-business tasks AI should handle, the two-tier local plus frontier pattern, and why the quality gate is the product.",
 "og_title": "Where AI Automation Actually Pays Off",
 "og_desc": "A filter for what to automate, the two-tier model pattern, and why the quality gate is the product.",
 "headline": "Where AI Automation Actually Pays Off in a Small Business",
 "crumb": "AI Automation",
 "about": ["Business automation", "Applied AI", "Operations"],
 "eyebrow": "Guide · AI",
 "h1": "Automate the deadline work, not the thinking",
 "lead": "Most AI automation projects fail on selection, not technology. The tasks worth automating share a specific shape, and the ones that burn money share a different one.",
 "nav": NAV_AI,
 "body": [
  ("h2", "The filter"),
  ("p", "A task is a good automation candidate when it is <strong>repetitive, structured, deadline-driven, and cheap to verify</strong>. That last one carries most of the weight: if checking the output takes as long as producing it, automation has moved the work rather than removed it."),
  ("table", (["Automate", "Keep human"],
             [["Drafting a first version", "Sending anything that commits you"],
              ["Extracting fields from documents", "Deciding what the fields mean for the relationship"],
              ["Classifying and routing inbound messages", "Handling the angry one"],
              ["Chasing missing paperwork on a schedule", "Negotiating price"],
              ["Summarising a long thread", "Making the call the thread was about"],
              ["Monitoring dates and flagging expiry", "Deciding what to do when something expires"]])),
  ("h2", "The two-tier pattern"),
  ("p", "The architecture that consistently works is two-tier. A cheap local model does the volume — drafting, tagging, extraction, overnight batches — at zero marginal cost. A frontier model does the judgement: the final pass, the hard reasoning, anything customer-facing. Between them sits the piece most people skip."),
  ("h2", "The quality gate is the product"),
  ("p", "Generated output at volume is worthless without an automated check, because the failure rate is never zero and one bad artefact reaching a customer costs more than the whole batch saved. A gate is a set of hard invariants, checked in code, that quarantines anything failing them."),
  ("ul", ["Required fields present and non-empty.",
          "No placeholder text — no unfilled template variables, no leftover brackets.",
          "Names, amounts, and dates match the source record exactly, checked by string comparison rather than by vibes.",
          "Length and format within bounds.",
          "Banned-phrase list for anything that would embarrass you.",
          "Deduplication against what has already been sent, so nobody gets the same message twice."]),
  ("p", "Everything failing the gate goes to a quarantine folder rather than out the door. <strong>Volume without a gate is not throughput, it is liability at scale.</strong>"),
  ("h2", "Sequencing a real build"),
  ("ol", ["<strong>Instrument first.</strong> Count how often the task happens and how long it takes. Automating something that occurs twice a month is a hobby.",
          "<strong>Write the gate before the generator.</strong> If you cannot specify what correct output looks like in code, you are not ready to generate it.",
          "<strong>Run it in shadow mode.</strong> Generate, gate, and inspect — but do not send. Measure the pass rate.",
          "<strong>Ship the highest-volume slice only.</strong> One workflow, end to end, beats five half-built ones.",
          "<strong>Keep a human at the point of irreversibility</strong> until the pass rate has been stable for long enough that you would bet on it."]),
  ("h2", "What it actually costs"),
  ("p", "Less than people expect on tokens and more than they expect on plumbing. A local model on hardware you already own is free per call, so the recurring cost of a high-volume drafting pipeline can be genuinely near zero. The real expense is the boring part: connecting the data sources, defining the invariants, handling the exceptions, and maintaining it when a format changes upstream."),
  ("p", "Which is the honest summary of this whole field right now — <strong>the model is the cheap part.</strong>"),
  ("p", 'A worked example of all of this in production is <a href="/freightdesk.html">FreightDesk AI</a>: local model drafts overnight, an automated audit quarantines anything failing its checks, a human sees only exceptions. The generation half is covered in the <a href="/guides/local-llm-ollama.html">local LLM guide</a>, and the retrieval half in the <a href="/guides/rag-explained.html">RAG guide</a>.'),
 ],
 "tools": [("/freightdesk.html", "FreightDesk AI", "the pattern in production for freight brokerages."),
           ("/guides/local-llm-ollama.html", "Local LLM guide", "how to run the cheap tier on your own hardware."),
           ("/store.html", "Automation Studio &amp; store", "playbooks and templates for building this yourself.")],
 "faqs": [
  ("Which business tasks are worth automating with AI?", "Tasks that are repetitive, structured, deadline-driven, and cheap to verify — drafting first versions, extracting fields from documents, classifying and routing messages, chasing paperwork on a schedule, summarising threads, and monitoring expiry dates. If verifying the output costs as much as doing the work, automation has moved the work rather than removed it."),
  ("What should stay human in an automated workflow?", "Anything that commits you or depends on a relationship: sending final communications, negotiating price, handling complaints or claims, and deciding what to do when something the system flagged actually happens."),
  ("What is the two-tier model pattern?", "A cheap local model handles high-volume, low-difficulty work such as drafting, tagging, and extraction at zero marginal cost, while a frontier model handles judgement, hard reasoning, and anything customer-facing. An automated quality gate sits between them."),
  ("Why does an automation pipeline need a quality gate?", "Because generation at volume always has a non-zero failure rate, and one bad artefact reaching a customer can cost more than the entire batch saved. A gate checks hard invariants in code — required fields, no placeholder text, exact matches for names and amounts, deduplication — and quarantines anything that fails."),
  ("How should you sequence an AI automation build?", "Instrument the task first to confirm the volume justifies it, write the quality gate before the generator, run in shadow mode without sending to measure the pass rate, ship one high-volume workflow end to end, and keep a human at the irreversible step until the pass rate is proven stable."),
  ("What does AI automation actually cost?", "Less than expected on model inference, especially with a local model on hardware you already own, and more than expected on integration — connecting data sources, defining invariants, handling exceptions, and maintaining it when an upstream format changes. The model is the cheap part."),
 ],
 "faq_cards": [
  ("What is worth automating?", "Repetitive, structured, deadline-driven work that is cheap to verify. If checking costs as much as doing, you moved the work rather than removed it."),
  ("What stays human?", "Anything that commits you: final sends, price negotiation, complaints, and deciding what to do when a flag fires."),
  ("What is the two-tier pattern?", "Cheap local model for volume drafting and extraction, frontier model for judgement and anything customer-facing, gate in between."),
  ("Why a quality gate?", "Failure rate is never zero, and one bad artefact costs more than the batch saved. Volume without a gate is liability at scale."),
  ("How do I sequence a build?", "Instrument, write the gate first, run in shadow mode, ship one workflow end to end, keep a human at the irreversible step."),
  ("What does it cost?", "Little on inference, a lot on plumbing — integration, invariants, exceptions, maintenance. The model is the cheap part."),
 ],
},

{
 "slug": "cut-calorie-math",
 "title": "The Arithmetic Behind a 60-Pound Cut",
 "desc": "How a calorie deficit actually works: maintenance estimation, deficit size, protein, why the scale lies week to week, and how to track it without obsessing.",
 "og_title": "The Arithmetic Behind a 60-Pound Cut",
 "og_desc": "Maintenance, deficit size, protein, and why the scale lies for ten days at a time.",
 "headline": "The Arithmetic Behind a 60-Pound Cut",
 "crumb": "Calorie Arithmetic",
 "about": ["Body composition", "Calorie deficit", "Habit tracking"],
 "eyebrow": "Guide · Body",
 "h1": "260 to 200, and the arithmetic that got there",
 "lead": "There is no clever part. There is an estimate, a deficit, a protein floor, and a tracking method that survives the weeks when the scale refuses to move.",
 "nav": NAV_BODY,
 "body": [
  ("warn", "Educational only — not medical or nutritional advice. Talk to a doctor or registered dietitian before changing how you eat, especially with any medical condition, medication, or history of disordered eating."),
  ("h2", "Start with maintenance, not a diet"),
  ("p", "Maintenance is the intake at which weight is stable. Every formula for it is an estimate, and estimates are wrong for individuals — so use one to start, then correct it with real data."),
  ("formula", "Rough start:  maintenance ≈ bodyweight (lb) × 14–16\nThen:         eat that for 10–14 days, track weight daily,\n              and adjust based on the trend, not the formula"),
  ("p", "<strong>Your own two-week trend beats any calculator.</strong> The formula gets you within a few hundred calories; the data closes the gap."),
  ("h2", "Deficit size"),
  ("p", "A pound of body fat is commonly approximated at around 3,500 calories, which makes a 500-per-day deficit roughly a pound a week. It is an approximation — adaptive changes and water shifts blur it — but it is a workable planning number."),
  ("table", (["Daily deficit", "Rough weekly loss", "Trade-off"],
             [["250", "≈ 0.5 lb", "Easy to sustain, slow enough to feel like nothing is happening"],
              ["500", "≈ 1 lb", "The usual recommendation — meaningful and liveable"],
              ["750–1000", "≈ 1.5–2 lb", "Faster, but hunger, training quality, and adherence all suffer"],
              ["Aggressive crash", "varies", "Higher muscle loss, poor adherence, near-universal rebound"]])),
  ("p", "The deficit you actually follow beats the optimal one you abandon in three weeks. That is the entire lesson and most people learn it the slow way, twice."),
  ("h2", "Protein is the one macro worth defending"),
  ("p", "In a deficit the body will take some of the weight from lean mass. Adequate protein plus resistance training is what shifts the balance toward fat. Common practical guidance is roughly <strong>0.7–1.0 g per pound of target bodyweight</strong>, which is generous but simple to hit and hard to overshoot in a deficit."),
  ("p", "Protein also has the highest satiety per calorie of the three macros, so the floor makes the deficit easier to live with. Fill the remaining calories with carbohydrate and fat in whatever split you personally adhere to best — that ratio matters far less than the total and the protein floor."),
  ("h2", "Why the scale lies"),
  ("p", "Daily weight moves with water, glycogen, sodium, digestion, and sleep — swings of several pounds that have nothing to do with fat. It is entirely normal for the scale to stall for ten days and then drop three pounds overnight while the underlying loss was perfectly steady."),
  ("ul", ["Weigh daily, at the same time, under the same conditions.",
          "Judge only the <strong>weekly average against the previous weekly average</strong>. Never compare two individual days.",
          "Expect a stall after high sodium, hard training, or poor sleep.",
          "If the four-week trend is flat, the deficit is not real — recheck portions and untracked intake before touching the plan."]),
  ("h2", "The tracking method that survives"),
  ("ol", ["Track weight daily, look at it weekly.",
          "Track intake honestly for two weeks to calibrate, then loosely once the portions are known.",
          "Keep a protein floor as a hard rule; treat everything else as a target.",
          "Lift, and keep a record of the lifts. Strength holding steady in a deficit is the best available evidence that the weight leaving is mostly fat.",
          "Take a photo monthly. It is the only measure that captures what the scale cannot."]),
  ("h2", "The part nobody writes down"),
  ("p", "Sixty pounds took a long time, and most of that time was unremarkable. The weeks that felt like failure were mostly water. The thing that made it work was not discipline in any heroic sense — it was reducing the number of decisions: same breakfast, known portions, one number to check per week."),
  ("p", 'I built <a href="/apps/cut/">Cut</a> for that shape of tracking: weight in, trend out, no account, no server, nothing leaves your device.'),
 ],
 "tools": [("/apps/cut/", "Cut", "weight and body-recomposition tracker — offline, local-only, no signup."),
           ("/apps/fire/", "Fire", "daily ritual checklist for the habits underneath it."),
           ("/media-kit.html", "Media kit", "the full transformation story and creator work.")],
 "faqs": [
  ("How do you calculate maintenance calories?", "Start with a rough estimate of bodyweight in pounds multiplied by 14 to 16, eat at that level for 10 to 14 days while weighing daily, then adjust based on the actual weight trend. Your own two-week data is more accurate than any formula, which only needs to get you within a few hundred calories."),
  ("How big should a calorie deficit be?", "A deficit of about 500 calories a day corresponds to roughly a pound a week using the common 3,500-calories-per-pound approximation, and is the usual recommendation. Larger deficits lose weight faster but cost adherence, training quality, and more lean mass. The deficit you actually sustain beats the theoretically optimal one you abandon."),
  ("How much protein do you need when cutting?", "Common practical guidance is roughly 0.7 to 1.0 grams per pound of target bodyweight. Adequate protein combined with resistance training shifts the composition of the loss toward fat rather than lean mass, and protein is also the most satiating macronutrient per calorie."),
  ("Why does the scale stall for weeks?", "Daily weight is dominated by water, glycogen, sodium, digestion, and sleep, which can mask steady fat loss for a week or more. Compare weekly averages to previous weekly averages rather than individual days, and only conclude the deficit is not working if the four-week trend is flat."),
  ("Do carbohydrate and fat ratios matter for fat loss?", "Far less than total calories and the protein floor. Once calories and protein are set, split the remainder between carbohydrate and fat in whichever way you personally adhere to best."),
  ("Is losing 60 pounds fast possible?", "Speed is the wrong target. At a sustainable pace of roughly a pound a week, a 60-pound loss is a project measured in many months, and the approaches that go faster tend to cost more lean mass and have far higher rebound rates. This is general information, not medical advice."),
 ],
 "faq_cards": [
  ("How do I find maintenance?", "Bodyweight × 14–16 as a start, then eat there for two weeks and correct using your own weight trend. Data beats the formula."),
  ("How big a deficit?", "About 500/day for roughly a pound a week. Bigger is faster and costs adherence, training quality, and lean mass."),
  ("How much protein?", "Roughly 0.7–1.0 g per pound of target bodyweight. It protects lean mass in a deficit and keeps you full."),
  ("Why is the scale stuck?", "Water, glycogen, sodium, digestion, sleep. Compare weekly averages, not days, and only worry if four weeks are flat."),
  ("Do macros matter?", "Much less than total calories and the protein floor. Split the rest however you actually adhere to."),
  ("Can I do it fast?", "Speed is the wrong target — faster costs lean mass and rebounds. This is general information, not medical advice."),
 ],
},

]
