"""Guide content — portfolios, interview patterns, undergraduate research, and funding."""

NAV_CAREER = [("/", "Work"), ("/guides.html", "Guides"), ("/resume.html", "Resume"), ("/apply.html", "Apply OS")]
NAV_EDU = [("/", "Work"), ("/guides.html", "Guides"), ("/about.html", "About"), ("/apps.html", "Apps")]

GUIDES = [

{
 "slug": "portfolio-that-gets-interviews",
 "title": "A Student Portfolio That Gets Interviews",
 "desc": "What a student software portfolio needs: a live URL, a README that pitches, three strong projects instead of ten weak ones, and case studies reviewers finish.",
 "og_title": "A Student Portfolio That Gets Interviews",
 "og_desc": "Shipped and reachable beats impressive-sounding. What a reviewer checks in 60 seconds.",
 "headline": "A Student Software Portfolio That Gets Interviews",
 "crumb": "Student Portfolios",
 "about": ["Software portfolios", "Technical hiring", "Student projects"],
 "eyebrow": "Guide · Career",
 "h1": "Shipped and reachable beats impressive-sounding",
 "lead": "A reviewer gives your portfolio under a minute. In that minute they are answering one question: did this person actually finish something real? Everything below is about making that answer obvious fast.",
 "nav": NAV_CAREER,
 "body": [
  ("h2", "The only test that matters"),
  ("p", "A portfolio is not a gallery and it is not a resume in HTML. It is <strong>evidence that you can take something from idea to working thing that other people can use</strong>. Most student portfolios fail that test not because the projects are bad but because the evidence is unreachable — a repo with no README, a demo that 404s, a screenshot of something nobody can run."),
  ("p", "<strong>A live URL beats a repository.</strong> A reviewer who can click and immediately see the thing working has already given you more credit than a reviewer who has to clone, install dependencies, and guess at environment variables — which they will not do. Deploy it. Free static hosting and free tiers cover almost every student project, and a deployed toy outranks an undeployed system."),
  ("h2", "What a reviewer checks in 60 seconds"),
  ("table", (["Second", "What they do", "What kills you"],
             [["0–5", "Load the site or repo", "It does not load, or it is a wall of unstyled text"],
              ["5–15", "Read the top line — what is this?", "No one-sentence description of what the project does"],
              ["15–30", "Click the live demo", "Broken link, dead deploy, or no demo at all"],
              ["30–45", "Skim the README or case study", "Setup instructions where the explanation should be"],
              ["45–60", "Open the code, scan one file", "Tutorial code, one giant file, no commits after day one"]])),
  ("p", "Notice that none of those seconds are spent on your design taste or your framework choice. They are spent establishing that the thing is real and that you can explain it."),
  ("h2", "Three strong projects, not ten weak ones"),
  ("p", "Ten shallow projects read as ten abandoned weekends. Three projects with depth read as someone who follows through. Depth means the boring parts are there: error handling, a test or two, a deploy, a README, commits spread over more than one day, and some evidence you dealt with a problem you did not anticipate at the start."),
  ("ul", ["<strong>Cut anything from a tutorial</strong> unless you extended it substantially, and say what you extended.",
          "<strong>Cut anything you cannot explain in an interview</strong> — every project on the page is fair game for a deep question.",
          "<strong>Cut anything with no users and no result</strong>, unless the technical difficulty itself is the point.",
          "<strong>Keep the one that is unusual.</strong> One weird, specific project is worth more attention than three competent CRUD apps.",
          "<strong>Keep the one with a number attached.</strong> Accuracy, latency, throughput, time saved, users — any honest metric anchors the whole page."]),
  ("h2", "The README is the pitch"),
  ("p", "For most projects the README is the only documentation anyone will read, and for a hiring reviewer it is the case study. Setup instructions matter, but they belong <em>below</em> the explanation, not above it."),
  ("formula", "# Project name\nOne sentence: what it does and who it is for.\n\n[Live demo](url)  ·  30-second screenshot or GIF\n\n## Why\nThe problem, in two or three sentences.\n\n## How it works\nThe architecture in a short paragraph, plus the stack.\n\n## What was hard\nThe real constraint, and what you decided.\n\n## Results\nNumbers if you have them. Scope if you do not.\n\n## Run it locally\nThe commands, last."),
  ("p", "A screenshot or a short GIF near the top does an enormous amount of work, because it lets someone understand the project without running anything. It is the cheapest credibility you can buy."),
  ("h2", "How to write a project case study"),
  ("p", "A case study is not a feature list. It is a decision narrative — you had a problem, you had constraints, you chose something, and something happened. The structure that reads well:"),
  ("ol", ["<strong>Context.</strong> What the problem was and why it was worth solving. One paragraph.",
          "<strong>Constraints.</strong> Time, cost, data, hardware, skill. Constraints are what make the decisions interesting.",
          "<strong>What you built.</strong> The architecture in plain language before any diagram, plus the stack and why.",
          "<strong>The hard part.</strong> The one thing that did not work at first. This is the paragraph that separates a builder from a follower of tutorials.",
          "<strong>The result.</strong> A number, or honest scope. \"78% directional accuracy over 50+ sources per day\" is a result; \"successfully implemented\" is not.",
          "<strong>What you would change.</strong> Short, specific, unromantic. It signals you evaluated your own work."]),
  ("callout", "Write the case study while the project is fresh. Reconstructing why you made a decision six months later produces vague prose, and vague prose is what makes a portfolio forgettable."),
  ("h2", "The portfolio site itself"),
  ("ul", ["<strong>One page is enough.</strong> Who you are, three projects with links, contact. Depth lives on the project pages.",
          "<strong>Every project links to something clickable</strong> — live demo first, repository second, paper or write-up third.",
          "<strong>Fast and readable on a phone.</strong> A meaningful share of reviews happen on a phone between meetings.",
          "<strong>Real text, not images of text.</strong> Recruiters and search engines both read the page.",
          "<strong>Your email visible without a form.</strong> Contact forms lose messages and add friction to the exact action you want.",
          "<strong>Dates on things.</strong> A portfolio with no dates reads as stale by default."]),
  ("h2", "The version of this that is easy to skip"),
  ("p", "Building the portfolio is the fun part; keeping it reachable is the part that decays. Deploys expire, free tiers sleep, links rot. <strong>Check every link on your portfolio the week before you start applying</strong>, and again mid-season. A dead demo link on an otherwise strong page is worse than no link, because it converts a positive signal into evidence you do not maintain your work."),
  ("p", 'The application side of this — which roles, which deadlines, what you sent and when — is what <a href="/apply.html">Apply OS</a> handles, and the document that points at the portfolio is covered in the <a href="/guides/ats-resume.html">ATS resume guide</a>.'),
 ],
 "tools": [("/apply.html", "Apply OS", "free deadline radar and application pipeline, browser-only."),
           ("/resume.html", "Resume rebuild", "the ATS-safe document your portfolio links from."),
           ("/guides/ats-resume.html", "ATS resume guide", "how projects should be written on the resume itself.")],
 "faqs": [
  ("What makes a student software portfolio effective?", "Evidence that you finished something real and can explain it. That means a live clickable URL rather than a repository alone, a README that opens with what the project does and why, and a small number of projects with genuine depth. Reviewers spend under a minute, so reachability beats ambition."),
  ("How many projects should be in a portfolio?", "Three strong ones. Ten shallow projects read as ten abandoned weekends, while three with error handling, tests, a deploy, a real README, and commits spread over time read as someone who follows through. Cut anything you cannot defend in a deep interview question."),
  ("Is a live demo better than a GitHub repository?", "Yes. A reviewer who can click and see the thing working credits you immediately, while one who must clone, install dependencies, and guess at configuration will simply move on. A deployed small project outranks an undeployed larger one."),
  ("What should a project README contain?", "A one-sentence description, a live demo link and a screenshot or GIF near the top, then why the project exists, how it works, what was hard, and the result with a number if one honestly exists. Local setup instructions belong at the bottom, not the top."),
  ("How do you write a project case study?", "As a decision narrative rather than a feature list: context, constraints, what you built, the one thing that did not work at first, the result, and what you would change. The hard-part paragraph is what distinguishes a builder from someone following a tutorial."),
  ("What do reviewers check first in a portfolio?", "Whether the page loads, whether one sentence tells them what the project is, whether the demo link works, whether the README explains rather than only instructs, and whether the code looks like yours rather than a tutorial. Broken links and missing descriptions cause most of the failures."),
 ],
 "faq_cards": [
  ("What actually works?", "Evidence you finished something real and can explain it: a live URL, a README that pitches, and depth over volume. Reviewers give it under a minute."),
  ("How many projects?", "Three with real depth. Ten shallow ones read as ten abandoned weekends. Cut anything you cannot defend in a deep question."),
  ("Demo or repo?", "Live demo. Nobody clones and configures your project. A deployed small thing outranks an undeployed bigger one."),
  ("What goes in the README?", "One-sentence description, demo link and GIF up top, then why, how, what was hard, and the result. Setup commands go last."),
  ("How do I write a case study?", "Context, constraints, what you built, the part that did not work, the result, what you would change. The hard part is the paragraph that counts."),
  ("What gets checked first?", "Does it load, is there a one-line description, does the demo link work, does the README explain, is the code yours. Broken links kill most pages."),
 ],
},

{
 "slug": "coding-interview-patterns",
 "title": "Coding Interview Patterns, Not Problem Counts",
 "desc": "The pattern-based approach to technical interviews: the ten recurring problem patterns, why tracking the pattern you fail beats counting, and spaced repetition.",
 "og_title": "Coding Interview Patterns, Not Problem Counts",
 "og_desc": "Ten recurring patterns, and why tracking failures by pattern beats grinding problem counts.",
 "headline": "Coding Interview Patterns, Not Problem Counts",
 "crumb": "Interview Patterns",
 "about": ["Technical interviews", "Algorithms", "Deliberate practice"],
 "eyebrow": "Guide · Career",
 "h1": "Track which pattern you fail, not how many problems you did",
 "lead": "Interview problems are drawn from a small set of recurring shapes. Solving 400 problems randomly teaches you 400 facts; identifying which of ten patterns you keep failing teaches you the thing that transfers.",
 "nav": NAV_CAREER,
 "body": [
  ("h2", "Why problem counts are the wrong metric"),
  ("p", "\"I did 300 problems\" tells you nothing about readiness, because it does not distinguish between 300 problems in the patterns you already know and 300 spread across the ones you do not. Volume without a diagnosis produces a common and frustrating outcome: a large solved count and a consistent failure on any problem phrased slightly unfamiliarly."),
  ("p", "The reframe is simple. <strong>An interview problem is a pattern wearing a costume.</strong> Your job in the first two minutes is to identify the pattern; the implementation afterwards is mechanical if you have drilled it. So practice should be organised around recognising patterns and around finding the ones where your recognition fails."),
  ("h2", "The recurring patterns"),
  ("table", (["Pattern", "Recognition cue", "Typical complexity"],
             [["Two pointers", "Sorted array, pair or triplet sum, in-place partition, palindrome", "O(n) after any sort"],
              ["Sliding window", "Contiguous subarray or substring, longest or shortest satisfying a condition", "O(n)"],
              ["Binary search on the answer", "Monotone predicate, \"minimum k such that…\", \"can we do it in x?\"", "O(n log range)"],
              ["BFS / DFS on graphs", "Grid, tree, connectivity, shortest path with unit edges, reachability", "O(V + E)"],
              ["Topological sort", "Dependencies, prerequisites, ordering with constraints, cycle detection", "O(V + E)"],
              ["Heap / top-k", "K largest, k closest, merge k sorted, running median", "O(n log k)"],
              ["Intervals", "Meetings, ranges, merges, overlaps, scheduling", "O(n log n) with sort"],
              ["Dynamic programming", "Count the ways, optimal value, overlapping subproblems, choices per index", "Depends on state space"],
              ["Backtracking", "Generate all, permutations, combinations, constraint satisfaction, N-queens", "Exponential with pruning"],
              ["Union-find", "Connected components, grouping, cycle detection in undirected graphs, Kruskal", "Near O(α(n)) per op"]])),
  ("p", "That table is most of the surface area of a standard software interview loop. The remaining problems are usually combinations — a BFS whose frontier is a heap, a DP over intervals, a binary search whose predicate runs a greedy check."),
  ("h2", "The two-minute recognition drill"),
  ("p", "Recognition is a separate skill from implementation and it is the one that fails under pressure. Drill it separately: read a problem, spend two minutes deciding the pattern and the complexity target, write it down, then check. Do not implement. You can run twenty of these in the time one full solution takes, and it trains exactly the step interviews test first."),
  ("formula", "For each problem, before coding, answer four questions:\n\n  1. What is the input shape?        sorted / graph / intervals / string\n  2. What is being asked?            exists / count / optimum / enumerate\n  3. What complexity is plausible?   n log n suggests sort or heap or binary search\n  4. Which pattern fits?             name it, out loud, before typing"),
  ("p", "Question 3 does more work than people expect. If the constraints allow n up to 10^5, an O(n^2) solution is not the intended one, and that single observation frequently identifies the pattern on its own."),
  ("h2", "Keeping a failure log by pattern"),
  ("p", "The whole method rests on one artefact: a log where every problem you attempt is tagged with its pattern and an outcome. Not a count — a <strong>per-pattern record</strong>."),
  ("ol", ["Tag every attempt with one of the ten patterns.",
          "Record the outcome honestly: solved unaided, solved with a hint, or failed.",
          "Record <em>where</em> it broke — recognition, approach, implementation, or edge cases. These are different problems with different fixes.",
          "Review weekly and look for the pattern with the worst ratio. That is your next week.",
          "When a pattern reaches a run of clean unaided solves, stop drilling it and let spaced repetition maintain it."]),
  ("p", "The failure location matters as much as the failure. If you recognise sliding window instantly but keep mishandling the shrink condition, you do not need more sliding-window problems — you need to write the template once, correctly, and rehearse it. If you never recognise it in the first place, the fix is the opposite."),
  ("h2", "Spaced repetition, because you will forget"),
  ("p", "Algorithm knowledge decays like anything else. A problem solved cleanly in March is often a blank in June. Spaced repetition solves this cheaply: re-attempt solved problems on an expanding schedule rather than solving new ones forever."),
  ("table", (["Outcome", "Next review", "Rationale"],
             [["Failed", "1 day", "Nothing has been learned yet"],
              ["Solved with a hint", "3 days", "Recognition is fragile"],
              ["Solved unaided, slowly", "1 week", "Correct but not fluent"],
              ["Solved unaided, fluently", "3 weeks", "Maintenance only"],
              ["Fluent twice in a row", "2 months", "Retired to background rotation"]])),
  ("p", "The practical shape is a Leitner system: boxes with review intervals, a problem moves forward on a clean solve and drops back to box one on a failure. Twenty minutes of review before new problems each session is a better use of the hour than another fresh problem."),
  ("h2", "A weekly structure that works"),
  ("ul", ["<strong>Start every session with review</strong>, not new material. Fifteen to twenty minutes on due problems.",
          "<strong>One target pattern per week</strong>, chosen from the worst ratio in the log, not from a curriculum order.",
          "<strong>Recognition drills in bulk</strong> — a batch of twenty problems where you only name the pattern.",
          "<strong>Two or three full timed solves</strong>, out loud, since interviews are verbal and silence reads as being stuck.",
          "<strong>Write the template once per pattern</strong> — the canonical implementation, from memory, until it is automatic.",
          "<strong>Stop tracking total solved.</strong> It is the metric that feels like progress and measures nothing."]),
  ("callout", "The honest test of readiness is not a solved count. It is whether you can be handed an unfamiliar problem in any of the ten patterns and name the pattern within two minutes, then implement its template without looking it up."),
  ("p", 'The rest of the search — which roles, which deadlines, and the sponsorship questions if you need them — is covered in the <a href="/guides/swe-internship-international-student.html">internship guide</a>, and the pipeline itself lives in <a href="/apply.html">Apply OS</a>.'),
 ],
 "tools": [("/apply.html", "Apply OS", "application pipeline and deadline radar, free and browser-only."),
           ("/guides/swe-internship-international-student.html", "Internship guide", "the timeline and sponsorship mechanics around the interviews."),
           ("/resume.html", "Resume rebuild", "the document that gets you to the interview in the first place.")],
 "faqs": [
  ("What are the main coding interview patterns?", "Two pointers, sliding window, binary search on the answer, BFS and DFS, topological sort, heap and top-k, intervals, dynamic programming, backtracking, and union-find. Most remaining interview problems are combinations of these, such as a BFS whose frontier is a heap or a binary search whose predicate runs a greedy check."),
  ("Why is counting solved problems a bad metric?", "Because it does not distinguish between problems in patterns you already know and problems in the ones you do not. A large solved count with no per-pattern diagnosis commonly produces someone who still fails any problem phrased unfamiliarly."),
  ("How do you identify which pattern a problem uses?", "Answer four questions before writing code: the input shape, what is being asked, the plausible complexity given the constraints, and the pattern name. Complexity does surprising work — if the constraints allow large inputs, an O(n^2) approach is not the intended one, which frequently identifies the pattern by itself."),
  ("What should a practice log record?", "The pattern tag, the outcome, and where the attempt broke — recognition, approach, implementation, or edge cases. Those four failure locations need different fixes: missing recognition needs exposure to more problem statements, while a broken implementation needs the template rehearsed."),
  ("How does spaced repetition apply to interview prep?", "Re-attempt solved problems on an expanding schedule instead of only solving new ones: one day after a failure, three days after a hinted solve, a week after a slow unaided solve, three weeks after a fluent one. A Leitner box system with fifteen to twenty minutes of review before new problems each session handles it."),
  ("How do you know when you are ready?", "When you can be handed an unfamiliar problem in any of the ten patterns, name the pattern within about two minutes, and implement its canonical template without looking it up. That is a different test from any solved-problem total."),
 ],
 "faq_cards": [
  ("What are the patterns?", "Two pointers, sliding window, binary search on answer, BFS/DFS, topological sort, heap/top-k, intervals, DP, backtracking, union-find."),
  ("Why not count problems?", "A count cannot tell known patterns from unknown ones. Volume without diagnosis leaves you failing anything phrased unfamiliarly."),
  ("How do I spot the pattern?", "Input shape, what is asked, plausible complexity, then name it. Constraints alone often rule out the wrong approach."),
  ("What do I log?", "Pattern, outcome, and where it broke — recognition, approach, implementation, or edge cases. Each needs a different fix."),
  ("How does spaced repetition help?", "Re-solve on expanding intervals: 1 day after a fail, 3 days after a hint, 1 week, 3 weeks. Leitner boxes, review before new problems."),
  ("When am I ready?", "When an unfamiliar problem in any pattern gets named in two minutes and the template gets written without a lookup."),
 ],
},

{
 "slug": "undergraduate-research",
 "title": "How to Get Into Undergraduate Research",
 "desc": "How to find a lab, email a professor, survive the first task, and why publishing as an undergraduate is disproportionately valuable.",
 "og_title": "How to Get Into Undergraduate Research",
 "og_desc": "Finding a lab, the email that gets a reply, and why publishing as an undergrad compounds.",
 "headline": "How to Get Into Undergraduate Research",
 "crumb": "Undergraduate Research",
 "about": ["Undergraduate research", "Academic labs", "Computer science education"],
 "eyebrow": "Guide · Research",
 "h1": "How undergraduates actually get into a lab",
 "lead": "Most students never ask, and the ones who do usually ask badly. The process is unglamorous: read what a professor published, email them about it specifically, and be useful on a small task before you expect anything larger.",
 "nav": NAV_EDU,
 "body": [
  ("h2", "Why this is worth doing"),
  ("p", "Research is one of the few things an undergraduate can do that is genuinely rare among applicants. Coursework is common, projects are common, internships are competitive but common. <strong>A publication with your name on it is not common</strong>, and it signals something specific: that you can work on an open problem for months without a solution key and write it up to a standard that survived peer review."),
  ("p", "It also compounds. One paper makes the second easier, gives you a reference who has seen you work rather than seen your grades, and opens graduate admissions if that path ever becomes interesting."),
  ("h2", "Finding a lab"),
  ("p", "You are not looking for \"a research opportunity\". You are looking for a specific person whose specific work you can describe in a sentence. That distinction is what separates an email that gets a reply from one that does not."),
  ("ol", ["<strong>Read the department's faculty directory</strong> and shortlist five to eight people whose research area you can actually follow at your level.",
          "<strong>Find their recent papers</strong> — the lab page, their Google Scholar profile, or the conference proceedings for their field. Read the abstract and introduction of two of them properly.",
          "<strong>Check for a lab website</strong>. Many list open positions, expected commitments, and the exact application process, which makes the cold email unnecessary.",
          "<strong>Ask your instructors.</strong> A professor who has taught you and likes your work is the shortest path in the entire process, and their referral to a colleague carries real weight.",
          "<strong>Look beyond your own department.</strong> CS skills are wanted in education, biology, linguistics, public health, and economics labs, and the competition there is far thinner.",
          "<strong>Check for funded programmes</strong> — undergraduate research awards, REU-style summer programmes, and departmental assistantships all have formal applications and deadlines."]),
  ("callout", "The unfair advantage for a CS undergraduate is that most labs outside CS have data they cannot process well. Being the person who can write the pipeline, clean the dataset, or build the study tool is a legitimate entry ticket even before you understand the domain."),
  ("h2", "The email"),
  ("p", "A professor receives a lot of generic requests and ignores nearly all of them. The three things that get a reply are: evidence you read their work, a concrete offer of what you can do, and a small ask. Keep it under 200 words."),
  ("formula", "Subject: Undergraduate interested in [specific topic] — [your name]\n\nDear Professor [Name],\n\nI am a [year] [major] student at [university]. I read your paper\n\"[exact title]\" and found [one specific thing — a method, a result,\na limitation you noticed] genuinely interesting because [one honest\nsentence, in your own words].\n\nI have [concrete relevant skill: Python, data cleaning, building study\ntools, statistics] and used it to [one line about a real project].\nI would like to contribute to your lab, including on the unglamorous\nparts — data collection, cleaning, transcription, tooling.\n\nWould you have 15 minutes in the next two weeks to talk about whether\nthere is anything I could help with? I have attached my CV.\n\nThank you for your time,\n[Name] · [email] · [portfolio or GitHub link]"),
  ("ul", ["<strong>Name the paper exactly.</strong> A generic \"I am interested in your research\" is the single clearest signal that you read nothing.",
          "<strong>Offer the boring work explicitly.</strong> Labs need data cleaning and transcription more than they need ideas from strangers.",
          "<strong>Ask for 15 minutes, not a position.</strong> A small ask is easy to say yes to.",
          "<strong>Attach a one-page CV</strong> and link something clickable.",
          "<strong>Follow up once</strong> after ten days, then move on. Non-reply is usually inbox volume, not judgement.",
          "<strong>Email five to eight people</strong>, not one. The reply rate is genuinely low and that is normal."]),
  ("h2", "What the first task actually looks like"),
  ("p", "It is almost never the interesting part, and this is the point at which most undergraduates quietly disappear. Expect literature screening, data cleaning, transcription, annotating responses against a codebook, running participant sessions, or building a small internal tool nobody outside the lab will ever see."),
  ("p", "<strong>Do it well and finish it on time.</strong> The entire progression from data-cleaner to co-author runs on that one behaviour, because a lab's scarcest resource is a person who reliably completes things without supervision. The students who ask for a research question in month one and vanish by month three are the norm; being the exception is not difficult, only consistent."),
  ("h2", "The vocabulary: IRB and mixed methods"),
  ("h3", "IRB"),
  ("p", "An Institutional Review Board is the university committee that reviews research involving human participants before it starts. If your study involves people — surveys, interviews, classroom studies, usability sessions — you need approval, and running the study first is not recoverable: <strong>data collected without approval generally cannot be used or published</strong>."),
  ("p", "In practice it means a written protocol describing who the participants are, what you will ask them, what data you collect, how it is stored, how it is anonymised, and what the consent form says. Approval takes weeks, so it sits at the front of the timeline. As an undergraduate you will typically complete a short human-subjects training course and be added to an existing protocol rather than writing your own."),
  ("h3", "Mixed methods"),
  ("p", "Mixed-methods research combines <strong>quantitative</strong> data — scores, timings, counts, survey scales you can run statistics on — with <strong>qualitative</strong> data — interviews, open responses, observation notes that you analyse by coding for themes."),
  ("p", "The reason to combine them is that each covers the other's blind spot. Quantitative data tells you <em>that</em> something changed and how much; qualitative data tells you <em>why</em>, and often surfaces the explanation you would never have thought to measure. A typical design runs a measurable intervention, collects the numbers, then interviews a subset of participants and codes the transcripts for recurring themes that explain the numbers."),
  ("h2", "Publishing, and why it is disproportionately valuable"),
  ("p", "Undergraduate authorship is rare enough that it is memorable in almost any application pile. Beyond the signal, the process teaches things coursework does not: how to scope a claim so the data actually supports it, how to write for reviewers who will attack the weakest sentence, and how to respond to criticism without either collapsing or arguing."),
  ("p", "Realistic routes in, roughly in order of accessibility: a poster at a conference or a departmental symposium, a workshop paper, a short paper or experience report, then a full paper as a middle author. Posters are not a consolation prize — they are the normal entry point, and they still involve peer review, a deadline, and defending the work in person."),
  ("h2", "A concrete example"),
  ("p", "My own path is not exceptional and that is the point. I joined <strong>Dr. Ethel Tshukudu's CS Education Research Lab at SJSU in August 2024</strong> as an undergraduate researcher, starting on the ordinary work — study logistics, data handling, tooling. That became co-authorship on <strong>two papers at the SIGCSE Technical Symposium 2026</strong>: one on bilingual coding for inclusive CS learning (<a href=\"https://doi.org/10.1145/3770761.3777339\">DOI 10.1145/3770761.3777339</a>), and a poster on adaptive curriculum maps using graph-augmented retrieval-oriented LLMs for education."),
  ("p", "The sequence was: be useful on small things, be reliable, stay long enough for a project to reach a submission deadline. There was no shortcut in it, and there did not need to be."),
  ("p", 'More on what I work on is on the <a href="/about.html">about page</a>. If the research is in CS education specifically, the <a href="/guides/bilingual-coding-cs-education.html">bilingual coding guide</a> covers one of these studies in detail.'),
 ],
 "tools": [("/about.html", "About", "the research, the projects, and what I am currently working on."),
           ("/guides/bilingual-coding-cs-education.html", "Bilingual coding guide", "a worked example of a mixed-methods CS education study."),
           ("/resume.html", "Resume rebuild", "how to present research on a one-page CV.")],
 "faqs": [
  ("How do you find an undergraduate research lab?", "Shortlist five to eight faculty from the department directory whose work you can follow, read the abstract and introduction of two of their recent papers, check their lab site for a stated application process, and ask instructors who already know your work. Look outside your own department too — CS skills are in demand in education, biology, linguistics, and public health labs where competition is much thinner."),
  ("How should you email a professor about research?", "Under 200 words, naming one of their papers exactly and one specific thing in it you found interesting, stating a concrete skill and a real project where you used it, explicitly offering to do the unglamorous work, and asking for fifteen minutes rather than a position. Attach a one-page CV, follow up once after about ten days, and email several people because the reply rate is genuinely low."),
  ("What does a first research task look like?", "Almost always something unglamorous: literature screening, data cleaning, transcription, coding responses against a codebook, running participant sessions, or building a small internal tool. Completing it well and on time is the entire mechanism by which undergraduates progress toward authorship, because reliability is a lab's scarcest resource."),
  ("What is an IRB approval and when do you need it?", "An Institutional Review Board is the university committee that reviews research involving human participants before data collection begins. You need it for surveys, interviews, classroom studies, and usability sessions, and data collected without approval generally cannot be used or published. Approval takes weeks, so it sits at the front of the project timeline."),
  ("What does mixed-methods research mean in practice?", "It combines quantitative data such as scores, timings, and survey scales with qualitative data such as interviews and open responses coded for themes. The numbers show that something changed and by how much; the qualitative side explains why, and often surfaces explanations nobody thought to measure."),
  ("Is publishing as an undergraduate realistic?", "Yes, most commonly as a poster, a workshop paper, a short paper, or a middle-author position on a full paper. It is rare enough among undergraduates to be memorable in any application pile, and the process teaches scoping a claim to the data, writing for hostile reviewers, and handling criticism — none of which coursework covers."),
 ],
 "faq_cards": [
  ("How do I find a lab?", "Shortlist 5–8 faculty, read two of their papers properly, check lab sites for a process, and ask instructors who know your work. Look outside CS too."),
  ("What do I put in the email?", "Under 200 words: the exact paper title, one specific thing in it, a concrete skill, an offer to do the boring work, and an ask for 15 minutes."),
  ("What is the first task?", "Data cleaning, transcription, screening, coding responses, or a small tool. Finishing it well and on time is the whole progression mechanism."),
  ("What is IRB?", "The committee approving human-participant research before it starts. No approval means the data usually cannot be published. Allow weeks."),
  ("What is mixed methods?", "Quantitative data for what changed and how much, qualitative coding of interviews for why. Each covers the other's blind spot."),
  ("Can undergrads publish?", "Yes — posters, workshop papers, short papers, middle authorship. Rare enough to be memorable, and it teaches what coursework does not."),
 ],
},

{
 "slug": "bilingual-coding-cs-education",
 "title": "Bilingual Coding and Inclusive CS Learning",
 "desc": "What bilingual coding is, why second-language load hurts novice programmers, and what a 60-participant SIGCSE 2026 study found about confidence.",
 "og_title": "Bilingual Coding and Inclusive CS Learning",
 "og_desc": "Learning to program in a second language, and what a SIGCSE 2026 study found.",
 "headline": "Bilingual Coding for Inclusive CS Learning",
 "crumb": "Bilingual Coding",
 "about": ["Computer science education", "Bilingual learners", "Inclusive pedagogy"],
 "type": "Article",
 "citation": ["https://doi.org/10.1145/3770761.3777339"],
 "eyebrow": "Guide · Research",
 "h1": "Learning to program in your second language",
 "lead": "Programming is already hard. Doing it while translating the instructions, the error messages, and your own reasoning out of a second language is a different task entirely — and it is the task a large share of CS students are actually performing.",
 "nav": NAV_EDU,
 "body": [
  ("h2", "The problem, stated plainly"),
  ("p", "Introductory programming asks a novice to hold several new things at once: the syntax of a language, a mental model of how a machine executes it, and a problem-solving method. Cognitive load in that first course is high for everyone."),
  ("p", "<strong>For a bilingual learner, an additional layer sits on top of all of it.</strong> The lecture is in a second language. The textbook is in a second language. Keywords, error messages, documentation, and the informal vocabulary instructors use to explain concepts are all in a second language — while the reasoning itself, the internal narration of \"if this is empty then I need to…\", often still happens in the first."),
  ("p", "The result is that a learner can be translating and programming simultaneously, and the cost of the translation is invisible from the outside. It looks like slowness, or hesitation to speak in class, or reluctance to ask questions — and it is frequently misread by everyone involved, including the learner, as lack of aptitude for programming."),
  ("h2", "Why the language layer matters more than it seems"),
  ("ul", ["<strong>Error messages are the primary feedback channel</strong> in early programming, and they are terse, idiomatic, and entirely in English.",
          "<strong>Keywords carry semantic hints</strong> — <em>while</em>, <em>return</em>, <em>continue</em> — that help a native speaker guess behaviour and do nothing for a learner who parses them as arbitrary tokens.",
          "<strong>Problem statements are natural-language comprehension tasks</strong> before they are programming tasks. A misread word produces a correct solution to the wrong problem.",
          "<strong>Asking for help has a language cost.</strong> Articulating a half-formed technical confusion is hard in a first language and considerably harder in a second, so questions go unasked.",
          "<strong>Confidence is the thing that erodes first,</strong> and in introductory CS confidence predicts persistence — whether a student stays in the major at all."]),
  ("h2", "What the study examined"),
  ("p", "That last point is what our study went after. The paper — <strong>\"Exploring Bilingual Coding for Inclusive CS Learning\"</strong>, presented at the <strong>SIGCSE Technical Symposium 2026</strong> (<a href=\"https://doi.org/10.1145/3770761.3777339\">DOI 10.1145/3770761.3777339</a>) — was conducted in Dr. Ethel Tshukudu's CS Education Research Lab at San José State University."),
  ("table", (["Element", "Detail"],
             [["Venue", "SIGCSE Technical Symposium 2026"],
              ["Design", "Mixed methods — quantitative measures plus qualitative analysis"],
              ["Participants", "60"],
              ["Ethics", "IRB-approved protocol"],
              ["Focus", "Bilingual learners in introductory programming contexts"],
              ["Reported outcome", "Significant pre-to-post gains in confidence, largest among novices"]])),
  ("p", "The mixed-methods design was not decoration. Confidence is a self-reported construct, so the quantitative side establishes <em>that</em> it moved and by how much, while the qualitative side — learners describing their own experience in their own words — is what indicates <em>why</em>, and surfaces the parts of the experience that no pre-written scale asks about."),
  ("h2", "The finding"),
  ("p", "The study reported <strong>statistically significant pre-to-post gains in learner confidence</strong>, alongside gains in computing identity, enjoyment and motivation — with inexperienced participants gaining significantly more in confidence than experienced ones. That is the headline result, and it is worth being precise about what it does and does not claim. The bilingual-versus-English-only comparison itself came out small-to-moderate in effect size and did <em>not</em> reach statistical significance."),
  ("callout", "The measured outcome is confidence, not a claim that bilingual support makes anyone a better programmer in the abstract. In introductory CS that distinction matters less than it sounds, because confidence is one of the stronger predictors of whether a student continues in computing at all — the students lost to CS are frequently lost before their capability was ever the binding constraint."),
  ("p", "The mechanism the qualitative side points at is unsurprising once stated: reducing the translation overhead frees attention for the actual computational thinking, and being permitted to reason in your stronger language removes a barrier that had nothing to do with programming ability in the first place."),
  ("h2", "What this implies for teaching"),
  ("p", "The practical implications are cheap to act on, which is the useful property of this line of work — none of it requires a new curriculum or a budget."),
  ("ol", ["<strong>Let learners reason in their first language.</strong> Pair work, comments, notes, and planning do not have to happen in English for the code to be correct.",
          "<strong>Provide a glossary of terms, not just of keywords.</strong> The informal vocabulary — \"loop through\", \"pass in\", \"call\", \"return\" — is the part that quietly excludes.",
          "<strong>Explain error messages explicitly</strong> as a teachable text genre rather than assuming they are self-evident.",
          "<strong>Separate language comprehension from problem difficulty</strong> in problem statements: short sentences, no idiom, no culturally specific framing.",
          "<strong>Give a low-stakes route to ask questions</strong> — written, asynchronous, or anonymous — because the spoken channel carries the highest language cost.",
          "<strong>Do not read hesitation as inability.</strong> It is the single most consequential misreading in an introductory classroom."]),
  ("h2", "Why this is a research area at all"),
  ("p", "Global CS enrolment is substantially bilingual, and the field's introductory materials are overwhelmingly English-language. Any factor that pushes capable students out of computing before their capability is the constraint is a retention problem worth measuring, and language is one of the few such factors that is both large and inexpensive to address."),
  ("p", 'The full paper is at <a href="https://doi.org/10.1145/3770761.3777339">doi.org/10.1145/3770761.3777339</a>. How undergraduates get into work like this in the first place is covered in the <a href="/guides/undergraduate-research.html">undergraduate research guide</a>.'),
 ],
 "tools": [("/guides/undergraduate-research.html", "Undergraduate research guide", "how to find a lab, email a professor, and reach authorship."),
           ("/about.html", "About", "the lab, the papers, and current projects."),
           ("/apps.html", "Apps", "the tools I build outside the research work.")],
 "faqs": [
  ("What is bilingual coding in CS education?", "It refers to learning and practising programming while working across two languages — typically reasoning in a first language while the instruction, keywords, error messages, and documentation are all in English. It is studied because that translation layer adds cognitive load on top of an already demanding introductory course."),
  ("Why is learning to program harder in a second language?", "Introductory programming already asks novices to hold syntax, an execution model, and a problem-solving method at once. A second-language learner adds continuous translation of lectures, problem statements, and terse English error messages, and pays a language cost every time they try to articulate a half-formed question. The overhead is invisible from outside and is easily misread as lack of aptitude."),
  ("What did the SIGCSE 2026 bilingual coding study examine?", "The paper \"Exploring Bilingual Coding for Inclusive CS Learning\", presented at the SIGCSE Technical Symposium 2026 (DOI 10.1145/3770761.3777339), used a mixed-methods, IRB-approved design with 60 participants to examine bilingual learners in introductory programming contexts and how bilingual support affected their experience."),
  ("What did the study find?", "It reported statistically significant pre-to-post gains in confidence, computing identity, enjoyment and motivation, with inexperienced participants gaining significantly more in confidence than experienced ones. The measured construct is confidence rather than raw programming ability, which matters because confidence is a strong predictor of whether students persist in computing at all."),
  ("Why use a mixed-methods design for this?", "Confidence is self-reported, so quantitative measures establish that it changed and by how much, while qualitative analysis of learners describing their own experience indicates why and surfaces factors no pre-written scale would have asked about. Each side covers the other's blind spot."),
  ("What can instructors do about it?", "Allow learners to reason and plan in their first language, provide a glossary of informal vocabulary rather than only keywords, teach error messages explicitly as a text genre, write problem statements in short unidiomatic sentences, offer a written or anonymous route to ask questions, and avoid reading hesitation as inability. None of it requires a new curriculum or a budget."),
 ],
 "faq_cards": [
  ("What is bilingual coding?", "Programming while working across two languages — reasoning in a first language while instruction, keywords, and errors are all in English."),
  ("Why is it harder?", "Continuous translation sits on top of already-high cognitive load, and asking questions costs language effort. It looks like slowness, not overhead."),
  ("What did the study do?", "SIGCSE TS 2026 paper, DOI 10.1145/3770761.3777339: mixed methods, IRB-approved, 60 participants, bilingual learners in intro programming."),
  ("What was the finding?", "Significant pre-to-post gains in learner confidence, largest among novices. Confidence, not raw ability — and it predicts persistence in CS."),
  ("Why mixed methods?", "Numbers show that confidence moved and by how much; interviews show why, including factors no pre-written scale would ask about."),
  ("What should instructors change?", "Allow first-language reasoning, glossary the informal vocabulary, teach error messages, simplify problem prose, offer written question routes."),
 ],
},

{
 "slug": "scholarships-international-students",
 "title": "Scholarships as an International Student",
 "desc": "How international students find and win scholarships, where eligibility usually breaks, and how to run an application pipeline that survives deadlines.",
 "og_title": "Scholarships as an International Student",
 "og_desc": "Where eligibility breaks, how the funding types differ, and how to run a real pipeline.",
 "headline": "Finding and Winning Funding as an International Student",
 "crumb": "Scholarships",
 "about": ["Scholarships", "International students", "Student funding"],
 "type": "Article",
 "eyebrow": "Guide · Career",
 "h1": "Eligibility first, essays second",
 "lead": "Most of the effort international students put into funding is wasted before it starts, on programmes they were never eligible for. Filter hard on eligibility, then run the rest as a pipeline with deadlines.",
 "nav": NAV_CAREER,
 "body": [
  ("warn", "Eligibility rules vary by programme and by immigration status, and they change. Nothing here is legal or immigration advice. Verify every requirement directly with the programme and with your school's international student office or academic advisor before you rely on it, and before anything you receive could affect your status."),
  ("h2", "Where eligibility actually breaks"),
  ("p", "Read the eligibility section before the prize amount. The overwhelming majority of scholarship databases are built for domestic students, and the clauses that disqualify international applicants are usually one line buried below the description."),
  ("table", (["Clause", "What it usually means", "Workaround"],
             [["\"Must be a US citizen or permanent resident\"", "Hard stop, no exceptions, typically federal or federally derived funding", "None — skip it"],
              ["\"Must be eligible to work in the US\"", "Depends entirely on your status and the nature of the award", "Check with your international student office"],
              ["\"Must be a resident of [state]\"", "Residency for tuition purposes, which international students rarely hold", "Usually a stop; occasionally defined loosely"],
              ["\"Open to students at [university]\"", "Institutional funds — often the friendliest category", "Apply; these are the highest-yield ones"],
              ["\"Requires FAFSA\"", "Federal aid, which international students generally cannot file for", "Check whether an institutional alternative form exists"],
              ["\"Must be enrolled full time\"", "Common and usually already true for you", "Verify it stays true across the funded period"],
              ["\"Open to all students regardless of citizenship\"", "Explicitly inclusive — rarer and worth prioritising", "Prioritise these"]])),
  ("p", "<strong>Institutional funding is where international students win most often.</strong> Departmental awards, college-level scholarships, endowed funds tied to a major, and research or teaching assistantships are administered by your own university, are frequently silent on citizenship, and have a fraction of the applicant volume of national competitions."),
  ("h2", "The funding types are not interchangeable"),
  ("p", "People use these words loosely, and the differences change both who is eligible and how you should apply."),
  ("ul", ["<strong>Scholarship</strong> — money toward education, usually merit or need based, paid to you or applied to tuition. Most citizenship clauses live here.",
          "<strong>Grant</strong> — money for a specific purpose or project rather than for you generally. Often need-based when governmental, but project grants are judged on the project, which is a much better fit if your work is strong.",
          "<strong>Fellowship</strong> — funding attached to a programme, cohort, or research position. Frequently includes a stipend and sometimes constitutes employment, which is exactly where immigration status becomes a real constraint rather than a checkbox.",
          "<strong>Assistantship</strong> — paid work as a research or teaching assistant. This is employment; whether you can hold it depends on your status and the work authorisation rules that apply to you.",
          "<strong>Startup credits and non-cash awards</strong> — cloud compute, API credits, software licences, hardware. Rarely citizenship-restricted because they are not payments, frequently generous, and almost nobody applies because they do not feel like \"funding\".",
          "<strong>Competitions and hackathon prizes</strong> — prize money is treated differently from employment income in many contexts, but not in all of them. Verify before you accept."]),
  ("callout", "The category most consistently underused by international students is non-cash credit programmes. Free compute, credits, and tooling do not carry the citizenship clauses that block cash awards, and for anyone building projects they remove a real constraint immediately."),
  ("h2", "Building the pipeline"),
  ("p", "Funding applications fail on logistics far more than on merit. Deadlines are scattered across the year, each application wants slightly different materials, and recommendation letters take weeks. Treat it as a pipeline with a tracker, exactly like a job search."),
  ("ol", ["<strong>Build the list first, apply second.</strong> Spend one session finding thirty candidates before you write a single essay. Sources: your university's financial aid and departmental pages, your major's professional societies, company and foundation programmes, and community or heritage-based funds.",
          "<strong>Filter on eligibility immediately</strong> and record the reason for every rejection so you never re-read the same programme in three months.",
          "<strong>Record the deadline type.</strong> Hard-deadline and rolling programmes need completely different behaviour: rolling ones reward applying early, hard ones reward planning backwards.",
          "<strong>Work backwards from each deadline</strong> — letters requested four weeks out, transcripts two weeks out, essay drafted two weeks out, submission three days early. Portals fail on the final day, predictably.",
          "<strong>Batch by material type.</strong> Write all the 500-word essays in one sitting, request all letters in one sitting. Context switching is what makes this feel enormous.",
          "<strong>Track status and outcome</strong> so next year starts from a working list rather than from zero."]),
  ("p", "<strong>Volume matters more than polish here</strong>, within limits. Award rates are low and largely outside your control, so twelve solid applications beat three immaculate ones. The exception is any programme with a named contact or an interview stage, where effort per application genuinely converts."),
  ("h2", "Recommendation letters"),
  ("ul", ["Ask four weeks ahead, minimum. Two weeks is an imposition and it shows in the letter.",
          "Ask people who have seen you <em>work</em>, not people with impressive titles who taught you once.",
          "Send a packet with the request: the programme description, the deadline, your CV, and three specific things you would like mentioned. This is a favour to them, not presumption.",
          "Ask one person to write for several programmes at once, and give them the full list up front.",
          "Send a reminder a week out and a thank-you afterwards with the outcome. You will need them again."]),
  ("h2", "Reusing one essay without it reading as generic"),
  ("p", "You cannot write twelve original essays and you should not try. The workable method is a <strong>core narrative plus a fitted opening and closing</strong> — the middle is genuinely reusable because it is your actual story, and the parts that make it feel tailored are short and cheap to rewrite."),
  ("formula", "REUSABLE CORE (~70% — write once, edit rarely)\n  · The specific problem or moment that started this\n  · What you built, studied, or did about it — with a concrete detail\n  · What it cost and what you learned that you did not expect\n  · Where it is going next\n\nFITTED OPENING (~15% — rewrite per application)\n  · Names the programme's stated priority in its own words\n  · Connects it to the first line of your core in one sentence\n\nFITTED CLOSING (~15% — rewrite per application)\n  · What this specific funding changes about what happens next\n  · A concrete plan, not gratitude"),
  ("p", "Two rules make the difference between reuse and laziness. First, the closing must be specific about what the money changes — \"this scholarship would let me reduce work hours and finish the study I started in the lab\" is an argument; \"this scholarship would help me achieve my dreams\" is filler. Second, <strong>the concrete detail in the core has to be genuinely concrete</strong>. A number, a name, a moment. Generic essays are not generic because they were reused; they are generic because they contain nothing that could only have been written by one person."),
  ("ul", ["Mirror the programme's own stated values in their own words, once, in the opening. More than once reads as pandering.",
          "Answer the question that was actually asked. A large share of applications are eliminated for answering a different prompt.",
          "Respect the word limit exactly. It is the cheapest possible way to lose.",
          "Cut every sentence that would be true of any applicant.",
          "Have someone who does not know your work read it and tell you what you do. If they cannot, the essay is not doing its job."]),
  ("h2", "One more time on eligibility"),
  ("p", "Some awards carry conditions that interact with immigration status — how a stipend is classified, whether an assistantship counts as employment, what a taxable prize means for you. These are not questions to resolve by reading a forum. Your school's international student office answers them for free and answers them for your specific case."),
  ("p", 'The mechanics of work authorisation itself are in the <a href="/guides/cpt-vs-opt.html">CPT vs OPT guide</a> and the <a href="/visa.html">Visa Navigator</a>, and the pipeline discipline that makes any of this work is the same as <a href="/apply.html">Apply OS</a>.'),
 ],
 "tools": [("/apply.html", "Apply OS", "deadline radar and pipeline tracking, free and browser-only."),
           ("/visa.html", "Visa Navigator", "backward-planned work authorisation timeline."),
           ("/guides/cpt-vs-opt.html", "CPT vs OPT guide", "the work authorisation mechanics behind funded positions.")],
 "faqs": [
  ("Can international students get scholarships in the US?", "Yes, but the eligible pool is narrower. Federal and many state-funded awards require citizenship or permanent residency, while institutional funding from your own university, departmental awards, private foundations, and programmes explicitly open regardless of citizenship are the realistic targets. Eligibility rules vary by programme and by immigration status and must be verified with the programme and your school's advisors."),
  ("Where does eligibility usually break for international students?", "Most often on citizenship or permanent residency clauses, state residency requirements, and applications requiring FAFSA, which international students generally cannot file. Read the eligibility section before the award amount, and record why each programme was rejected so you do not re-read it later."),
  ("What is the difference between a scholarship, grant, and fellowship?", "A scholarship is money toward education, usually merit or need based. A grant funds a specific purpose or project and is judged on the project rather than on you. A fellowship attaches funding to a programme or research position and often includes a stipend, which can constitute employment — the point at which immigration status becomes a genuine constraint rather than a checkbox."),
  ("What funding do international students overlook?", "Non-cash awards: cloud compute, API credits, software licences, and hardware programmes. They rarely carry citizenship clauses because they are not payments, they are often generous, and very few students apply because they do not feel like funding. For anyone building projects they remove a real constraint immediately."),
  ("How do you run a scholarship application pipeline?", "Build a list of thirty candidates before writing anything, filter on eligibility immediately, record whether each deadline is hard or rolling, work backwards from each date with letters requested four weeks out and submission three days early, and batch by material type. Volume beats polish within limits, because award rates are low and mostly outside your control."),
  ("How do you reuse one essay across many applications?", "Keep a reusable core of roughly seventy percent — the specific problem that started your work, what you did about it with a concrete detail, what it cost, and where it goes next — then rewrite only the opening and closing per programme. The closing must state specifically what the funding changes, and the core must contain a detail that could only have been written by you."),
 ],
 "faq_cards": [
  ("Can international students get scholarships?", "Yes, but narrower. Institutional and departmental funding, private foundations, and citizenship-neutral programmes. Verify eligibility per programme."),
  ("Where does eligibility break?", "Citizenship or permanent residency clauses, state residency, and FAFSA requirements. Read eligibility before the award amount."),
  ("Scholarship vs grant vs fellowship?", "Scholarship funds your education, a grant funds a project and is judged on it, a fellowship attaches to a position and may count as employment."),
  ("What gets overlooked?", "Non-cash awards — compute, API credits, software, hardware. Rarely citizenship-restricted, often generous, and almost nobody applies."),
  ("How do I run the pipeline?", "List thirty first, filter on eligibility, log hard vs rolling deadlines, plan backwards, batch by material, submit three days early."),
  ("How do I reuse an essay?", "Reusable core of ~70%, rewritten opening and closing per programme. Say what the money specifically changes, and keep one detail only you could write."),
 ],
},

]
