"""Guide content — shipping software and selling it. Data only; rendering lives in engine.py."""

NAV_DEV = [("/", "Work"), ("/guides.html", "Guides"), ("/stack.html", "Stack"), ("/apps.html", "Apps")]
NAV_BRAND = [("/", "Work"), ("/guides.html", "Guides"), ("/kxngsef.html", "KXNG SEF"), ("/store.html", "Store")]

GUIDES = [

{
 "slug": "offline-pwa",
 "title": "Build an Installable Offline PWA With No Backend",
 "desc": "How to build an installable offline PWA with no backend: manifest fields, service worker caching, cache versioning, and how iOS install differs.",
 "og_title": "Build an Installable Offline PWA With No Backend",
 "og_desc": "Manifest, service worker caching, cache versioning, storage choice, and how install differs on iOS and Android.",
 "headline": "Building an Installable Offline PWA With No Backend",
 "crumb": "Offline PWA",
 "about": ["Progressive web apps", "Service workers", "Offline-first design"],
 "eyebrow": "Guide · Web",
 "h1": "An installable app, no backend, no app store",
 "lead": "A progressive web app is three files on top of a normal website: a manifest, a service worker, and a storage decision. Get those right and the thing installs to a home screen, launches without a browser chrome, and works on a plane.",
 "level": "Intermediate",
 "nav": NAV_DEV,
 "body": [
  ("h2", "What actually makes a site installable"),
  ("p", "Browsers apply a short checklist before they will offer installation: the site is served over HTTPS, it links a valid web app manifest with the required fields, and it registers a service worker with a fetch handler. Miss any one and the install prompt silently never appears — there is no error, which is why this is the first thing to verify."),
  ("p", "Everything else — offline behaviour, caching strategy, storage — is your design problem, not a requirement. A PWA that installs but breaks offline is worse than a bookmark, so the caching work is where the actual engineering is."),
  ("h2", "The manifest fields that matter"),
  ("p", "A manifest is a small JSON file linked from the head. Most of the spec is optional; a handful of fields decide whether the install looks like an app or looks like a shortcut."),
  ("formula", "&lt;link rel=\"manifest\" href=\"/apps/tradelog/\"&gt;\n\n{\n  \"name\": \"TradeLog\",\n  \"short_name\": \"TradeLog\",\n  \"start_url\": \"/apps/tradelog/\",\n  \"scope\": \"/apps/tradelog/\",\n  \"display\": \"standalone\",\n  \"background_color\": \"#0B0B0D\",\n  \"theme_color\": \"#0B0B0D\",\n  \"icons\": [\n    {\"src\": \"icon-192.png\", \"sizes\": \"192x192\", \"type\": \"image/png\"},\n    {\"src\": \"icon-512.png\", \"sizes\": \"512x512\", \"type\": \"image/png\"},\n    {\"src\": \"icon-512-maskable.png\", \"sizes\": \"512x512\",\n     \"type\": \"image/png\", \"purpose\": \"maskable\"}\n  ]\n}"),
  ("ul", ["<strong>start_url</strong> — where the app opens from the home screen. Point it at the app, not at the site root, or every launch lands on your homepage.",
          "<strong>scope</strong> — the URL prefix the app considers its own. Links outside scope open in the browser instead of in the app window.",
          "<strong>display</strong> — <code>standalone</code> removes browser chrome. <code>fullscreen</code> also removes the status bar; <code>minimal-ui</code> keeps a thin bar.",
          "<strong>short_name</strong> — what appears under the icon. Over about 12 characters it gets truncated on a phone.",
          "<strong>icons</strong> — 192px and 512px PNGs at minimum, plus a <code>maskable</code> variant with roughly 20% safe padding so Android does not crop your logo into a circle.",
          "<strong>background_color</strong> — the splash colour while the app boots. Set it to your real background or the launch flashes white."]),
  ("h2", "Service worker caching strategies"),
  ("p", "A service worker is a script that sits between the app and the network and can answer requests from a cache. There are two strategies worth learning and one rule for choosing between them: <strong>cache-first for things that rarely change, network-first for things that do.</strong>"),
  ("table", (["Strategy", "How it works", "Use it for"],
             [["Cache-first", "Serve from cache; only hit the network on a miss", "App shell: HTML, CSS, JS, icons, fonts"],
              ["Network-first", "Try the network; fall back to cache on failure", "API responses, prices, anything time-sensitive"],
              ["Stale-while-revalidate", "Serve cache immediately, refresh cache in background", "Content that can be one version old without harm"],
              ["Network-only", "Never cache", "Analytics, POSTs, anything with side effects"]])),
  ("p", "For an app with no backend, this collapses nicely: everything is app shell, so almost everything is cache-first, and there is no data endpoint to worry about because the data lives in the browser."),
  ("formula", "const CACHE = 'tradelog-v7';\nconst SHELL = ['/apps/tradelog/', '/apps/tradelog/index.html',\n               '/apps/tradelog/app.js', '/apps/tradelog/app.css'];\n\nself.addEventListener('install', e =&gt; {\n  e.waitUntil(caches.open(CACHE).then(c =&gt; c.addAll(SHELL)));\n  self.skipWaiting();\n});\n\nself.addEventListener('activate', e =&gt; {\n  e.waitUntil(\n    caches.keys().then(keys =&gt; Promise.all(\n      keys.filter(k =&gt; k !== CACHE).map(k =&gt; caches.delete(k))\n    )).then(() =&gt; self.clients.claim())\n  );\n});\n\nself.addEventListener('fetch', e =&gt; {\n  e.respondWith(caches.match(e.request).then(r =&gt; r || fetch(e.request)));\n});"),
  ("h2", "Cache versioning, and the classic bug"),
  ("p", "The single most common PWA bug: <strong>you ship a fix, users reload, and they still see the old app.</strong> This is not a mystery, it is the service worker lifecycle working as designed. A new worker installs but stays in a <em>waiting</em> state until every tab controlled by the old one is closed — and reloading a tab does not close it."),
  ("ol", ["<strong>Bump the cache name on every deploy.</strong> <code>tradelog-v6</code> becomes <code>tradelog-v7</code>. If the name does not change, <code>addAll</code> writes into the same bucket and old entries survive.",
          "<strong>Delete old caches in <code>activate</code>.</strong> Otherwise every version you ever shipped stays on the user's disk forever.",
          "<strong>Call <code>skipWaiting()</code> and <code>clients.claim()</code></strong> so the new worker takes over immediately instead of waiting for all tabs to close.",
          "<strong>Never cache the service worker file itself with a long max-age.</strong> If <code>sw.js</code> is cached by the HTTP layer, the browser cannot see that it changed, and the app is frozen until the cache header expires."]),
  ("warn", "The failure mode is silent and it looks like your deploy did not work. Before debugging your build, open DevTools → Application → Service Workers and check whether a worker is stuck in <em>waiting</em>. That is the answer roughly nine times out of ten."),
  ("h2", "localStorage or IndexedDB?"),
  ("p", "Both keep data on the user's device. They are not interchangeable."),
  ("table", (["", "localStorage", "IndexedDB"],
             [["API", "Synchronous, three methods, trivial", "Asynchronous, transactional, verbose"],
              ["Data type", "Strings only — you JSON round-trip everything", "Structured objects, blobs, files"],
              ["Practical size", "About 5 MB per origin", "Large — typically a share of free disk"],
              ["Querying", "None. You load everything and filter in JS", "Indexes and cursors"],
              ["Blocking", "Blocks the main thread on every read and write", "Off the main thread"]])),
  ("p", "The rule I use: <strong>localStorage until it hurts.</strong> A few thousand records of JSON is fine — a trade journal, a weight log, a habit checklist. Move to IndexedDB when you are storing binary data, when you need to query rather than load-everything-and-filter, or when the payload passes a megabyte or two and the synchronous writes start showing up as jank."),
  ("p", "One caveat for either: browser storage is not backup. It survives reloads and reboots, but it does not survive a cleared browsing history, and on iOS it can be evicted after extended non-use. Ship an export button and say so plainly."),
  ("h2", "Installing on iOS versus Android"),
  ("p", "This is the part that costs support emails, because the two platforms behave completely differently and only one of them tells the user anything."),
  ("ul", ["<strong>Android Chrome</strong> — the browser detects installability and surfaces its own prompt. You can also capture the <code>beforeinstallprompt</code> event and trigger it from your own button, which converts far better than waiting for the browser banner.",
          "<strong>iOS Safari</strong> — there is no prompt and no <code>beforeinstallprompt</code> event. The user must tap <strong>Share → Add to Home Screen</strong> manually. Nothing on the page can trigger it.",
          "<strong>iOS third-party browsers</strong> — Chrome and Firefox on iOS have historically been unable to add a PWA to the home screen at all. If a user says the option is missing, ask which browser they are in before anything else.",
          "<strong>Detecting installed state</strong> — <code>window.matchMedia('(display-mode: standalone)')</code> works broadly; iOS also exposes <code>navigator.standalone</code>."]),
  ("p", "Practical consequence: detect iOS Safari and show a small one-line instruction with the share icon, and hide it once the app is running in standalone mode. Without that hint, most iPhone users will never install."),
  ("h2", "What you give up"),
  ("p", "No App Store listing and no App Store search traffic. No push notifications on iOS unless the app has been added to the home screen. No background execution to speak of. Nothing that requires a native API the browser has not exposed."),
  ("p", 'What you get in exchange: zero platform fees, no review queue, no annual developer fee, and a deploy that reaches every user the moment you push. For a personal tool, that trade is usually correct. I ship three of these — <a href="/apps/tradelog/">TradeLog</a>, <a href="/apps/cut/">Cut</a>, and <a href="/apps/fire/">Fire</a> — all offline, all local storage, no accounts anywhere.'),
 ],
 "tools": [("/apps.html", "Apps hub", "the three installable PWAs, all offline and account-free."),
           ("/apps/tradelog/", "TradeLog", "R-multiple trading journal — a localStorage-backed PWA in production."),
           ("/apps/fire/", "Fire", "daily ritual checklist, the smallest of the three and the clearest example of the pattern."),
           ("/privacy.html", "Privacy policy", "how the local-only storage claim is written up for users.")],
 "faqs": [
  ("What makes a website installable as a PWA?", "Three things: it is served over HTTPS, it links a valid web app manifest with name, icons, start_url and display, and it registers a service worker with a fetch handler. If any one is missing the browser simply never offers installation, with no error message shown."),
  ("What is the difference between cache-first and network-first?", "Cache-first serves from the cache and only touches the network on a miss, which suits the app shell — HTML, CSS, JS and icons that change only on deploy. Network-first tries the network and falls back to the cache, which suits data that goes stale, like prices or API responses."),
  ("Why do users still see the old version after I deploy a PWA?", "Because the new service worker installs but stays in a waiting state until every tab controlled by the old one is closed, and reloading a tab does not close it. Fix it by bumping the cache name on every deploy, deleting old caches during the activate event, and calling skipWaiting() plus clients.claim()."),
  ("Should I use localStorage or IndexedDB?", "Use localStorage for small amounts of JSON — a few thousand records is comfortable within its roughly 5 MB limit. Move to IndexedDB when you need to store binary data, query with indexes instead of loading everything, or when synchronous writes start causing visible jank."),
  ("How do you install a PWA on an iPhone?", "Open the site in Safari, tap the Share button, then choose Add to Home Screen. iOS provides no automatic install prompt and no beforeinstallprompt event, so the page cannot trigger it — and third-party browsers on iOS have historically not offered the option at all."),
  ("Can a PWA work with no backend at all?", "Yes. If all state lives in the user's browser through localStorage or IndexedDB and the service worker caches the app shell, there is nothing left for a server to do beyond serving static files. That also means no accounts, no sync, and no server-side compute."),
 ],
 "faq_cards": [
  ("What makes a site installable?", "HTTPS, a valid manifest with icons and start_url, and a service worker with a fetch handler. Miss one and the prompt silently never appears."),
  ("Cache-first or network-first?", "Cache-first for the app shell — HTML, CSS, JS, icons. Network-first for anything that goes stale. No backend means almost everything is shell."),
  ("Why is my deploy not showing up?", "The new worker is stuck waiting behind open tabs. Bump the cache name, delete old caches on activate, call skipWaiting() and clients.claim()."),
  ("localStorage or IndexedDB?", "localStorage until it hurts — a few thousand JSON records inside ~5 MB. IndexedDB for binary data, real queries, or when writes cause jank."),
  ("How do you install on iPhone?", "Safari → Share → Add to Home Screen, done manually. iOS has no install prompt and no beforeinstallprompt event to hook."),
  ("Can a PWA run with no server?", "Yes — state in browser storage, shell in the service worker cache. The trade is no accounts, no sync, no server-side compute."),
 ],
},

{
 "slug": "client-side-only-tools",
 "title": "The Case for Client-Side-Only Tools",
 "desc": "No account means no breach surface. What you gain from browser-only tools, what you give up in sync and compute, what it costs to run, and how to say so.",
 "og_title": "The Case for Client-Side-Only Tools",
 "og_desc": "No accounts, no database, no breach surface — and an honest account of what that costs the user.",
 "headline": "The Case for Client-Side-Only Tools",
 "crumb": "Client-Side Tools",
 "about": ["Local-first software", "Privacy by design", "Static hosting"],
 "eyebrow": "Guide · Architecture",
 "h1": "Tools with no backend, and the honest trade",
 "lead": "A tool that never sends data anywhere cannot leak it, cannot lose it in someone else's breach, and cannot be repriced when the hosting bill arrives. It also cannot sync to your phone. Both halves are worth saying out loud.",
 "level": "Beginner",
 "nav": NAV_DEV,
 "body": [
  ("h2", "The default is heavier than the problem"),
  ("p", "Most small utilities get built with an account system, a database, a session store, and a hosting bill — for a calculator. The reflex is so automatic that nobody asks whether the server is doing anything the browser could not."),
  ("p", "For a large class of tools, it is not. A position sizer, a trade journal, a weight tracker, a habit checklist, a unit converter, a text formatter: all of these are pure functions plus a little state. The browser has a JavaScript engine and persistent storage. That is the entire requirement."),
  ("h2", "What you gain"),
  ("h3", "No breach surface"),
  ("p", "The strongest security property available is <strong>not holding the data.</strong> No user table means no credential dump, no password reset flow to phish, no session tokens to steal, no compliance obligation around personal data you never received. You cannot be forced to hand over records that were never on your server, and an attacker who fully compromises the host gets a folder of static files."),
  ("h3", "Data stays where the user can see it"),
  ("p", "Browser storage is inspectable. A curious user can open DevTools and read exactly what the app kept. That is a much stronger claim than a privacy policy, because it is verifiable rather than promised — the network tab shows there are no outbound requests carrying their data."),
  ("h3", "It costs nothing to run"),
  ("p", "Static files on GitHub Pages, Netlify, or Cloudflare Pages cost nothing at realistic personal-project traffic. There is no database to back up, no dependency to patch at 2am, no bill that grows with users. A client-side tool that gets popular gets <em>cheaper</em> per user, not more expensive."),
  ("h3", "It keeps working"),
  ("p", "No server means no outage, no rate limit, no deprecation. Offline through a service worker, it works on a plane. A tool built this way in 2020 still runs today with no maintenance, which is not a claim most SaaS side projects can make."),
  ("h2", "What you give up"),
  ("p", "This is the part most local-first pitches skip, so here it is plainly."),
  ("table", (["You lose", "What that means in practice"],
             [["Cross-device sync", "Data logged on the laptop is not on the phone. Two devices means two separate datasets."],
              ["Backup", "Clearing browser data deletes everything. On iOS, storage can be evicted after long non-use."],
              ["Server-side compute", "No heavy jobs, no scheduled tasks, no calling a paid API without exposing the key."],
              ["Collaboration", "No sharing, no multi-user, no permissions — there is nothing to share through."],
              ["Analytics on usage", "You genuinely do not know how the tool is used, which makes it harder to improve."],
              ["Recovery", "No support ticket can restore what a user deleted, because you never had a copy."]])),
  ("p", "The honest framing is not that these do not matter. It is that <strong>for single-user tools they usually matter less than the ongoing cost of an account system</strong> — for the builder and for the user, who has one more password and one more breach notification in their future."),
  ("h2", "Mitigations that keep the model intact"),
  ("ol", ["<strong>Ship export and import.</strong> A JSON or CSV download turns 'no backup' into 'your backup, your file'. This is the single highest-value feature in a local-only tool.",
          "<strong>Warn before destructive actions</strong> and never auto-clear storage on version change.",
          "<strong>Make the storage key stable</strong> across deploys, and migrate schemas forward rather than resetting them.",
          "<strong>Say where the data lives, in the app,</strong> not only in the privacy policy. One line under the form does more than a page nobody opens.",
          "<strong>If sync is genuinely needed later,</strong> add it as an opt-in layer over the same local store rather than rewriting around a server."]),
  ("h2", "Writing the privacy policy honestly"),
  ("p", "A local-only tool makes for a short, unusually credible privacy policy — but only if it is specific. Vague reassurance reads exactly like every policy that turned out to be false."),
  ("ul", ["Name the storage mechanism: 'stored in your browser's localStorage on this device'.",
          "State plainly that there is no account, no server-side database, and no transmission of entered data.",
          "Disclose what <em>is</em> collected, if anything — static hosting still produces server logs with IP addresses, and any embedded analytics or fonts are third-party requests. Do not claim zero collection while loading a tracker.",
          "Explain the eviction risk: clearing site data deletes it, and browsers may evict storage. Point at the export button in the same sentence.",
          "Skip the legal-sounding padding. A policy a user can read in 60 seconds is more protective than one they cannot."]),
  ("p", 'The test I use: could a technically literate user verify every claim in the policy from the network tab in under a minute? If yes, it is honest. If a claim requires trusting me, it should be softened or removed. <a href="/privacy.html">Mine is here →</a>'),
  ("h2", "When you actually do need a backend"),
  ("p", "Not every tool fits. You need a server when the data is genuinely shared between people, when compute exceeds what a phone browser can do, when an API key must stay secret, when the data must survive a lost device, or when a regulation requires audit trails you can produce. Those are real requirements — the point is to check whether you have one, not to assume you do."),
 ],
 "tools": [("/apps.html", "Apps hub", "three tools built this way — no accounts, no server, no analytics on your entries."),
           ("/apps/cut/", "Cut", "weight tracker with local storage and an export path."),
           ("/privacy.html", "Privacy policy", "a short, verifiable version of the claims described here."),
           ("/stack.html", "My stack", "what static hosting and tooling this runs on.")],
 "faqs": [
  ("What is a client-side-only tool?", "A tool that runs entirely in the browser, with all state kept in browser storage such as localStorage or IndexedDB, and no server component beyond serving static files. There is no account, no database, and no transmission of what the user enters."),
  ("Is a tool without accounts more secure?", "For the user's data, generally yes, because the strongest protection is not holding the data at all. There is no user table to dump, no session tokens to steal, and no password reset flow to phish. It does not make the code itself more secure, and it offers no protection if the device is compromised."),
  ("What do you lose with no backend?", "Cross-device sync, server-side backup and recovery, collaboration between users, server-side compute, secret API keys, and any real usage analytics. For single-user tools these usually matter less than the cost of running an account system, but they are real losses and should be disclosed."),
  ("What does it cost to run a client-side tool?", "Effectively nothing. Static files on GitHub Pages, Netlify, or Cloudflare Pages are free at personal-project traffic levels, and there is no database to back up or patch. Cost per user falls as usage grows rather than rising."),
  ("How do users back up data in a browser-only app?", "Through an export function that downloads their data as JSON or CSV, which they store themselves. This is the single most important feature in a local-only tool, because clearing site data deletes everything and browsers can evict storage after extended non-use."),
  ("What should a local-only privacy policy say?", "Name the exact storage mechanism, state that there is no account and no server-side database, disclose anything that is still collected such as hosting server logs or third-party fonts and analytics, explain that clearing site data deletes everything, and point at the export button. Every claim should be verifiable from the browser's network tab."),
 ],
 "faq_cards": [
  ("What is a client-side-only tool?", "Runs entirely in the browser, state in localStorage or IndexedDB, no server beyond static files. No account, no database, nothing transmitted."),
  ("Is no-account more secure?", "For user data, yes — the strongest protection is not holding it. No user table, no tokens, no reset flow to phish. It does not protect a compromised device."),
  ("What do you give up?", "Sync, backup, recovery, collaboration, server-side compute, secret API keys, and real usage analytics. Say so rather than hiding it."),
  ("What does it cost to run?", "Effectively zero. Static hosting is free at personal traffic, nothing to back up or patch, and cost per user falls as usage grows."),
  ("How do users back up?", "An export button that downloads JSON or CSV. Highest-value feature in a local-only tool — clearing site data wipes everything."),
  ("What goes in the privacy policy?", "The exact storage mechanism, no account or database, whatever hosting logs still collect, the eviction risk, and the export path. Verifiable claims only."),
 ],
},

{
 "slug": "ffmpeg-auto-editing",
 "title": "Automated Video Editing With ffmpeg",
 "desc": "Scene-change detection, audio-energy highlights, lossless cutting and concatenation, 9:16 vertical conversion, and why a local pipeline beats a cloud API.",
 "og_title": "Automated Video Editing With ffmpeg",
 "og_desc": "Scene detection, audio-energy highlights, cutting, concatenation, and 9:16 conversion — all locally.",
 "headline": "Automated Video Editing With ffmpeg: Detection, Cutting, Vertical",
 "crumb": "ffmpeg Auto-Editing",
 "about": ["ffmpeg", "Video processing", "Automation"],
 "eyebrow": "Guide · Media",
 "h1": "Turning long footage into clips, automatically",
 "lead": "An automatic editor is not one clever algorithm. It is a detector that proposes cut points, a scorer that ranks segments, and a cutter that stitches the winners together — and ffmpeg can do all three from the command line.",
 "level": "Intermediate",
 "nav": NAV_DEV,
 "body": [
  ("h2", "The shape of the pipeline"),
  ("ol", ["<strong>Probe</strong> — read duration, resolution, frame rate, and audio layout so nothing downstream guesses.",
          "<strong>Detect</strong> — find candidate boundaries with scene-change detection and candidate highlights with audio energy.",
          "<strong>Score and select</strong> — rank the candidate segments and pick the ones that fit the target runtime.",
          "<strong>Cut</strong> — extract the selected ranges, ideally without re-encoding.",
          "<strong>Assemble</strong> — concatenate, convert aspect ratio, normalise loudness, encode once at the end."]),
  ("p", "The discipline that keeps this fast is doing all the analysis on cheap passes and <strong>encoding exactly once</strong>, at the end. Every intermediate re-encode costs time and a generation of quality."),
  ("h2", "Probe first"),
  ("formula", "ffprobe -v error -show_entries \\\n  format=duration:stream=width,height,r_frame_rate,codec_type \\\n  -of json input.mp4"),
  ("p", "Hardcoding 1920x1080 at 30fps is how a pipeline breaks on the first phone clip someone hands you. Read it, branch on it."),
  ("h2", "Scene-change detection"),
  ("p", "ffmpeg's <code>select</code> filter exposes a per-frame <code>scene</code> score between 0 and 1, measuring how different a frame is from its predecessor. Thresholding that score gives you cut candidates."),
  ("formula", "ffmpeg -i input.mp4 \\\n  -filter:v \"select='gt(scene,0.4)',showinfo\" \\\n  -f null - 2&gt;&amp;1 | grep showinfo\n\n# print timestamps only, machine-readable\nffprobe -show_frames -of csv=p=0 \\\n  -f lavfi \"movie=input.mp4,select=gt(scene\\,0.4)\" \\\n  -show_entries frame=pkt_pts_time"),
  ("ul", ["<strong>0.3</strong> — sensitive. Fires on camera movement and lighting changes as well as real cuts.",
          "<strong>0.4</strong> — a reasonable default for mixed footage.",
          "<strong>0.5 and above</strong> — hard cuts only. Misses dissolves and slow transitions entirely.",
          "Single continuous shots — a locked-off camera at an event produces almost no scene changes, so this detector contributes nothing and audio has to carry the selection."]),
  ("h2", "Finding highlights with audio"),
  ("p", "For unedited footage — an event, a talk, a match — the visual track is often uniform and the interesting moments are audible: a cheer, a laugh, a sudden loudness jump. Audio energy is a crude but effective highlight detector, and it is cheap to compute."),
  ("formula", "# per-window loudness, one line per measurement\nffmpeg -i input.mp4 -af ebur128=framelog=verbose -f null - 2&gt;&amp;1\n\n# volume statistics across the whole file\nffmpeg -i input.mp4 -af volumedetect -f null - 2&gt;&amp;1\n\n# detect silence, then treat the gaps between silences as segments\nffmpeg -i input.mp4 -af silencedetect=noise=-30dB:d=0.6 -f null - 2&gt;&amp;1"),
  ("p", "Two approaches that work in practice. <strong>Peak-relative:</strong> compute short-term loudness over one-second windows, then keep windows more than roughly 6 dB above the file's median — those are your spikes. <strong>Silence-inverted:</strong> use <code>silencedetect</code> to find quiet gaps, treat the audible stretches between them as natural segments, and rank those segments by mean loudness."),
  ("p", "Then pad each pick: a highlight starts before the spike. Two to three seconds of lead-in and one to two of tail turns a jarring fragment into a watchable clip."),
  ("h2", "Cutting without re-encoding"),
  ("p", "Stream copy is enormously faster than re-encoding, but it can only cut at keyframes. Put <code>-ss</code> before <code>-i</code> and ffmpeg seeks quickly to the nearest keyframe; put it after, and it decodes up to the exact frame, which is accurate and slow."),
  ("formula", "# fast, keyframe-aligned, no quality loss\nffmpeg -ss 00:01:12 -i input.mp4 -t 8 -c copy clip01.mp4\n\n# frame-accurate, re-encodes\nffmpeg -i input.mp4 -ss 00:01:12.400 -t 8 \\\n  -c:v libx264 -crf 18 -preset veryfast -c:a aac clip01.mp4"),
  ("p", "The pragmatic compromise: cut with stream copy when the keyframe interval is small enough that a fraction of a second of drift does not matter, and re-encode only the clips where the cut point must be exact. Or force a short keyframe interval when you control the source encode."),
  ("h2", "Concatenating the picks"),
  ("p", "The concat demuxer joins files without re-encoding, but only when every input shares the same codec, resolution, frame rate, and audio parameters. Mixed sources need the concat filter, which re-encodes."),
  ("formula", "# clips.txt\nfile 'clip01.mp4'\nfile 'clip02.mp4'\nfile 'clip03.mp4'\n\nffmpeg -f concat -safe 0 -i clips.txt -c copy reel.mp4"),
  ("warn", "If concatenated output plays the first clip and then freezes or desyncs, the inputs did not actually match. Normalise every clip to identical codec, resolution, frame rate, sample rate, and channel layout first, or switch to the concat filter and accept one re-encode."),
  ("h2", "Converting to 9:16 vertical"),
  ("p", "Vertical delivery from horizontal footage is a framing decision, not a resize. Three options, in ascending order of effort:"),
  ("table", (["Approach", "How it looks", "When to use it"],
             [["Blurred-background pad", "Original centred, blurred enlarged copy behind it", "Fast, safe default for talking-head and wide shots"],
              ["Centre crop", "Fills the frame, cuts off both sides", "Subject reliably centred; loses anything at the edges"],
              ["Tracked crop", "Crop window follows the subject", "Best result, needs detection per frame and real work"]])),
  ("formula", "# blurred-background 1080x1920\nffmpeg -i reel.mp4 -filter_complex \\\n \"[0:v]scale=1080:-2,boxblur=20:2,crop=1080:1920[bg];\\\n  [0:v]scale=1080:-2[fg];\\\n  [bg][fg]overlay=(W-w)/2:(H-h)/2\" \\\n -c:a copy vertical.mp4\n\n# centre crop to 9:16\nffmpeg -i reel.mp4 -vf \\\n \"crop=ih*9/16:ih,scale=1080:1920\" -c:a copy vertical.mp4"),
  ("p", "Finish with loudness normalisation so clips cut from different parts of a recording do not jump in volume. The two-pass <code>loudnorm</code> filter targeting around −14 LUFS is the usual choice for social platforms."),
  ("formula", "ffmpeg -i vertical.mp4 -af loudnorm=I=-14:TP=-1.5:LRA=11 \\\n  -c:v copy final.mp4"),
  ("h2", "Why local beats an API for this"),
  ("ul", ["<strong>No upload.</strong> A 4 GB event recording takes longer to upload on a home connection than to process locally. The transfer is the bottleneck, not the compute.",
          "<strong>No per-minute cost.</strong> Video APIs price per minute processed. Iterating on a threshold means reprocessing the same footage twenty times — free locally, expensive per call.",
          "<strong>No rights question.</strong> Footage of identifiable people at an event does not go to a third party at all, which removes both a consent conversation and a terms-of-service question about training use.",
          "<strong>Deterministic and debuggable.</strong> The same command produces the same output, and every intermediate is a file you can open.",
          "<strong>No dependency on someone else's uptime or pricing page.</strong> The pipeline works the same in three years."]),
  ("p", "The honest counterpoint: an API gives you transcription, face tracking, and semantic highlight selection that a local ffmpeg pipeline does not have without extra models. If your selection logic genuinely needs to understand speech, run a local transcription model and keep the rest of the pipeline where it is."),
  ("p", 'This is the architecture behind <a href="/eventreels.html">EventReels</a> — probe, detect, score, cut, assemble, one encode at the end, entirely on the machine.'),
 ],
 "tools": [("/eventreels.html", "EventReels", "the working auto-editing pipeline this guide describes."),
           ("/stack.html", "My stack", "the rest of the tooling around it."),
           ("/guides/local-llm-ollama.html", "Local LLM guide", "the same local-over-API argument applied to language models."),
           ("/guides/ai-automation-small-business.html", "AI automation guide", "where a pipeline like this fits into an actual workflow.")],
 "faqs": [
  ("How do you detect scene changes with ffmpeg?", "Use the select filter's scene score, which rates how different each frame is from the previous one on a 0 to 1 scale, and threshold it — for example select='gt(scene,0.4)'. Around 0.3 is sensitive and fires on camera movement, 0.4 is a reasonable default, and 0.5 or above catches hard cuts only."),
  ("How do you find highlights in a video automatically?", "Analyse audio energy rather than video. Compute short-term loudness with the ebur128 filter and keep windows several decibels above the file's median, or use silencedetect to find quiet gaps and rank the audible segments between them by mean loudness. Pad each pick with a few seconds of lead-in."),
  ("How do you cut a video without re-encoding?", "Use -c copy for stream copy, with -ss placed before -i so ffmpeg seeks quickly. The limitation is that stream copy can only cut at keyframes, so the cut point may drift by a fraction of a second; put -ss after -i and re-encode when the cut must be frame-accurate."),
  ("Why does concatenated ffmpeg output freeze or desync?", "The concat demuxer with -c copy requires every input to share the same codec, resolution, frame rate, sample rate, and channel layout. When they differ, playback typically works for the first clip then breaks. Normalise all clips to identical parameters first, or use the concat filter and accept one re-encode."),
  ("How do you convert horizontal video to 9:16 vertical?", "Three options: pad with a blurred, enlarged copy of the video behind the original, which is the safe default; centre-crop to ih*9/16 by ih and scale to 1080x1920, which fills the frame but loses the edges; or track the subject and move the crop window, which looks best but requires per-frame detection."),
  ("Why use a local ffmpeg pipeline instead of a video API?", "No upload time on large files, no per-minute processing cost while you iterate on thresholds, no third party receiving footage of identifiable people, deterministic output you can debug file by file, and no exposure to another company's pricing or uptime. The trade is that APIs bundle transcription and face tracking that ffmpeg alone does not provide."),
 ],
 "faq_cards": [
  ("How do you detect scene changes?", "Threshold the select filter's scene score: gt(scene,0.4) is a fair default. 0.3 fires on camera movement, 0.5+ catches hard cuts only."),
  ("How do you find highlights?", "By audio, not video. Loudness spikes above the median via ebur128, or invert silencedetect and rank the audible segments. Pad the lead-in."),
  ("How do you cut without re-encoding?", "-ss before -i with -c copy. Fast and lossless, but cuts land on keyframes — re-encode only the clips that must be frame-accurate."),
  ("Why does concat break?", "The concat demuxer needs identical codec, resolution, frame rate, and audio params. Mismatched inputs play clip one then freeze."),
  ("How do you go vertical?", "Blurred-background pad is the safe default; centre crop fills the frame but loses the edges; tracked crop looks best and costs real work."),
  ("Why local instead of an API?", "No upload, no per-minute cost while iterating, no footage handed to a third party, deterministic and debuggable. APIs still win on transcription."),
 ],
},

{
 "slug": "print-on-demand-economics",
 "title": "Print-on-Demand Margin Math, Honestly",
 "desc": "Base cost, retail, platform fees, and net per unit on a tee and a hoodie — plus the costs people forget: returns, samples, artwork time, and ads.",
 "og_title": "Print-on-Demand Margin Math, Honestly",
 "og_desc": "A worked net-per-unit table on a tee and a hoodie, and the costs that quietly eat the margin.",
 "headline": "Print-on-Demand Margin Math, Honestly",
 "crumb": "Print-on-Demand Math",
 "about": ["Print on demand", "Unit economics", "Ecommerce"],
 "eyebrow": "Guide · Business",
 "h1": "The margin is fine. The volume is the problem.",
 "lead": "Print-on-demand removes inventory risk, which is the thing that kills most clothing brands. What it does not remove is the arithmetic: a good margin on a product nobody has heard of still earns nothing.",
 "type": "Article",
 "nav": NAV_BRAND,
 "body": [
  ("callout", "Every figure below is an <strong>illustrative example of the arithmetic</strong>, chosen to be realistic in shape. They are not quotes from any specific supplier and they are not results from any brand. Suppliers price differently by garment, print area, colour count, and region — run your own numbers against a real quote before deciding anything."),
  ("h2", "The three numbers"),
  ("p", "Print-on-demand economics reduce to base cost, retail price, and platform fee. Everything else is a variation on those three."),
  ("ul", ["<strong>Base cost</strong> — what the supplier charges to print and ship one unit. Rises with garment quality, print area, number of print locations, and colour count.",
          "<strong>Retail price</strong> — what you charge. The only lever you fully control, and the one most people set too low out of nerves.",
          "<strong>Platform fee</strong> — the storefront's cut plus payment processing. Typically a percentage plus a fixed per-transaction charge."]),
  ("formula", "net per unit = retail − base cost − platform fee\n\nplatform fee ≈ (retail × fee rate) + fixed transaction charge"),
  ("h2", "A worked example on a tee"),
  ("p", "Illustrative numbers: a mid-weight tee with a single front print, retailing at $32, on a storefront taking 5% plus roughly 3% payment processing and $0.30 per transaction."),
  ("table", (["Line", "Amount", "Note"],
             [["Retail", "$32.00", "Customer pays this plus shipping"],
              ["Base cost (print + fulfilment)", "−$13.30", "Garment, print, pick and pack"],
              ["Platform + processing (~8%)", "−$2.56", "Illustrative blended rate"],
              ["Fixed transaction fee", "−$0.30", "Per order, not per item"],
              ["<strong>Net per unit</strong>", "<strong>$15.84</strong>", "About 49% of retail"]])),
  ("h2", "The same math on a hoodie"),
  ("p", "Hoodies carry a much higher base cost, so the percentage margin compresses even though the dollar margin grows."),
  ("table", (["Line", "Amount", "Note"],
             [["Retail", "$58.00", ""],
              ["Base cost", "−$19.20", "Heavier garment, larger print area"],
              ["Platform + processing (~8%)", "−$4.64", ""],
              ["Fixed transaction fee", "−$0.30", ""],
              ["<strong>Net per unit</strong>", "<strong>$33.86</strong>", "About 58% of retail"]])),
  ("p", "Read those two tables together and the first real lesson appears: <strong>the hoodie earns more than twice the dollars per sale</strong>, which matters far more than the percentage. Percentages do not pay rent; dollars per order do. This is why brands push toward higher-ticket items and multi-item carts rather than optimising a tee's margin by a point."),
  ("h2", "The volume problem"),
  ("p", "$15.84 a shirt sounds fine until you multiply it."),
  ("table", (["Units sold / month", "Gross margin at $15.84", "What that actually is"],
             [["10", "$158", "A hobby"],
              ["50", "$792", "A meaningful side income"],
              ["200", "$3,168", "A part-time job with real operational load"],
              ["1,000", "$15,840", "A business, with staffing and support needs"]])),
  ("p", "Selling 200 shirts a month is not a design problem. It is a distribution problem — audience, content cadence, repeat customers, and retention. <strong>Print-on-demand solves inventory risk and solves nothing about demand,</strong> and demand is the part that is genuinely hard. The people who quit usually quit with a good product and no traffic."),
  ("h2", "The costs nobody puts in the spreadsheet"),
  ("table", (["Hidden cost", "Typical shape", "Effect on net"],
             [["Returns and reprints", "A few percent of orders, often on you rather than the supplier", "Shaves a few percent off net across all units"],
              ["Samples", "One unit of each product, at your own cost, plus shipping", "A fixed upfront spend before any revenue exists"],
              ["Artwork time", "Hours per design, plus mockups and revisions", "Free only if your time is worthless"],
              ["Ads", "Cost per acquisition frequently exceeds net per unit on a single item", "Can turn a positive-margin product into a loss"],
              ["Shipping expectations", "Customers expect free or cheap shipping", "Either raise retail or absorb it out of net"],
              ["Payment disputes", "Chargebacks carry the refund plus a fixed fee", "Small in volume, painful per event"],
              ["Platform changes", "Base costs and fee rates get revised", "Your margin is quietly repriced by someone else"]])),
  ("p", "The one that ends most stores is the ads line. If net per unit is $15.84 and it costs $22 in ads to acquire a customer who buys one item, every sale loses money — and that only becomes visible after you have spent enough to see it. The escape routes are higher average order value, repeat purchases, or acquisition that does not cost money per unit, which is what organic content actually is."),
  ("h2", "Pricing, briefly"),
  ("ol", ["<strong>Start from the net you need,</strong> not from what competitors charge. Work backwards to retail.",
          "<strong>Price the bundle, not the item.</strong> The fixed transaction fee is per order, so a two-item cart is structurally more profitable.",
          "<strong>Do not compete on price against a supplier that has scale you do not.</strong> You will lose, and you will lose on your own margin.",
          "<strong>Recheck after every supplier price change.</strong> Base costs move; retail prices usually do not until someone notices.",
          "<strong>Treat free shipping as a price increase,</strong> because it is one. Fold it into retail deliberately rather than absorbing it silently."]),
  ("h2", "Why print-on-demand is still the right start"),
  ("p", "Held against the alternative, the case is strong. Bulk ordering 200 units means several thousand dollars committed before a single customer exists, a size curve guessed in advance, and boxes in a room. Print-on-demand trades roughly a third of the per-unit margin for zero inventory risk, no minimum order, and the ability to kill a design that does not sell without eating the stock."),
  ("p", 'For testing whether a design has an audience at all, that trade is clearly correct. Move to bulk only once a specific item has demonstrated repeat demand — and at that point the higher margin is earned by evidence rather than assumed. This is the model behind <a href="/kxngsef.html">KXNG SEF</a> and <a href="/heft.html">HEFT</a>: no inventory, no minimums, designs that do not sell simply stop being printed.'),
 ],
 "tools": [("/kxngsef.html", "KXNG SEF", "clothing brand run on a print-on-demand model."),
           ("/heft.html", "HEFT", "second brand on the same fulfilment model."),
           ("/store.html", "Store", "the digital-product side, where the unit economics work very differently."),
           ("/guides/ai-automation-small-business.html", "AI automation guide", "reducing the per-order operational load.")],
 "faqs": [
  ("How do you calculate print-on-demand profit per unit?", "Net per unit equals retail price minus base cost minus platform fees, where platform fees are usually a percentage of retail plus a fixed per-transaction charge. As an illustrative example, a $32 tee with a $13.30 base cost and roughly 8% plus $0.30 in fees nets about $15.84."),
  ("What margin is realistic on print-on-demand?", "Illustratively, around 45 to 60% of retail once base cost and platform fees are removed, with hoodies typically showing a higher percentage and a much higher dollar margin than tees. Actual figures depend entirely on your supplier, garment, print area, and storefront, so run the numbers against a real quote."),
  ("Is print-on-demand profitable?", "Per unit, usually yes. In total, only at volume — an illustrative $15.84 net per shirt means 10 sales a month is a hobby and 200 is a part-time job. Print-on-demand removes inventory risk but does nothing about demand, which is the genuinely hard part."),
  ("What costs do print-on-demand sellers forget?", "Returns and reprints, samples bought at your own cost, the hours spent on artwork and mockups, shipping that customers expect to be free, chargebacks, and above all advertising. Ad cost per acquisition frequently exceeds net per unit on a single item, which turns a profitable product into a loss."),
  ("Should you sell tees or hoodies?", "Hoodies carry a higher base cost but a much larger dollar margin per sale — illustratively about $33.86 against $15.84. Since the fixed transaction fee is charged per order rather than per item, higher-ticket products and multi-item carts are structurally more profitable than optimising a tee's margin."),
  ("Is print-on-demand better than bulk ordering?", "For starting out, yes. Bulk ordering commits thousands of dollars and a guessed size curve before any customer exists. Print-on-demand gives up roughly a third of the per-unit margin in exchange for zero inventory risk and no minimum order, which is the right trade until a specific design has proven repeat demand."),
 ],
 "faq_cards": [
  ("How is net per unit calculated?", "Retail minus base cost minus platform fee, where the fee is a percentage plus a fixed per-order charge. Illustrative $32 tee nets about $15.84."),
  ("What margin is realistic?", "Illustratively 45–60% of retail after base cost and fees. Depends entirely on supplier, garment, and print area — get a real quote."),
  ("Is it profitable?", "Per unit yes, in total only at volume. 10 shirts a month is a hobby, 200 is a part-time job. POD fixes inventory risk, not demand."),
  ("What costs get forgotten?", "Returns, samples, artwork hours, free shipping, chargebacks, and ads. Ad cost per customer often exceeds net per single item."),
  ("Tees or hoodies?", "Hoodies. Illustratively $33.86 net against $15.84, and the fixed fee is per order — so higher ticket and bigger carts win."),
  ("POD or bulk?", "POD to start. Bulk commits thousands and a guessed size curve upfront; POD trades about a third of margin for zero inventory risk."),
 ],
},

{
 "slug": "ai-search-optimization",
 "title": "How to Get Cited by AI Answer Engines (GEO/AEO)",
 "desc": "Entity consolidation, llms.txt, robots.txt rules for named AI crawlers, FAQPage that mirrors visible text, answer-first writing, and IndexNow for fast recrawl.",
 "og_title": "How to Get Cited by AI Answer Engines",
 "og_desc": "Entity consolidation, llms.txt, AI crawler rules, mirrored FAQPage schema, and answer-first structure.",
 "headline": "How to Get Cited by AI Answer Engines: Entities, llms.txt, and Structure",
 "crumb": "AI Search Optimization",
 "about": ["Generative engine optimization", "Structured data", "Technical SEO"],
 "eyebrow": "Guide · SEO",
 "h1": "Getting cited when the answer replaces the click",
 "lead": "Ranking and being cited are now different problems. An answer engine reads a handful of sources, decides which ones are unambiguous enough to quote, and names those. Being quotable is a structural property, and it is one you can engineer.",
 "level": "Intermediate",
 "nav": NAV_DEV,
 "body": [
  ("h2", "What changed"),
  ("p", "Classic SEO optimised for a ranked list of ten links. AI answer engines — ChatGPT search, Perplexity, Copilot, Google's AI overviews, Claude's web search — synthesise a single answer from a few retrieved sources and cite some of them. That shifts the target from <em>rank higher</em> to <strong>be the passage a model can lift verbatim and attribute confidently.</strong>"),
  ("p", "The practices go by two names: <strong>GEO</strong> (generative engine optimization) and <strong>AEO</strong> (answer engine optimization). They overlap almost entirely, and neither requires abandoning normal SEO — a page that is crawlable, fast, and structured still wins both. What changes is the emphasis: unambiguous entities, self-contained passages, and machine-readable facts."),
  ("h2", "Entity consolidation: one @id, referenced everywhere"),
  ("p", "The single highest-leverage technical move is making a retrieval system certain <em>who</em> the site is about. If ten pages each declare a separate Person node, a model sees ten weakly-connected entities. If ten pages reference one canonical <code>@id</code>, it sees one entity with ten pieces of evidence."),
  ("formula", "// on the homepage only — the canonical definition\n{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"Person\",\n  \"@id\": \"https://example.com/#person\",\n  \"name\": \"Full Name\",\n  \"url\": \"https://example.com/\",\n  \"jobTitle\": \"...\",\n  \"knowsAbout\": [\"...\", \"...\"],\n  \"sameAs\": [\n    \"https://github.com/handle\",\n    \"https://www.linkedin.com/in/handle\",\n    \"https://orcid.org/0000-...\"\n  ]\n}\n\n// on every other page — reference, never redefine\n\"author\":    {\"@id\": \"https://example.com/#person\"},\n\"publisher\": {\"@id\": \"https://example.com/#person\"}"),
  ("ul", ["<strong>Define once, reference everywhere.</strong> Re-stating the full Person object on every page invites contradictions, and contradictions are what make a model hedge instead of cite.",
          "<strong><code>sameAs</code> is the disambiguation lever.</strong> Link the profiles that already have independent authority — GitHub, LinkedIn, ORCID, a publisher DOI page. This is how an entity gets tied to an existing graph rather than floating alone.",
          "<strong>Keep names byte-identical</strong> across schema, page text, and external profiles. 'J. Smith' in one place and 'John Smith' in another is two entities as far as a matcher is concerned.",
          "<strong>Use <code>knowsAbout</code> deliberately.</strong> It is a direct statement of topical scope, and it is one of the few places you get to declare it rather than have it inferred.",
          "<strong>Validate every deploy.</strong> A JSON-LD syntax error means the block is skipped entirely and silently."]),
  ("h2", "llms.txt and llms-full.txt"),
  ("p", "<code>llms.txt</code> is a proposed convention: a markdown file at the site root that gives a language model a clean, navigable summary of the site without HTML, navigation, or scripts. <code>llms-full.txt</code> is the expanded version containing the actual content."),
  ("formula", "# Site Name\n\n&gt; One-sentence description of who this is and what the site covers.\n\n## Guides\n- [Offline PWA](https://example.com/guides/offline-pwa.html): building an\n  installable offline app with no backend.\n- [RAG explained](https://example.com/guides/rag-explained.html): chunking,\n  embeddings, reranking, and where pipelines fail.\n\n## Projects\n- [Project name](https://example.com/project.html): what it does, in one line.\n\n## Contact\n- email@example.com"),
  ("p", "Two honest caveats. First, adoption is not universal — no major crawler has committed to it as a requirement, so treat it as cheap insurance rather than a guaranteed channel. Second, it is <strong>not a place to say something different from the site.</strong> Contradiction between llms.txt and the rendered pages is worse than having no file, because it introduces exactly the ambiguity you are trying to eliminate."),
  ("p", "The reason to ship it anyway: it costs an hour, it is trivially machine-parseable, and it forces you to write a clean one-line description of every page — which is useful regardless of who reads it."),
  ("h2", "robots.txt and the named AI crawlers"),
  ("p", "AI companies operate separately-named agents, often splitting training crawlers from live-retrieval crawlers. Those are different decisions: blocking training while allowing retrieval is a coherent position, and so is the reverse."),
  ("table", (["Agent", "Operator", "Primary purpose"],
             [["GPTBot", "OpenAI", "Training data collection"],
              ["OAI-SearchBot", "OpenAI", "Live search retrieval and citation"],
              ["ChatGPT-User", "OpenAI", "Fetches a page a user asked about"],
              ["ClaudeBot", "Anthropic", "Crawling for model training"],
              ["Claude-User / Claude-SearchBot", "Anthropic", "User-initiated fetch and search indexing"],
              ["PerplexityBot", "Perplexity", "Search index used for cited answers"],
              ["Google-Extended", "Google", "Controls Gemini training use; does not affect Search ranking"],
              ["Applebot-Extended", "Apple", "Controls Apple Intelligence training use"],
              ["Bingbot", "Microsoft", "Bing index, which also feeds Copilot"],
              ["CCBot", "Common Crawl", "Open crawl corpus used by many trainers"]])),
  ("formula", "User-agent: GPTBot\nAllow: /\n\nUser-agent: OAI-SearchBot\nAllow: /\n\nUser-agent: ClaudeBot\nAllow: /\n\nUser-agent: PerplexityBot\nAllow: /\n\nUser-agent: Google-Extended\nAllow: /\n\nUser-agent: Applebot-Extended\nAllow: /\n\nSitemap: https://example.com/sitemap.xml"),
  ("warn", "Blocking <code>Google-Extended</code> does not remove you from Google Search, and blocking a training crawler does not remove you from that company's live search results — the agents are separate. Equally, if you want to be cited, blocking the retrieval bots guarantees you will not be. Decide training and retrieval independently, and know which name controls which."),
  ("p", "<code>robots.txt</code> is a request, not enforcement. Crawlers that ignore it will ignore it. If content genuinely must not be read, it needs authentication, not a directive."),
  ("h2", "FAQPage schema — and the rule that breaks sites"),
  ("p", "FAQPage markup is well-suited to answer engines: it is a list of question-answer pairs in exactly the shape a retrieval system wants. There is one hard rule."),
  ("warn", "<strong>Every question and answer in FAQPage markup must appear as visible text on the same page.</strong> Schema-only FAQ content — questions that exist in the JSON-LD but not on screen — violates Google's structured data guidelines and is a well-known cause of manual actions. Generate the visible FAQ and the schema from the same source so they cannot drift."),
  ("ul", ["Write answers that stand alone. 'It depends on the above' is unquotable; a model lifting that sentence out of context produces nothing useful.",
          "Two to four sentences per answer. Long enough to be complete, short enough to be lifted whole.",
          "Answer in the first sentence, then qualify. Never build to the answer.",
          "Use the question form a person would actually type or say, not a keyword-stuffed variant.",
          "Do not mark up promotional copy as an FAQ. It is the most common misuse and it does not survive review."]),
  ("h2", "Answer-first writing and question-shaped headings"),
  ("p", "Retrieval works on passages, not pages. A model chunks your page, embeds the chunks, and pulls the ones that match the query. That has direct consequences for structure."),
  ("ol", ["<strong>Make headings questions</strong> where it is natural — 'How do you detect scene changes?' rather than 'Detection'. The heading is often the strongest signal for what the chunk beneath it answers.",
          "<strong>Answer in the first sentence under the heading.</strong> A paragraph that spends three sentences setting up context gets chunked away from its own conclusion.",
          "<strong>Make each section self-contained.</strong> Assume the reader has only that chunk, because the model might.",
          "<strong>Use tables and lists for comparisons.</strong> They survive chunking better than prose and are easier to extract cleanly.",
          "<strong>Put specifics in the text.</strong> Numbers, versions, exact command names, and dates are what makes a passage worth citing over a generic competitor.",
          "<strong>State facts plainly and once.</strong> Hedged, repetitive prose gives a model nothing crisp to quote."]),
  ("p", "The underlying test is simple: <strong>if someone pasted one section of your page into a chat with no other context, would it answer the question?</strong> If not, that section will not get cited."),
  ("h2", "IndexNow for fast recrawl"),
  ("p", "IndexNow is a protocol supported by Bing, Yandex, Seznam and others that lets you push URLs the moment they change instead of waiting for a crawl. That matters for AI search because Copilot is built on the Bing index — faster Bing recrawl means faster Copilot freshness."),
  ("formula", "# 1. host a key file at the site root\n#    https://example.com/&lt;key&gt;.txt  containing exactly &lt;key&gt;\n\n# 2. ping on publish\ncurl \"https://api.indexnow.org/indexnow?url=https://example.com/guides/new.html&amp;key=&lt;key&gt;\"\n\n# or submit a batch\ncurl -X POST https://api.indexnow.org/indexnow \\\n  -H \"Content-Type: application/json\" -d '{\n    \"host\": \"example.com\",\n    \"key\": \"&lt;key&gt;\",\n    \"keyList\": [\"https://example.com/guides/new.html\"]\n  }'"),
  ("p", "Google does not participate in IndexNow; for Google, keep the sitemap current and submit it in Search Console. Do not spam either — pinging unchanged URLs repeatedly is the fastest way to have the signal ignored."),
  ("h2", "A checklist that fits on one screen"),
  ("ol", ["One canonical Person or Organization node with a stable <code>@id</code> and a full <code>sameAs</code> list, defined once and referenced from every page.",
          "Article or TechArticle schema on every content page, with <code>author</code> and <code>publisher</code> pointing at that <code>@id</code>.",
          "BreadcrumbList on every page below the root.",
          "FAQPage that mirrors visible on-page text exactly, generated from the same source.",
          "<code>llms.txt</code> and <code>llms-full.txt</code> at the root, consistent with the site.",
          "<code>robots.txt</code> with an explicit, deliberate decision for each named AI agent, plus a sitemap line.",
          "Question-shaped headings, answer-first paragraphs, self-contained sections.",
          "A current <code>sitemap.xml</code> listing every real page, submitted to Search Console.",
          "IndexNow ping wired into the publish step.",
          "Validate JSON-LD on every deploy — one syntax error silently discards the whole block."]),
  ("p", 'This site implements the full list, which is the only reason I can describe it concretely: the canonical Person node lives on the homepage and every page references it, <a href="/llms.txt">/llms.txt</a> and <a href="/llms-full.txt">/llms-full.txt</a> are generated alongside the pages, <a href="/ai.txt">/ai.txt</a> and robots.txt state the crawler policy explicitly, and every guide including this one carries TechArticle plus BreadcrumbList plus an FAQPage that mirrors the visible FAQ below. <a href="/about.html">The entity page is here →</a>'),
 ],
 "tools": [("/about.html", "About", "the canonical entity page every schema node on this site points at."),
           ("/guides/rag-explained.html", "RAG explained", "how retrieval actually chunks and ranks your pages — useful context for all of this."),
           ("/stack.html", "My stack", "the generator and tooling behind the structured data here."),
           ("/apps.html", "Apps hub", "an example of the same schema pattern applied to product pages.")],
 "faqs": [
  ("What is generative engine optimization (GEO)?", "GEO, also called answer engine optimization or AEO, is the practice of structuring a site so AI answer engines can retrieve, understand, and cite it. It shifts the goal from ranking in a list of links to being the passage a model can lift verbatim and attribute with confidence."),
  ("Why does entity consolidation matter for AI search?", "Because a retrieval system needs to be certain who a site is about. Defining one canonical schema.org Person or Organization node with a stable @id, and referencing that @id from every other page rather than redefining it, turns ten weakly-connected entities into one entity with ten pieces of supporting evidence. A sameAs list linking authoritative profiles ties it to the wider graph."),
  ("What is llms.txt?", "llms.txt is a proposed convention: a markdown file at the site root giving language models a clean, navigable summary of the site without HTML or navigation, with llms-full.txt holding the expanded content. Adoption is not universal, so treat it as cheap insurance, and never let it say anything that contradicts the rendered pages."),
  ("Which AI crawlers should robots.txt address?", "At minimum GPTBot and OAI-SearchBot from OpenAI, ClaudeBot and Claude-SearchBot from Anthropic, PerplexityBot, Google-Extended, Applebot-Extended, Bingbot, and CCBot. Training crawlers and live-retrieval crawlers are separate agents, so decide them independently — blocking Google-Extended does not affect Google Search ranking, and blocking retrieval bots guarantees you will not be cited."),
  ("Does FAQPage schema have to match the visible page?", "Yes. Every question and answer in FAQPage markup must appear as visible text on the same page. Schema-only FAQ content violates Google's structured data guidelines and is a known cause of manual actions, so generate the visible FAQ and the JSON-LD from a single source to prevent drift."),
  ("What is IndexNow?", "IndexNow is a protocol supported by Bing, Yandex, and others that lets a site push changed URLs for immediate recrawl instead of waiting to be crawled. It matters for AI search because Copilot is built on the Bing index. Google does not participate, so keep a current sitemap submitted in Search Console for that side."),
 ],
 "faq_cards": [
  ("What is GEO/AEO?", "Structuring a site so answer engines can retrieve and cite it. The goal moves from ranking in a list to being the quotable, attributable passage."),
  ("Why consolidate entities?", "One canonical Person or Organization @id, referenced from every page, plus a sameAs list. Ten references to one entity beat ten separate ones."),
  ("What is llms.txt?", "A markdown summary of the site at the root, with llms-full.txt for full content. Cheap insurance — and it must never contradict the pages."),
  ("Which AI crawlers matter?", "GPTBot, OAI-SearchBot, ClaudeBot, Claude-SearchBot, PerplexityBot, Google-Extended, Applebot-Extended, Bingbot, CCBot. Training and retrieval are separate calls."),
  ("Must FAQ schema match the page?", "Yes. Every Q and A must be visible on-page. Schema-only FAQ breaks Google's guidelines and draws manual actions. Generate both from one source."),
  ("What is IndexNow?", "A push protocol for instant recrawl on Bing and others, which feeds Copilot. Google does not participate — use a current sitemap there."),
 ],
},

]
