"""Guide content — trading mechanics batch C. Data only; rendering lives in engine.py."""

NAV_TRADE = [("/", "Work"), ("/guides.html", "Guides"), ("/risk-tools.html", "Calculators"), ("/apps.html", "Apps")]

DISCLAIMER = ('Educational content, not financial advice. No live profit-and-loss figures are claimed '
              'anywhere on this site; backtest and walk-forward results are always labelled as such. '
              'Full terms: <a href="/terms.html">/terms.html</a>')

GUIDES = [

{
 "slug": "vcp-base-patterns",
 "title": "VCP and Base Patterns Explained, With Test Results",
 "desc": "What a base is, how contractions are counted, why volume dry-up matters, where the pivot sits, and the walk-forward result that came out breakeven.",
 "og_title": "VCP and Base Patterns Explained",
 "og_desc": "Contraction counts, volume dry-up, pivots, failure modes — and the walk-forward test that came out breakeven.",
 "headline": "VCP and Base Patterns: Structure, Pivots, and What Testing Showed",
 "crumb": "VCP and Base Patterns",
 "about": ["Volatility contraction pattern", "Chart patterns", "Swing trading"],
 "eyebrow": "Guide · Trading",
 "h1": "VCP and bases, described honestly",
 "lead": "A base is a pause in a trend where shares change hands. A volatility contraction pattern is a base whose swings get progressively smaller. The structure is real and easy to see. Whether it pays is a separate question, and my own testing says it roughly did not.",
 "nav": NAV_TRADE,
 "body": [
  ("h2", "What is a base?"),
  ("p", "A base is a sideways or corrective range that interrupts a prior advance. Mechanically it is a transfer: holders who bought lower and want out sell into buyers who are willing to pay today's price. The range persists until one side runs out of inventory or patience."),
  ("p", "Three things describe any base and you should be able to state all three before calling something a base:"),
  ("ul", ["<strong>Depth</strong> — the percentage from the high of the base to its lowest low. A 12% base and a 45% base are not the same object.",
          "<strong>Duration</strong> — how many bars or weeks the range has lasted. Short bases after a long advance are usually late-stage.",
          "<strong>Prior trend</strong> — a base only means anything after an advance. A sideways range after a nine-month decline is a downtrend resting."]),
  ("h2", "What makes it a VCP"),
  ("p", "The volatility contraction pattern, popularised by Mark Minervini, is a base in which each successive pullback is <strong>smaller than the one before it</strong>. The idea is that supply is being exhausted in measurable steps: fewer sellers appear at each pullback, so each dip gets shallower."),
  ("p", "A worked count on a hypothetical base:"),
  ("table", (["Contraction", "High", "Low", "Depth", "Reading"],
             [["T1", "100.00", "82.00", "18.0%", "First shakeout, widest"],
              ["T2", "97.00", "88.30", "9.0%", "Roughly half of T1"],
              ["T3", "96.00", "91.70", "4.5%", "Roughly half of T2"],
              ["Pivot", "96.00", "—", "—", "Break above the T3 high"]])),
  ("p", "That is a <strong>3T base</strong>: three contractions, each about half the previous depth. Two to four contractions is the usual count. More than five and you are almost certainly drawing the ones you want to see."),
  ("h2", "Volume dry-up"),
  ("p", "The volume side of the pattern matters as much as the price side. Through a genuine contraction, volume should fall away toward the right edge of the base. The shorthand is <strong>VDU</strong>, volume dry-up: the final contraction trades on notably below-average volume, often 30% to 50% under the 50-day average."),
  ("p", "The reasoning is straightforward. If the last pullback is shallow <em>and</em> almost nobody traded it, there is very little supply left at that price. A shallow pullback on heavy volume says the opposite: plenty of people are still selling, they are just being absorbed for now."),
  ("h2", "The pivot and the buy point"),
  ("p", "The pivot is the high of the final contraction. The mechanical entry is a break above it, ideally on volume expanding well above average, because a breakout without volume is a price move without participation."),
  ("formula", "Entry  = pivot + small buffer\nStop   = below the low of the final contraction\n1R     = entry − stop\nSize   = (account × risk %) ÷ 1R"),
  ("p", 'Note the ordering. The structure defines the stop, the stop defines 1R, and 1R defines the size. Tight final contractions are attractive precisely because they make 1R small, which lets you take a normal-sized position without oversizing risk. The arithmetic is in the <a href="/guides/r-multiple-expectancy.html">R-multiple guide</a>.'),
  ("h2", "Failure modes"),
  ("ul", ["<strong>Undercut and rally</strong> — price breaks the final low, stops out the obvious holders, then reverses back up. Painful and common.",
          "<strong>Breakout on no volume</strong> — the pivot clears on below-average volume, drifts a few percent, and rolls back into the base.",
          "<strong>Late-stage base</strong> — a third or fourth base after a long advance fails far more often than the first one out of a correction.",
          "<strong>Wide, loose contractions</strong> — if T2 is not meaningfully tighter than T1, the pattern is a range, not a contraction.",
          "<strong>Drawn to fit</strong> — the biggest failure mode is the analyst. Contractions are easy to find retrospectively on any chart that later went up."]),
  ("h2", "What my own testing said"),
  ("p", "This is the part most write-ups omit. I built a screener and a no-lookahead backtest engine, then ran my swing setups through walk-forward testing rather than an in-sample fit. <strong>The VCP-style contraction setup came out roughly breakeven.</strong> Not a disaster, not an edge — after costs there was nothing there worth sizing."),
  ("table", (["Setup", "Walk-forward result", "Verdict"],
             [["AVWAP reclaim", "+0.117R over 4,933 trades (95% CI +0.057 to +0.174)", "Kept — the only survivor. An earlier +0.23R on 101 trades did not survive my own re-test"],
              ["VCP-style contraction", "roughly breakeven", "Not traded mechanically"],
              ["Gap / opening-range-breakout proxy", "−0.28R", "Dropped"]])),
  ("warn", "Breakeven does not mean the pattern is fake. It means my mechanical encoding of it, on my universe, over my test window, did not produce an edge. Discretionary traders who read context, liquidity, and market environment may do better. But if you cannot express a setup mechanically, you also cannot prove it works, and the honest position is to say so."),
  ("p", 'Two filters I expected to rescue it — a market-regime filter and a normalised-momentum-lag filter — were tested on the same data and <strong>cut expectancy</strong>, so both were rejected. <a href="/guides/walk-forward-backtest.html">How the testing was run →</a>'),
  ("h2", "How to use bases anyway"),
  ("ol", ["Use the structure for <em>risk definition</em>, which it is genuinely good at. The final contraction gives you a tight, non-arbitrary stop.",
          "Do not use the structure as a standalone edge claim until you have tested your version of it on your universe.",
          "Tag every base trade in your journal with the contraction count and whether VDU was present, then compute expectancy per tag after 30-plus trades.",
          "Treat late-stage bases as a smaller size category, not a normal one.",
          "Keep the negative results. A pattern that tests breakeven is information, and it stops you paying for it twice."]),
  ("callout", DISCLAIMER),
 ],
 "tools": [("/swing-screener.html", "Swing Screener", "the screener and no-lookahead backtest engine behind the walk-forward results."),
           ("/apps/tradelog/", "TradeLog", "tag base trades by contraction count and get expectancy per tag, offline and local."),
           ("/guides/walk-forward-backtest.html", "Walk-forward testing guide", "why in-sample pattern studies flatter every chart pattern.")],
 "faqs": [
  ("What is a VCP in trading?", "A volatility contraction pattern is a consolidation in which each successive pullback is shallower than the one before it, typically two to four contractions with each roughly half the depth of the previous. The idea is that supply is being exhausted in measurable steps, so fewer sellers appear at each dip."),
  ("How do you count contractions in a base?", "Measure each pullback from its local high to its local low as a percentage. A base going 18%, then 9%, then 4.5% is a three-contraction base, usually written 3T. Two to four contractions is normal; if you are counting six, you are almost certainly drawing what you want to see."),
  ("What is volume dry-up?", "Volume dry-up is the drop in traded volume toward the right edge of a base, often 30% to 50% below the 50-day average during the final contraction. A shallow pullback on very light volume suggests little supply remains, whereas a shallow pullback on heavy volume means sellers are still active and merely being absorbed."),
  ("Where is the buy point in a VCP?", "The pivot is the high of the final contraction, and the mechanical entry is a break above it on volume expanding above average. The stop belongs below the low of that final contraction, which makes the structure define the risk and therefore the position size."),
  ("Does the VCP pattern actually work?", "In my own walk-forward testing a VCP-style contraction setup came out roughly breakeven, meaning no edge worth sizing after costs. The anchored-VWAP reclaim was the only setup that survived, at +0.117R over 4,933 trades on a 129-symbol, 10-year universe (an earlier +0.23R over 101 trades did not survive my own re-test), and a gap/opening-range-breakout proxy came out at -0.28R and was dropped. These are backtest results, not live trading claims."),
  ("Why do base breakouts fail?", "The common failures are an undercut of the final low that stops out obvious holders before reversing, a breakout on below-average volume that rolls back into the base, and late-stage bases forming after an extended advance. The largest failure mode is retrospective drawing, since contractions are easy to find on any chart that already went up."),
 ],
 "faq_cards": [
  ("What is a VCP?", "A base where each pullback is shallower than the last, usually two to four contractions with each about half the previous depth."),
  ("How do you count contractions?", "Measure each high-to-low pullback as a percentage. 18%, then 9%, then 4.5% is a 3T base. Counting six means you are drawing what you want."),
  ("What is volume dry-up?", "Volume falling 30-50% under the 50-day average in the final contraction. Shallow dip plus light volume means little supply left."),
  ("Where is the buy point?", "The high of the final contraction, taken on expanding volume. The stop goes under that contraction's low, and that defines your size."),
  ("Does VCP work?", "In my walk-forward test it came out roughly breakeven — no edge worth sizing. Only the AVWAP reclaim survived, at +0.117R over 4,933 trades."),
  ("Why do breakouts fail?", "Undercut-and-rally, breakouts on thin volume, and late-stage bases. Plus the analyst drawing contractions onto charts that already worked."),
 ],
},

{
 "slug": "stop-loss-placement",
 "title": "Stop Loss Placement — Structure, ATR, and Position Size",
 "desc": "Structure-based, ATR-based, or percentage stops. Why the stop sets position size rather than the other way round, and the places never to put one.",
 "og_title": "Stop Loss Placement, Done Properly",
 "og_desc": "Structure vs ATR vs percentage stops, why the stop determines size, and the places never to put one.",
 "headline": "Stop Loss Placement: Structure, Volatility, and Sizing",
 "crumb": "Stop Loss Placement",
 "about": ["Stop loss", "Position sizing", "Risk management"],
 "eyebrow": "Guide · Risk",
 "h1": "Where the stop goes, and what it decides",
 "lead": "A stop loss is not a safety net bolted on after you buy. It is the first number in the trade, because it defines 1R, and 1R defines how many shares you are allowed to own.",
 "nav": NAV_TRADE,
 "body": [
  ("h2", "The stop comes first"),
  ("p", "Most people size a position by deciding how much they want to own, then place a stop wherever it feels comfortable. That is backwards, and it is why position sizes drift with mood rather than with risk."),
  ("p", "The correct order is fixed:"),
  ("ol", ["Find the price at which the trade idea is <strong>wrong</strong>. That is the stop.",
          "Distance from entry to stop is <strong>1R</strong>, expressed per share.",
          "Decide the account risk for this trade — commonly 0.5% to 1%.",
          "Divide. That gives share count. You do not get to choose it."]),
  ("formula", "1R per share = entry − stop\nRisk budget  = account × risk %\nShares       = risk budget ÷ 1R per share"),
  ("p", "Worked: a $30,000 account risking 1% is a $300 budget. Entry $48.00 with a structural stop at $45.60 gives 1R of $2.40 per share, so 125 shares, a $6,000 position. Move that stop to $47.40 and 1R is $0.60, so the same $300 budget buys 500 shares and a $24,000 position. <strong>Same risk, four times the exposure, purely because the structure was tighter.</strong>"),
  ("warn", "This is also the trap. A tight stop lets you carry a large position, and a large position on a stop that was tight for cosmetic rather than structural reasons is how a normal loss becomes several. Tighten the stop only when the chart genuinely offers a tighter invalidation, never to justify more shares."),
  ("h2", "Structure-based stops"),
  ("p", "Place the stop just beyond the price level that would prove the idea wrong: below the low of the base, below the anchored VWAP that generated the signal, below the consolidation floor, beyond the pattern's defining swing."),
  ("p", "The advantage is that the exit means something. When a structural stop fills, the reason you entered has been invalidated, so the exit carries information rather than just recording a bad hour. <strong>Signal and invalidation should be defined by the same object</strong> wherever possible."),
  ("h2", "Volatility-based stops (ATR)"),
  ("p", "Average true range measures how far an instrument typically moves in a period, including gaps. An ATR stop scales the distance to the instrument's own noise level instead of to a fixed percentage."),
  ("formula", "Stop = entry − (k × ATR14)\n\ncommon k values: 1.5 to 3.0 for swing timeframes"),
  ("p", "Worked: entry $48.00, ATR14 of $1.20, k of 2 gives a stop at $45.60 and 1R of $2.40. If that stock's ATR later rises to $2.00, the same k puts the stop at $44.00 and the same risk budget buys fewer shares automatically. That auto-adjustment is the point: <strong>the position shrinks as the instrument gets noisier</strong>, without you having to remember to shrink it."),
  ("h2", "Percentage stops"),
  ("p", "A flat 7% or 8% stop is the simplest rule and the weakest one, because it ignores both structure and volatility. A 7% stop on a low-volatility utility is enormous; on a leveraged ETF or a small-cap biotech it is inside a normal Tuesday. It has exactly one virtue: it is impossible to rationalise away, which for a beginner is worth something."),
  ("table", (["Method", "Adapts to volatility", "Carries information", "Best used for"],
             [["Structure", "Indirectly", "Yes — invalidates the thesis", "Pattern and level-based swing trades"],
              ["ATR multiple", "Yes, directly", "Partly", "Systematic entries, mixed-volatility universes"],
              ["Fixed percentage", "No", "No", "Beginners, or as an outer cap on the other two"]])),
  ("p", "In practice the useful combination is structure first, with an ATR check: if the structural stop is under 1 ATR away, it is inside noise and will be hit at random. Widen it to at least 1 ATR and take fewer shares, or skip the trade."),
  ("h2", "Where not to put a stop"),
  ("ul", ["<strong>On a round number.</strong> $50.00, $100.00, and $250.00 attract resting orders from everyone else. Sit a little beyond, not exactly on it.",
          "<strong>Exactly at the obvious swing low.</strong> Every chart reader sees the same low. Price routinely trades a few cents through it and reverses. A small buffer beyond the obvious level costs a little R and avoids a lot of undercut-and-rally.",
          "<strong>Inside the noise.</strong> Anything under roughly 1 ATR of the entry will be hit by random movement regardless of whether the idea was right.",
          "<strong>At a dollar figure you can tolerate losing.</strong> The market does not know your comfort level. If the structural stop is bigger than your tolerance, cut share count, not the stop.",
          "<strong>Nowhere.</strong> A mental stop is a stop you will renegotiate at the worst possible moment."]),
  ("h2", "Never move a stop down"),
  ("p", "Moving a stop further away converts a defined 1R loss into an undefined one, and it always happens under pressure, which is exactly when judgement is worst. It is the single most destructive habit available to a retail trader, because one widened stop can erase the gains from a dozen disciplined trades."),
  ("p", "Moving a stop <em>up</em> in a long, to breakeven or behind a trailing structure, is a different action entirely and is fine, provided the rule was written before the trade. The asymmetry is deliberate: risk may only be reduced, never increased, after entry."),
  ("p", 'Log a <strong>moved stop</strong> mistake tag every single time it happens. After 50 trades that tag usually explains most of the losses beyond −1R, and that is a rule change rather than a feeling. <a href="/guides/trading-journal.html">Journal fields that surface it →</a>'),
  ("callout", DISCLAIMER),
 ],
 "tools": [("/risk-tools.html", "Trader's risk toolkit", "position sizer that turns entry, stop, and account risk into a share count."),
           ("/apps/tradelog/", "TradeLog", "logs planned 1R and flags moved-stop trades so the pattern is countable."),
           ("/guides/r-multiple-expectancy.html", "R-multiple &amp; expectancy guide", "why every result should be measured in R rather than dollars.")],
 "faqs": [
  ("Where should you place a stop loss?", "Place it just beyond the price that would prove the trade idea wrong, which is usually a structural level such as the low of a base, a consolidation floor, or the anchored VWAP that generated the signal. Then check that this distance is at least about one average true range, because anything tighter sits inside normal noise and will be hit at random."),
  ("Does the stop determine position size, or the other way round?", "The stop determines position size. Find the invalidation price first, treat the entry-to-stop distance as 1R per share, then divide your account risk budget by that distance to get the share count. A $30,000 account risking 1% has a $300 budget, so a $2.40 stop distance allows 125 shares."),
  ("What is an ATR-based stop?", "An ATR stop sets the distance as a multiple of average true range, commonly 1.5 to 3 times ATR14 for swing timeframes. Because ATR measures the instrument's own typical movement including gaps, the stop widens automatically in volatile names and the resulting position size shrinks to match."),
  ("Are percentage stops any good?", "A fixed 7% or 8% stop ignores both structure and volatility, so it is far too wide for a low-volatility stock and far too tight for a leveraged ETF or a small-cap. Its only real virtue is that it cannot be rationalised away, which makes it a reasonable outer cap or a beginner's starting rule."),
  ("Where should you never put a stop?", "Avoid exact round numbers such as $50.00 or $100.00, and avoid sitting exactly at the obvious swing low that every chart reader can see, because price frequently trades a few cents through those levels and reverses. Also avoid any distance inside roughly one ATR, and avoid setting the stop at a dollar amount you find comfortable rather than at a level the chart justifies."),
  ("Should you ever move a stop loss?", "Move it in the direction of reduced risk only. Trailing a stop up in a long position, or to breakeven, is fine when the rule was defined before entry. Widening a stop converts a known 1R loss into an unknown one and always happens under pressure, which is why it is the most damaging habit in retail trading."),
 ],
 "faq_cards": [
  ("Where does the stop go?", "Just beyond the level that proves the idea wrong, and at least about 1 ATR away so noise alone cannot hit it."),
  ("Stop first or size first?", "Stop first, always. Entry minus stop is 1R per share; risk budget divided by 1R gives the share count. You do not choose the size."),
  ("What is an ATR stop?", "Distance set as 1.5-3x ATR14, so it scales to the instrument's own noise. Volatile names get wider stops and automatically smaller positions."),
  ("Are percentage stops fine?", "Weakest option — they ignore structure and volatility. Useful only as a beginner rule or an outer cap on a structural stop."),
  ("Where not to put one?", "Not on round numbers, not exactly at the obvious swing low, not inside 1 ATR, and never at a dollar figure that merely feels tolerable."),
  ("Can you move a stop?", "Only tighter. Trailing up is fine if the rule pre-existed. Widening turns a defined 1R loss into an undefined one, under pressure."),
 ],
},

{
 "slug": "volume-profile",
 "title": "Volume Profile Explained — POC, Value Area, Nodes",
 "desc": "How volume profile differs from a volume-by-time histogram, what POC and the value area mean, how to read volume nodes, and how it pairs with anchored VWAP.",
 "og_title": "Volume Profile Explained",
 "og_desc": "POC, value area, high and low volume nodes, and why price-based volume beats time-based volume.",
 "headline": "Volume Profile: POC, Value Area, and Volume Nodes",
 "crumb": "Volume Profile",
 "about": ["Volume profile", "Market profile", "Technical analysis"],
 "eyebrow": "Guide · Trading",
 "h1": "Volume profile, and what the histogram at the bottom cannot tell you",
 "lead": "The volume bars under a chart tell you when trading happened. A volume profile tells you where. Those are different questions, and only the second one identifies the prices people actually care about.",
 "nav": NAV_TRADE,
 "body": [
  ("h2", "Volume by time versus volume by price"),
  ("p", "The standard histogram buckets volume by <em>time</em>: one bar per session or per five-minute interval, showing how much traded in that window. It answers \"was today busy?\""),
  ("p", "A volume profile rotates that ninety degrees and buckets volume by <em>price</em>: horizontal bars showing how much total volume traded at each price level over a chosen range. It answers \"which prices did the market spend its money at?\" That is the more useful question, because acceptance and rejection happen at prices, not at clock times."),
  ("table", (["", "Volume by time", "Volume profile"],
             [["Axis", "Horizontal, one bar per period", "Vertical, one bar per price bucket"],
              ["Answers", "When was activity heavy?", "Which prices absorbed the most volume?"],
              ["Typical use", "Confirming a breakout day", "Locating support, resistance, and fair value"],
              ["Weakness", "Says nothing about level", "Says nothing about sequence or time"]])),
  ("h2", "POC, VAH, VAL"),
  ("ul", ["<strong>POC — point of control.</strong> The single price with the most traded volume in the range. It is the market's most agreed-on price for that period, and it tends to act as a magnet: price that leaves it often returns to test it.",
          "<strong>Value area.</strong> The contiguous band of prices containing roughly 70% of the range's volume, centred on the POC. The 70% figure comes from the one-standard-deviation convention inherited from market profile.",
          "<strong>VAH / VAL.</strong> Value area high and value area low, the two edges of that band. They are the practical boundaries between \"prices most participants accepted\" and \"prices they rejected\"."]),
  ("p", "The workaday reading: inside the value area, the market is balanced and mean-reverting, so fading the edges is the higher-probability behaviour. Outside it, the market is imbalanced and trending, so accepting the move is the higher-probability behaviour. <strong>The value area edges are where those two regimes swap</strong>, which is why VAH and VAL are worth marking even if you use nothing else from the tool."),
  ("h2", "High and low volume nodes"),
  ("p", "Beyond the POC, the shape of the profile matters."),
  ("table", (["Feature", "What it means", "How price behaves"],
             [["High volume node (HVN)", "A price where a lot of volume traded — heavy agreement and inventory", "Price slows, chops, and often stalls. Good place for a target, bad place for a breakout entry."],
              ["Low volume node (LVN)", "A price the market moved through quickly with little trade", "Price tends to travel across it fast. Good place for a stop to sit beyond, and a natural edge for a range."],
              ["Single print / gap in profile", "Almost no volume at that price at all", "Rejection zone. Revisits are often sharp and one-directional."]])),
  ("p", "A concrete use: if your entry sits just above an LVN and your target sits at the next HVN, you have a structural reason to expect fast travel to the target and a natural place to put the stop, on the far side of the low-volume gap where returning would contradict the thesis."),
  ("h2", "Choosing the range"),
  ("p", "A profile is only as meaningful as the range you compute it over. The common choices:"),
  ("ol", ["<strong>Session profile</strong> — one day. Intraday work, opening-range context.",
          "<strong>Composite over a base or consolidation</strong> — the most useful swing application, because it shows where inside the range the inventory actually sits.",
          "<strong>Since an event</strong> — anchored to an earnings gap or a major low, so the profile only contains participants from the current regime.",
          "<strong>Visible range</strong> — whatever is on screen. Convenient, and quietly the least rigorous, because the profile changes every time you scroll."]),
  ("p", "Same discipline as anchoring anything: <strong>pick the range for a stated reason before you look at the outcome.</strong> A profile computed over a range chosen because it produced a nice-looking POC is a drawing, not an analysis."),
  ("h2", "Pairing it with anchored VWAP"),
  ("p", "The two tools answer neighbouring questions and are strongest together. A profile tells you where volume sits but not who is up or down on it. Anchored VWAP tells you the average cost basis of everyone since a chosen event, so it tells you whether that cohort is in profit."),
  ("p", "Concretely: anchor a VWAP to the same event you anchor the profile to. If the AVWAP and the POC sit at nearly the same price, that level is both the most-traded price and the average cost basis, which makes it a strong reference for both entry and invalidation. If the AVWAP sits well above the POC, the average participant paid more than the most agreed-on price, which is overhead supply waiting to sell into strength."),
  ("p", 'An AVWAP reclaim occurring at a low volume node is a more interesting setup than one occurring in the middle of a high volume node, because there is less inventory to chew through above it. <a href="/guides/anchored-vwap.html">The anchored VWAP guide covers the reclaim mechanics →</a>, including the walk-forward result that made it the one setup I kept — +0.117R over 4,933 trades after my own re-test invalidated the +0.23R over 101 trades I first reported.'),
  ("h2", "Limits"),
  ("ul", ["Profiles are descriptive, not predictive. They show where trade happened, not where it will happen.",
          "They say nothing about sequence. A POC built early in a range and one built yesterday look identical on the profile and mean different things.",
          "Free retail data is often consolidated and incomplete, so the profile shape is approximate.",
          "Every level is negotiable in a strong trend. Value areas are reference points, not walls."]),
  ("callout", DISCLAIMER),
 ],
 "tools": [("/guides/anchored-vwap.html", "Anchored VWAP guide", "the cost-basis tool that pairs directly with a profile's POC."),
           ("/swing-screener.html", "Swing Screener", "the screener and no-lookahead backtest engine used for the walk-forward results."),
           ("/apps/tradelog/", "TradeLog", "tag trades by where they sat in the profile and compare expectancy per tag.")],
 "faqs": [
  ("What is a volume profile?", "A volume profile buckets traded volume by price rather than by time, drawing horizontal bars that show how much volume changed hands at each price level over a chosen range. It answers which prices the market spent its money at, which is a different and generally more useful question than the standard histogram's answer of when volume was heavy."),
  ("What is the point of control (POC)?", "The point of control is the single price with the highest traded volume in the profile's range, representing the market's most agreed-on price for that period. It tends to act as a magnet, so price that moves away from it frequently returns to test it."),
  ("What is the value area?", "The value area is the contiguous band of prices containing roughly 70% of the range's volume, centred on the point of control, with its edges labelled value area high (VAH) and value area low (VAL). Inside it the market is balanced and mean-reverting; outside it the market is imbalanced and trending."),
  ("What are high and low volume nodes?", "A high volume node is a price where heavy volume traded, so price tends to slow and chop there, making it a better target than an entry. A low volume node is a price the market passed through quickly with little trade, so price tends to travel across it fast, which makes the far side of it a sensible place for a stop."),
  ("How is volume profile different from the volume histogram?", "The standard histogram plots volume against time, one bar per period, so it tells you whether a session was busy. A volume profile plots volume against price, so it tells you which price levels absorbed the volume. The first is about activity, the second is about location."),
  ("How does volume profile work with anchored VWAP?", "Anchor both to the same event. The profile shows where volume traded and the anchored VWAP shows the average cost basis of everyone who traded since the anchor. When the two sit at the same price the level is unusually strong; when the VWAP sits above the POC, the average participant is underwater and overhead supply is likely."),
 ],
 "faq_cards": [
  ("What is a volume profile?", "Volume bucketed by price instead of by time. Horizontal bars showing which price levels actually absorbed the trading."),
  ("What is the POC?", "The single most-traded price in the range. It acts as a magnet, and price that leaves it tends to come back and test it."),
  ("What is the value area?", "The band holding about 70% of the range's volume, edged by VAH and VAL. Balanced inside, trending outside."),
  ("HVN vs LVN?", "High volume nodes are heavy-inventory prices where price stalls, so they make good targets. Low volume nodes get crossed fast, so stops sit beyond them."),
  ("How is it different from the volume histogram?", "The histogram is volume by time and tells you if a day was busy. The profile is volume by price and tells you which levels mattered."),
  ("Does it pair with anchored VWAP?", "Yes, anchored to the same event. POC and AVWAP at the same price is a strong level; AVWAP above POC means overhead supply."),
 ],
},

{
 "slug": "leveraged-etf-decay",
 "title": "Why Leveraged ETFs Decay — Volatility Drag Explained",
 "desc": "Daily rebalancing, volatility drag, and a worked two-day example where a 3x ETF loses on a flat round trip. When they fit, and why sizing must be tighter.",
 "og_title": "Why Leveraged ETFs Decay",
 "og_desc": "Daily rebalancing and volatility drag, with the arithmetic showing a 3x fund losing on a flat round trip.",
 "headline": "Why Leveraged ETFs Decay: Daily Rebalancing and Volatility Drag",
 "crumb": "Leveraged ETF Decay",
 "about": ["Leveraged ETFs", "Volatility drag", "Risk management"],
 "eyebrow": "Guide · Instruments",
 "h1": "Leveraged ETFs, and the arithmetic nobody reads",
 "lead": "A 3x fund promises three times the daily move. It delivers exactly that, every day, and the compounding of those daily moves is why holding one through a choppy flat market loses money while the index goes nowhere.",
 "nav": NAV_TRADE,
 "body": [
  ("h2", "The prospectus already told you"),
  ("p", "A leveraged ETF targets a multiple of the underlying index's return over <strong>one trading day</strong>. That is the entire mandate. Nothing in the product promises 3x over a week, a month, or a year, and the funds say so plainly in their own documents."),
  ("p", "To hold that daily multiple, the fund rebalances its exposure at the end of every session. If the index rises, the fund must add exposure to keep the ratio; if the index falls, it must cut exposure. The mechanical consequence is that <strong>the fund buys after up days and sells after down days</strong>, which is exactly the wrong behaviour in a market that oscillates."),
  ("h2", "The worked two-day example"),
  ("p", "Take an index at 100 and a 3x fund at 100. Day one the index rises 10%; day two it falls 9.0909%, which returns it exactly to 100."),
  ("table", (["", "Index", "Index level", "3x daily move", "3x fund value"],
             [["Start", "—", "100.00", "—", "100.00"],
              ["Day 1", "+10.00%", "110.00", "+30.00%", "130.00"],
              ["Day 2", "−9.0909%", "100.00", "−27.2727%", "94.55"],
              ["Net", "0.00%", "100.00", "—", "−5.45%"]])),
  ("formula", "Day 2 fund value = 130.00 × (1 − 0.272727) = 130.00 × 0.727273 = 94.55\n\nIndex round trip:  0.00%\n3x fund round trip: −5.45%"),
  ("p", "The index finished exactly flat. The 3x fund lost 5.45%. Nobody made a bad decision and no fee caused it. The loss is pure arithmetic: a −27.27% day requires a +37.5% day to recover, and the fund never got one."),
  ("h2", "Volatility drag, generalised"),
  ("p", "The same effect exists in any leveraged compounding sequence, and it scales roughly with the square of the leverage factor and with variance:"),
  ("formula", "drag ≈ ½ × L × (L − 1) × σ²\n\nwhere L is the leverage multiple\n      σ² is the variance of daily returns"),
  ("p", "The two things to take from that expression: drag rises with the <em>square</em> of volatility, so a choppy market is disproportionately punishing, and it rises faster than linearly with L, so a 3x fund suffers roughly three times the drag of a 2x fund on the same underlying, not one and a half times."),
  ("p", "A second worked case makes the asymmetry clear. Run the same round trip with a 1% daily swing instead of a 10% one: index up 1% then down 0.9901% returns to 100, while the 3x fund goes to 103.00 then down 2.9703% to 99.94, a loss of only 0.06%. <strong>Same structure, a hundred times smaller bill, because volatility is what you are paying.</strong>"),
  ("h2", "The trending exception"),
  ("p", "Compounding is not only a tax. In a smoothly trending market with low daily volatility, compounding works in your favour and a 3x fund can beat 3x the underlying's period return. Five consecutive 2% up days give an index +10.4% while a 3x fund returns +33.8%, which is more than three times the index's period gain."),
  ("p", "This is the honest version of the trade-off. <strong>Leveraged ETFs are instruments for short, directional, low-chop periods.</strong> They are not broken products; they are products whose behaviour depends on the path, not just the endpoint."),
  ("h2", "When they fit and when they do not"),
  ("table", (["Situation", "Verdict", "Why"],
             [["Multi-day trend trade with a defined stop", "Reasonable", "Path is short and the daily rebalancing has little time to compound against you"],
              ["Hedging an existing position for a few days", "Reasonable", "Capital-efficient; a small position covers a large exposure"],
              ["Buy and hold for months", "No", "Volatility drag compounds indefinitely and the underlying can round-trip while you lose"],
              ["Choppy, range-bound market", "No", "This is the exact condition the drag formula punishes hardest"],
              ["Retirement or core account holdings", "No", "Nothing about a daily-reset product suits a multi-year horizon"]])),
  ("h2", "Sizing must be tighter, not the same"),
  ("p", "The naive mistake is to size a 3x position the same way you size a normal one and treat the extra leverage as extra upside. Run the risk arithmetic instead."),
  ("p", "A $30,000 account risking 1% has a $300 budget. On a normal stock with a $2.40 stop distance that is 125 shares. On a 3x ETF, the same percentage stop distance in the underlying becomes three times as large in the fund, so the equivalent stop distance is roughly $7.20 and the same $300 budget buys about 42 shares. <strong>The position must shrink by roughly the leverage factor for the risk to stay identical.</strong>"),
  ("p", "My own execution rules encode this as a hard <strong>half-cap on leveraged ETF positions</strong>: whatever normal sizing produces, a leveraged instrument gets half of it. That is a deliberately blunt rule, and blunt rules survive contact with a bad week better than clever ones do."),
  ("ul", ["Compute the stop from the fund's own ATR, not from the underlying's chart.",
          "Treat overnight gaps as materially worse, because a gap is also multiplied by the leverage factor.",
          "Set a maximum holding period in days and honour it, because drag is a function of time in the instrument.",
          "Never hold two correlated leveraged positions and count them as separate risk. They are one position with a bigger number."]),
  ("p", 'Position sizing arithmetic, break-even win rates, and risk of ruin are all in the <a href="/risk-tools.html">free risk toolkit</a>.'),
  ("callout", DISCLAIMER),
 ],
 "tools": [("/risk-tools.html", "Trader's risk toolkit", "position sizer and risk-of-ruin simulation for tighter leveraged sizing."),
           ("/guides/kelly-criterion.html", "Kelly criterion guide", "why estimated edges argue for smaller size, especially with leverage."),
           ("/apps/tradelog/", "TradeLog", "tag leveraged trades separately and compare their real expectancy against unleveraged ones.")],
 "faqs": [
  ("Why do leveraged ETFs lose money over time?", "Because they target a multiple of the underlying's return over a single day and rebalance nightly to maintain it, so the daily returns compound. In an oscillating market this compounding works against the holder, and the fund can lose money even when the underlying index finishes exactly flat."),
  ("Can you show an example of leveraged ETF decay?", "Start an index and a 3x fund both at 100. The index rises 10% to 110, so the fund gains 30% to 130. The index then falls 9.0909% back to exactly 100, so the fund falls 27.2727% to 94.55. The index round trip is 0% and the fund round trip is -5.45%, entirely from arithmetic rather than fees."),
  ("What is volatility drag?", "Volatility drag is the gap between a leveraged fund's compounded return and the simple multiple of the underlying's return, caused by daily rebalancing. It scales approximately as one half times L times (L minus 1) times the variance of daily returns, so it grows with the square of volatility and faster than linearly with the leverage factor."),
  ("Are leveraged ETFs ever appropriate?", "They suit short, directional holding periods in low-volatility trends and short-term hedging where capital efficiency matters. In a smooth uptrend compounding actually helps: five consecutive 2% index days give the index 10.4% while a 3x fund returns 33.8%. They are unsuitable for buy and hold, choppy ranges, and long-horizon accounts."),
  ("How should you size a leveraged ETF position?", "Shrink the position by roughly the leverage factor so that dollar risk stays constant. A $30,000 account risking 1% is a $300 budget, which buys 125 shares at a $2.40 stop distance but only about 42 shares when the equivalent stop distance triples to $7.20 in a 3x fund. A blunt half-size cap on leveraged instruments is a reasonable standing rule."),
  ("Do leveraged ETFs always underperform their multiple?", "No. Path matters more than direction. In a smoothly trending, low-volatility market compounding can push a leveraged fund past the simple multiple of the period return. It is choppy, high-variance paths that produce underperformance, which is why holding period and market conditions decide the outcome."),
 ],
 "faq_cards": [
  ("Why do leveraged ETFs decay?", "They target a daily multiple and rebalance nightly, so returns compound. Oscillating markets make that compounding work against you."),
  ("Worked example?", "Index 100 to 110 to 100 is flat. A 3x fund goes 100 to 130 to 94.55 — down 5.45% on a flat round trip, from arithmetic alone."),
  ("What is volatility drag?", "Roughly ½ × L × (L−1) × variance. It grows with the square of volatility and faster than linearly with the leverage factor."),
  ("When are they appropriate?", "Short directional holds in low-chop trends, and brief hedges. Never buy-and-hold, never in a choppy range, never in a core account."),
  ("How do you size them?", "Divide by roughly the leverage factor to hold dollar risk constant. A blunt half-size cap on leveraged instruments works well."),
  ("Do they always lag the multiple?", "No. In a smooth trend compounding can beat it — five 2% up days give the index 10.4% and a 3x fund 33.8%. Path decides, not direction."),
 ],
},

{
 "slug": "paper-to-live-trading",
 "title": "Paper Trading to Real Money — Building a Promotion Gate",
 "desc": "What paper does not simulate: slippage, partial fills, borrow, emotion. Why a promotion gate matters, and the 60-trade rule my engine enforces in code.",
 "og_title": "Paper Trading to Real Money",
 "og_desc": "What paper does not simulate, and the 60-trade promotion gate my execution engine enforces in code.",
 "headline": "From Paper Trading to Real Money: What Changes and What Gates It",
 "crumb": "Paper to Live Trading",
 "about": ["Paper trading", "Trading systems", "Risk management"],
 "eyebrow": "Guide · Process",
 "h1": "The gap between paper and real money",
 "lead": "Paper trading is a useful mechanical rehearsal and a terrible predictor of results. It gets the arithmetic right and omits every friction that decides whether a small edge survives.",
 "nav": NAV_TRADE,
 "body": [
  ("h2", "What paper trading is genuinely good for"),
  ("ul", ["Proving the plumbing works — orders route, brackets attach, positions reconcile, the journal populates.",
          "Catching bugs that a backtest hides, such as duplicate orders, timezone errors, and stale quotes.",
          "Rehearsing the routine so the mechanical steps are automatic before money is involved.",
          "Sanity-checking that live signal frequency roughly matches what the backtest predicted."]),
  ("p", "That is a real list and it is worth doing. What it is not is evidence that the strategy makes money."),
  ("h2", "What paper does not simulate"),
  ("table", (["Friction", "What paper assumes", "What real money does"],
             [["Slippage", "Fills at the quoted price", "Fills a few ticks worse, much worse on gaps and thin names"],
              ["Partial fills", "The whole order fills", "Limit orders fill partially or not at all, changing the risk you actually took"],
              ["Market impact", "Your order does not exist", "Size moves the book in illiquid names, and you trade against your own footprint"],
              ["Short borrow", "Shorts are always available", "Locate may be unavailable, expensive, or recalled mid-trade"],
              ["Halts and gaps", "Orders behave normally", "A stop through a gap fills far below the stop price, so the loss exceeds 1R"],
              ["Fees and financing", "Often ignored entirely", "Commission, regulatory fees, and margin interest apply to every round trip"],
              ["Emotion", "Every signal is taken", "You skip the uncomfortable ones, which are frequently the good ones"]])),
  ("p", "The last row is the largest by a distance. A backtest and a paper account both take 100% of signals. In real money you will hesitate after two losses, size down after a drawdown, and take a discretionary exit at the worst moment. <strong>A strategy's realised expectancy is the strategy's expectancy multiplied by your compliance with it</strong>, and compliance is never 100%."),
  ("h2", "How much does friction cost?"),
  ("p", 'Run the arithmetic on the edge I actually validated. The anchored-VWAP reclaim came out at +0.117R over 4,933 trades on a 129-symbol, 10-year universe (95% CI +0.057 to +0.174) — the +0.23R over 101 trades I first reported did not survive my own adversarial re-test. Assume a 1R risk of $300 per trade, so the modelled edge is $35.10 per trade.'),
  ("formula", "modelled edge    = 0.117R × $300 = $35.10 per trade\nslippage 2 ticks × 2 sides on 100 shares ≈ $4.00\ncommission + fees                        ≈ $2.00\nnet edge                                  ≈ $63.00 per trade"),
  ("p", "That version survives. Now assume slippage of 0.05R per side rather than a few ticks, which is realistic on gappy names, and you lose 0.10R of a 0.117R edge — <strong>over 85% of the entire result, gone to execution quality alone.</strong> A small edge is not robust to sloppy fills, which is the practical reason execution discipline matters more than signal hunting."),
  ("h2", "Why a promotion gate"),
  ("p", "A promotion gate is a pre-committed, written rule that decides when a system is allowed to trade real money, evaluated by something other than your enthusiasm. Without one, the promotion decision gets made on a good week, which is precisely the wrong sample."),
  ("p", "A gate needs three properties to be worth anything:"),
  ("ol", ["<strong>Written before the paper run starts.</strong> A threshold invented afterwards is a rationalisation with a number attached.",
          "<strong>Sample-size based, not time based.</strong> \"Two months of paper\" can mean four trades. Trades are the unit that carries information.",
          "<strong>Enforced by something that is not you.</strong> A rule you can quietly waive at 9:28am is not a rule."]),
  ("h2", "The gate I actually enforce"),
  ("p", "My execution engine refuses to connect a live broker until the paper record shows <strong>60 closed paper trades with positive realised expectancy</strong>. It is a hard check in the promotion path, not a note in a document, and the current record against it is zero closed paper trades, so the live path stays shut."),
  ("p", "The two numbers are chosen for different reasons. Sixty closed trades is a compromise: it is not enough for statistical confidence, which needs a few hundred, but it is enough to expose an engine that double-fires orders, mishandles a halt, or quietly loses on fees. Requiring <em>realised</em> expectancy rather than modelled expectancy is the important half, because realised includes the fills you actually got."),
  ("warn", "An override exists in the code because a gate with no escape hatch gets bypassed by editing the source, which is worse. It is named to be uncomfortable to type, and it logs a warning when used. That is the design intent: make the unsafe path possible, obvious, and recorded, rather than impossible and therefore routed around."),
  ("h2", "Broker choice is part of the gate"),
  ("ul", ["Prefer a broker with a <strong>real paper environment on the same API</strong>, so promotion is a credential change rather than a rewrite.",
          "Avoid reverse-engineered private APIs. They violate the platform's terms, get accounts restricted, usually offer no paper mode at all, and often require storing a password and second factor locally.",
          "Verify the system <strong>fails closed</strong>: if configuration is missing or ambiguous, it should place no orders rather than default to live.",
          "Test concurrency explicitly. Twelve simultaneous signal evaluations must produce exactly one order, not twelve."]),
  ("h2", "A staged promotion, not a switch"),
  ("ol", ["Paper until the gate passes on closed trades, with the journal reconciled against broker fills.",
          "Live at minimum size — one share, or the smallest tradeable unit — for 20 trades. This tests fills, fees, and your own behaviour, not profitability.",
          "Live at quarter risk for another 30 trades, comparing realised R against paper R per setup.",
          "Full risk only after realised and paper expectancy agree within a reasonable margin.",
          "Demote automatically on a pre-defined drawdown. My engine halts at a 10% drawdown, which is a rule that only works because it is coded rather than intended."]),
  ("p", 'The measurement layer has to exist before any of this is meaningful, which means logging planned 1R, realised R, and setup tag on every trade from the first paper fill onward. <a href="/guides/trading-journal.html">Journal fields that make this work →</a>'),
  ("callout", DISCLAIMER),
 ],
 "tools": [("/trading-bot.html", "Trading bot", "the execution engine with the 60-closed-paper-trade promotion gate enforced in code."),
           ("/apps/tradelog/", "TradeLog", "logs planned and realised R per setup so paper and live can be compared directly."),
           ("/guides/walk-forward-backtest.html", "Walk-forward testing guide", "the stage before paper, and the costs a backtest leaves out.")],
 "faqs": [
  ("What does paper trading fail to simulate?", "Slippage, partial fills, market impact, short-borrow availability, halts and gap fills, commissions and financing, and above all emotion. Paper accounts and backtests take 100% of signals, while a real trader hesitates after losses and takes discretionary exits, so realised expectancy is always lower than modelled expectancy."),
  ("Is paper trading worth doing at all?", "Yes, but for engineering reasons rather than for proof of profitability. It verifies that orders route correctly, brackets attach, positions reconcile, and signal frequency matches the backtest, and it catches bugs such as duplicate orders and timezone errors that a backtest cannot expose."),
  ("What is a promotion gate in trading?", "A promotion gate is a written, pre-committed rule that decides when a strategy or system may trade real money. To be useful it must be defined before the paper run begins, measured in closed trades rather than elapsed time, and enforced by code or a third party rather than by the trader's own judgement."),
  ("How many paper trades before going live?", "My own execution engine refuses to connect a live broker until there are 60 closed paper trades showing positive realised expectancy. Sixty is not statistically conclusive, which needs several hundred trades, but it is enough to expose engines that double-fire orders, mishandle halts, or lose quietly to fees."),
  ("How much does slippage cost a small edge?", "Enough to matter. My own re-tested edge of +0.117R gives $35.10 per trade at a $300 risk unit, and a few ticks of slippage plus commission leaves roughly $29. But slippage of 0.05R per side removes 0.10R, which is over 85% of that edge, so execution quality is often larger than signal quality."),
  ("How should you scale from paper to full size?", "In stages rather than with a switch. Pass the gate on paper, then trade the minimum size for about 20 trades to test fills and behaviour, then quarter risk for another 30 trades while comparing realised R against paper R per setup, and only then full risk. Pair it with a coded drawdown halt, such as stopping at 10%."),
 ],
 "faq_cards": [
  ("What does paper miss?", "Slippage, partial fills, borrow, gap fills, fees — and emotion. Paper takes every signal; you will not."),
  ("Is paper trading useful?", "For engineering, yes: it proves orders route, brackets attach, and books reconcile. It is not evidence the strategy makes money."),
  ("What is a promotion gate?", "A pre-written rule deciding when a system may trade real money, counted in closed trades and enforced by code rather than by mood."),
  ("How many paper trades first?", "My engine requires 60 closed paper trades with positive realised expectancy before it will connect a live broker. Currently the record is zero."),
  ("Does slippage matter that much?", "Yes. Slippage of 0.05R per side removes 0.10R from a 0.117R edge — over 85% of it, lost purely to execution quality."),
  ("How do you scale up?", "Stages: pass the gate, 20 trades at minimum size, 30 at quarter risk, then full risk — with a coded drawdown halt at 10%."),
 ],
},

]
