"""Guide content — trading and AI. Data only; rendering lives in engine.py."""

NAV_TRADE = [("/", "Work"), ("/guides.html", "Guides"), ("/risk-tools.html", "Calculators"), ("/apps.html", "Apps")]
NAV_AI = [("/", "Work"), ("/guides.html", "Guides"), ("/stack.html", "Stack"), ("/store.html", "Store")]

DISCLAIMER = ('Educational content, not financial advice. No live profit-and-loss figures are claimed '
              'anywhere on this site; backtest and walk-forward results are always labelled as such. '
              'Full terms: <a href="/terms.html">/terms.html</a>')

GUIDES = [

{
 "slug": "anchored-vwap",
 "title": "Anchored VWAP Explained — How to Use It, and Its Limits",
 "desc": "What anchored VWAP is, how it differs from session VWAP, where to anchor, what a reclaim means, and the walk-forward result behind it.",
 "og_title": "Anchored VWAP Explained",
 "og_desc": "Where to anchor, what a reclaim means, and the only setup that survived my own walk-forward test.",
 "headline": "Anchored VWAP Explained: Anchors, Reclaims, and What the Data Said",
 "crumb": "Anchored VWAP",
 "about": ["Anchored VWAP", "Technical analysis", "Swing trading"],
 "eyebrow": "Guide · Trading",
 "h1": "Anchored VWAP, and the one setup that survived testing",
 "lead": "VWAP is just an average price weighted by volume. Anchoring it to an event instead of the session open turns it into something more useful: a running record of what everyone who traded since that event has paid.",
 "nav": NAV_TRADE,
 "body": [
  ("h2", "What is anchored VWAP?"),
  ("p", "VWAP — volume-weighted average price — is the average price paid per share over a period, weighting each price by the volume traded there. Standard VWAP resets every session. <strong>Anchored VWAP (AVWAP) starts from a bar you choose</strong> and keeps running from there."),
  ("formula", "VWAP = Σ(price × volume) ÷ Σ(volume), summed from the anchor bar to now"),
  ("p", "That choice is the whole idea. Anchor to an earnings gap and the line tracks the average cost basis of everyone who has traded since that earnings report. When price sits above it, that cohort is collectively in profit; below it, collectively underwater. The technique was popularised by Brian Shannon, whose framing is that price and volume tell you what participants actually did, not what they said."),
  ("h2", "Where do you anchor?"),
  ("p", "An anchor is only meaningful if the event changed who owns the stock. Useful anchors:"),
  ("ul", ["The earnings gap — the most common one, because it resets the story",
          "A 52-week high or low, where a lot of positioning changed hands",
          "The first bar of a major news event, index inclusion, or guidance change",
          "The start of a base or consolidation, to see whether the base is being absorbed or distributed",
          "The exact bar of a prior failed breakout, to measure whether trapped buyers are back to breakeven"]),
  ("p", "Anchoring to a random Tuesday produces a line that looks meaningful and means nothing. If you cannot say in one sentence why that bar mattered, it is not an anchor."),
  ("h2", "What is an AVWAP reclaim?"),
  ("p", "A reclaim is price crossing back above an anchored VWAP it had been trading under, and then holding. The reading is simple: the average buyer since that event has gone from losing to breaking even. Supply that was overhead — people waiting to get out flat — is either gone or has stopped pressing."),
  ("p", "The mechanical version I test looks for three things: price closes back above the AVWAP from a defined anchor, the reclaim holds for a confirming bar rather than wicking through, and the stop goes just below the AVWAP so the invalidation is the same line that generated the signal. That last part matters — <strong>the setup and the risk are defined by the same object</strong>, which is what makes it sizeable."),
  ("h2", "Does it actually work?"),
  ("p", "Some of it does. I built a screener and a no-lookahead backtest engine, then ran my own swing setups through walk-forward testing rather than a curve-fit in-sample check. Most of them did not survive."),
  ("table", (["Setup", "Walk-forward result", "Verdict"],
             [["AVWAP reclaim", "+0.117R over 4,933 trades (95% CI +0.057 to +0.174)", "Kept — the only survivor. An earlier +0.23R on 101 trades did not survive my own re-test"],
              ["VCP-style contraction", "≈ breakeven", "Neutral, not traded mechanically"],
              ["Gap / opening-range-breakout proxy", "−0.28R", "Dropped"]])),
  ("p", "+0.117R per trade is not a windfall. It is a marginal edge that only shows up over thousands of trades and gets erased by sloppy execution or oversized positions — and against a risk-matched random entry, only about +0.030R of it is attributable to the AVWAP trigger at all, with a confidence interval that crosses zero. My first version of this number was +0.23R over 101 trades; it did not survive my own adversarial re-test. I published that alongside it, because a strategy write-up without the failures is marketing."),
  ("p", 'Two filters I expected to help — a market-regime filter and a normalised-momentum-lag filter — were tested on the same data and <strong>cut expectancy</strong>, so both were rejected. <a href="/swing-screener.html">The full write-up is here →</a>'),
  ("h2", "How to use it without fooling yourself"),
  ("ol", ["Pick the anchor before you look at the outcome. Anchoring after the fact is how every chart becomes a winning chart.",
          "Use one anchor per thesis. Five AVWAPs on one chart means one of them will always look right.",
          "Define the stop as part of the signal, not after entry.",
          "Log every trade in R and judge the setup over 100 trades, not five.",
          "Assume your edge is smaller than the backtest says, because costs, slippage, and your own hesitation are not in the backtest."]),
  ("callout", DISCLAIMER),
 ],
 "tools": [("/swing-screener.html", "Swing Screener", "the screener and no-lookahead backtest engine behind these results."),
           ("/apps/tradelog/", "TradeLog", "an R-multiple journal that computes expectancy per setup, offline and local."),
           ("/guides/r-multiple-expectancy.html", "R-multiple &amp; expectancy guide", "the math for sizing and judging any of this.")],
 "faqs": [
  ("What is anchored VWAP?", "Anchored VWAP is a volume-weighted average price calculated from a specific bar you choose rather than from the session open. It represents the average price paid by everyone who has traded since that anchor event, so price above the line means that cohort is collectively in profit and below means it is underwater."),
  ("How is anchored VWAP different from regular VWAP?", "Regular VWAP resets at the start of each session and is mostly used intraday. Anchored VWAP starts at an event you select — an earnings gap, a 52-week high, the start of a base — and keeps running for as long as that event stays relevant, which makes it usable on swing and position timeframes."),
  ("Where should you anchor a VWAP?", "Anchor to bars where ownership genuinely changed: earnings gaps, 52-week highs or lows, major news, index inclusion, the start of a consolidation, or a prior failed breakout. If you cannot state in one sentence why that bar mattered, it is not a valid anchor."),
  ("What does an AVWAP reclaim mean?", "A reclaim is price crossing back above an anchored VWAP it had been trading below, and holding there. It signals that the average buyer since the anchor event has moved from a loss to breakeven, which removes overhead supply from traders who were waiting to exit flat."),
  ("Does the AVWAP reclaim setup actually work?", "In my own walk-forward testing it was the only setup that survived, but the headline shrank under re-testing. An early +0.23R over 101 trades on 8 names was not reproducible; on a 129-symbol, 10-year universe it is +0.117R over 4,933 trades (95% CI +0.057 to +0.174), and a risk-matched random entry already captures +0.086R of that. A VCP-style contraction came out roughly breakeven and a gap/opening-range-breakout proxy came out at -0.28R and was dropped. That is a marginal edge at best, and it is educational information rather than advice."),
  ("Who popularised anchored VWAP?", "Brian Shannon is the practitioner most associated with popularising anchored VWAP for swing and position trading, framing it around what participants actually paid rather than around indicator signals."),
 ],
 "faq_cards": [
  ("What is anchored VWAP?", "A volume-weighted average price running from a bar you choose, not from the session open. It tracks the average cost basis of everyone who traded since that event."),
  ("How is it different from session VWAP?", "Session VWAP resets daily and is an intraday tool. Anchored VWAP persists from its anchor, so it works on swing and position timeframes."),
  ("Where do you anchor it?", "Bars where ownership changed: earnings gaps, 52-week highs or lows, major news, the start of a base, or a prior failed breakout."),
  ("What is a reclaim?", "Price crossing back above an AVWAP it was under, and holding. The average buyer since the anchor is back to breakeven, so overhead supply thins out."),
  ("Does it work?", "It was the only setup that survived my walk-forward test, at +0.117R over 4,933 trades. Marginal, not a windfall — my earlier +0.23R on 101 trades did not survive re-testing. Not advice."),
  ("Do regime filters help?", "Not in my data. A market-regime filter and a normalised-momentum-lag filter were both tested and both cut expectancy, so both were rejected."),
 ],
},

{
 "slug": "walk-forward-backtest",
 "title": "Walk-Forward Testing &amp; Lookahead Bias, Explained",
 "desc": "Why in-sample backtests lie, what lookahead and survivorship bias look like in code, how walk-forward works, and how to spot a curve fit.",
 "og_title": "Walk-Forward Testing &amp; Lookahead Bias",
 "og_desc": "Why in-sample backtests lie, and what an honest test looks like in code.",
 "headline": "Walk-Forward Testing and Lookahead Bias: How Backtests Lie",
 "crumb": "Walk-Forward Testing",
 "about": ["Backtesting", "Walk-forward analysis", "Quantitative research"],
 "eyebrow": "Guide · Research",
 "h1": "How backtests lie, and what an honest one looks like",
 "lead": "Almost every strategy works on the data it was built on. The interesting question is whether it works on data it has never seen — and most of the ways people answer that question are quietly broken.",
 "nav": NAV_TRADE,
 "body": [
  ("h2", "What is lookahead bias?"),
  ("p", "Lookahead bias is using information at bar <em>t</em> that was not available until after bar <em>t</em>. It is almost never deliberate, and it is almost always fatal to the result."),
  ("p", "The classic version is off-by-one indexing: computing a signal from the daily close and then filling the order at that same close. In reality you cannot know the close until the session is over, so the fill must land on the next bar's open. One index shift can turn a losing system into a spectacular one."),
  ("ul", ["Signal computed on the close, filled at the same close",
          "Indicators recalculated over the full dataset and then sliced, so early bars carry information from later ones",
          "Restated fundamentals or adjusted prices applied to dates before the restatement existed",
          "A stop that gets checked against the same bar's low after using that bar's high to decide the entry",
          "Splitting train and test data after normalising across the whole set"]),
  ("h2", "What is survivorship bias?"),
  ("p", "Survivorship bias is testing on a universe that only contains what is still listed today. Delisted, acquired, and bankrupt tickers vanish from most convenient datasets, so the test never has to hold the ones that went to zero. Any long-biased strategy looks better against a universe that quietly deleted its worst outcomes."),
  ("h2", "In-sample, out-of-sample, walk-forward"),
  ("p", "Three levels of honesty:"),
  ("table", (["Method", "What it does", "How much to trust it"],
             [["In-sample", "Optimise and evaluate on the same data", "None. This is curve fitting with extra steps."],
              ["Single out-of-sample split", "Optimise on the first chunk, test once on the last", "Some — but you only get one honest test, and looking twice spends it."],
              ["Walk-forward", "Roll the optimise/test window forward repeatedly, always testing on unseen data", "The most useful of the three, and still not a guarantee."]])),
  ("p", "Walk-forward works like this: fit parameters on a training window, test on the block immediately after it, then slide both windows forward and repeat. The reported result is the concatenation of every out-of-sample block. Because every trade in the result came from parameters chosen without seeing that trade, the equity curve is at least structurally honest."),
  ("h2", "The costs people leave out"),
  ("ul", ["<strong>Slippage</strong> — assume worse fills than mid, especially on gaps and small caps.",
          "<strong>Commission and financing</strong> — small per trade, decisive at high frequency.",
          "<strong>Partial fills</strong> — a backtest fills 100% of a limit order that reality would have missed.",
          "<strong>Borrow availability</strong> for shorts, which the data will not tell you about.",
          "<strong>Your own behaviour</strong> — the backtest takes every signal; you will not."]),
  ("h2", "How to read a result"),
  ("p", "Ask three questions of any backtest, including your own:"),
  ("ol", ["<strong>How many trades?</strong> Under 100 out-of-sample trades, expectancy is mostly noise.",
          "<strong>How many parameters were tuned?</strong> Every knob is a chance to fit history. A two-parameter system with 300 trades beats a nine-parameter system with 40.",
          "<strong>Where are the negative results?</strong> A write-up with no failed variants is a sales page. Real research kills more ideas than it keeps."]),
  ("p", "When I ran this on my own setups, the outcome was mostly negative: only the anchored-VWAP reclaim survived — at +0.23R over 101 trades, a number my own later adversarial re-test could not reproduce; on a 129-symbol, 10-year universe the defensible figure is +0.117R over 4,933 trades (95% CI +0.057 to +0.174). A VCP variant came out breakeven, and a gap/opening-range-breakout proxy came out at −0.28R and was cut. Two filters I was confident about — regime and normalised momentum lag — both reduced expectancy and were rejected."),
  ("p", 'That is the point of the exercise: <strong>an honest test is one that is allowed to say no.</strong> <a href="/swing-screener.html">Full write-up and engine →</a>'),
  ("callout", DISCLAIMER),
 ],
 "tools": [("/swing-screener.html", "Swing Screener", "the no-lookahead backtest engine and walk-forward results."),
           ("/trading-bot.html", "Trading bot", "the execution side, with a hard gate requiring 60 profitable paper trades before any live broker."),
           ("/guides/r-multiple-expectancy.html", "R-multiple &amp; expectancy guide", "how to measure what a test produced.")],
 "faqs": [
  ("What is lookahead bias in backtesting?", "Lookahead bias is using data at a point in time that was not actually available then — most commonly computing a signal from a bar's close and filling the order at that same close, when the fill could only have happened on the next bar. It also appears when indicators are computed over the whole dataset before splitting, or when restated data is applied to dates before the restatement existed."),
  ("What is walk-forward testing?", "Walk-forward testing fits parameters on a training window, tests on the block of data immediately after it, then slides both windows forward and repeats. The reported performance is the concatenation of out-of-sample blocks, so every trade came from parameters chosen without seeing that trade."),
  ("Why do in-sample backtests look so good?", "Because the parameters were chosen to fit that exact data. Any strategy with enough tunable knobs can be made to fit history perfectly, which says nothing about the future. In-sample results should be treated as a debugging check, not evidence."),
  ("What is survivorship bias?", "Survivorship bias is testing against a universe that only includes securities still listed today, so companies that were delisted, acquired, or went bankrupt are silently missing. Long-biased strategies look better than they were because the worst outcomes were deleted from the sample."),
  ("How many trades does a backtest need?", "At least 100 out-of-sample trades before expectancy is worth trusting, and more if the strategy is rare-signal or highly parameterised. Under 30 trades the result is dominated by luck."),
  ("What costs should a backtest include?", "Slippage, commissions, financing, partial fills, and short-borrow availability at minimum. A backtest that assumes perfect fills at mid price overstates every strategy, and overstates high-frequency ones enormously."),
 ],
 "faq_cards": [
  ("What is lookahead bias?", "Using information the market had not published yet — usually filling at the same close that generated the signal. One index shift can invent an edge that never existed."),
  ("What is walk-forward testing?", "Fit on a training window, test on the next block, slide forward, repeat. Every reported trade came from parameters chosen before that trade existed."),
  ("Why do in-sample results look great?", "Because the parameters were fitted to that data. It is curve fitting with extra steps — useful for debugging, useless as evidence."),
  ("What is survivorship bias?", "Testing on a universe of survivors only. Delisted and bankrupt names are missing, so long strategies look better than they were."),
  ("How many trades are enough?", "100+ out-of-sample trades before expectancy means much. Under 30 you are measuring luck with a decimal point."),
  ("What gets left out of backtests?", "Slippage, commissions, financing, partial fills, borrow availability — and your own willingness to actually take every signal."),
 ],
},

{
 "slug": "trading-journal",
 "title": "What to Log in a Trading Journal (and What to Ignore)",
 "desc": "The fields that change behaviour in a trading journal — R-multiple, setup tag, mistake tag, MAE/MFE — and how to review without lying to yourself.",
 "og_title": "What to Log in a Trading Journal",
 "og_desc": "The handful of fields that change behaviour — and the ones that just feel productive.",
 "headline": "What to Log in a Trading Journal, and What to Ignore",
 "crumb": "Trading Journal",
 "about": ["Trading journal", "Trade review", "Risk management"],
 "eyebrow": "Guide · Process",
 "h1": "A trading journal that changes behaviour",
 "lead": "Most journals are diaries: long, honest, and useless. A journal earns its keep when it produces one number per setup that tells you what to stop doing.",
 "nav": NAV_TRADE,
 "body": [
  ("h2", "The minimum viable journal"),
  ("p", "Six fields per trade will out-perform a page of prose, because they can be aggregated:"),
  ("table", (["Field", "Why it earns its place"],
             [["Setup tag", "The only way to compute expectancy per setup instead of per account."],
              ["Planned risk (1R in dollars)", "Makes every result comparable. Without it there are no R-multiples."],
              ["Entry, stop, exit", "Lets the journal compute R rather than trusting your memory of it."],
              ["R-multiple result", "The output that everything else exists to produce."],
              ["Mistake tag", "One of a fixed, short list. Free text hides patterns; a fixed list surfaces them."],
              ["MAE / MFE", "Maximum adverse and favourable excursion — tells you whether your stops and targets are in the wrong place."]])),
  ("h2", "Why R, not dollars"),
  ("p", "Dollars mix two different questions — was the idea good, and was the size right — into one number. R separates them. A +2R trade is a +2R trade whether you risked $50 or $500, so setups become comparable across account sizes and across time as the account grows."),
  ("formula", "R-multiple = (exit − entry) ÷ (entry − stop)"),
  ("p", 'The arithmetic behind sizing, expectancy, and break-even win rates is in the <a href="/guides/r-multiple-expectancy.html">R-multiple guide</a>.'),
  ("h2", "Mistake tags beat journal entries"),
  ("p", "Keep the list short enough to be honest and fixed enough to count. Something like: <strong>chased entry</strong>, <strong>moved stop</strong>, <strong>oversized</strong>, <strong>no setup</strong>, <strong>early exit</strong>, <strong>revenge trade</strong>, <strong>none</strong>."),
  ("p", "After 50 trades this list does something no paragraph can: it tells you that, say, 60% of your losses beyond −1R came from moving stops. That is a rule change, not a feeling. A free-text journal containing the same information will never surface it, because you will never re-read fifty paragraphs."),
  ("h2", "What MAE and MFE tell you"),
  ("ul", ["<strong>High MAE on winners</strong> — your stop is tighter than the trade needs; you are getting shaken out of good ideas.",
          "<strong>Low MFE on losers</strong> — the setup never worked at all, so entries, not exits, are the problem.",
          "<strong>High MFE, low realised R</strong> — you are exiting early. The edge exists and you are not collecting it.",
          "<strong>MAE approaching 1R on most winners</strong> — the stop is in a common noise zone; consider a different anchor for it."]),
  ("h2", "The weekly review that works"),
  ("ol", ["Compute expectancy per setup tag. Not per week, per setup.",
          "Rank mistake tags by dollars lost, not by frequency.",
          "Cut or halve the size of the worst setup for the next 20 trades. One change at a time.",
          "Check sample size before concluding anything — under 30 trades in a setup, note it and wait.",
          "Write one sentence, not one page: what changes next week."]),
  ("h2", "What to ignore"),
  ("p", "Screenshots of every chart, hour-by-hour emotional narration, indicator settings you never vary, and win-rate as a headline number. Win rate without reward-to-risk is decoration — 70% at +0.3R against 30% at −1R is a losing system, and the journal that celebrates the 70% is actively harmful."),
  ("p", 'I built <a href="/apps/tradelog/">TradeLog</a> for exactly this shape: log the trade, get expectancy per setup, no account, no server, data stays in your browser.'),
  ("callout", DISCLAIMER),
 ],
 "tools": [("/apps/tradelog/", "TradeLog", "R-multiple journal with per-setup expectancy. Installs offline, stores nothing off your device."),
           ("/risk-tools.html", "Risk toolkit", "position sizer, expectancy, break-even win rate, risk of ruin."),
           ("/guides/r-multiple-expectancy.html", "R-multiple &amp; expectancy guide", "the underlying math.")],
 "faqs": [
  ("What should you log in a trading journal?", "Six fields do most of the work: setup tag, planned risk in dollars (your 1R), entry, stop and exit prices, the resulting R-multiple, a mistake tag from a fixed short list, and maximum adverse and favourable excursion. Everything else is optional decoration."),
  ("Why record trades in R instead of dollars?", "Dollars mix idea quality with position size. R normalises for size, so a +2R trade is comparable whether you risked $50 or $500, which makes setups comparable across time and as the account grows."),
  ("What are MAE and MFE?", "Maximum adverse excursion is the worst unrealised loss during a trade; maximum favourable excursion is the best unrealised gain. Together they show whether stops are too tight, targets too far, or exits too early — high MFE with low realised R means you are leaving the edge on the table."),
  ("How often should you review a trading journal?", "Weekly for mistake tags and once every 30 or more trades per setup for expectancy. Reviewing expectancy weekly on a handful of trades produces noise-driven changes, which is worse than not reviewing at all."),
  ("Why use mistake tags instead of written notes?", "A fixed short list can be counted and ranked by dollars lost, so patterns surface after 50 trades. Free-text notes contain the same information but are never re-read in aggregate, so the pattern never appears."),
  ("Is win rate a useful journal metric?", "Only alongside reward-to-risk. Winning 70% of trades at +0.3R while losing 30% at -1R is -0.09R per trade — a losing system with a flattering win rate. Expectancy is the metric that decides."),
 ],
 "faq_cards": [
  ("What should you log?", "Setup tag, 1R in dollars, entry/stop/exit, resulting R, a mistake tag from a fixed list, and MAE/MFE. Six fields beat six paragraphs."),
  ("Why R instead of dollars?", "R strips out position size, so a +2R trade is comparable whether you risked $50 or $500 — and setups become comparable to each other."),
  ("What are MAE and MFE?", "Worst and best unrealised excursion during the trade. High MFE with low realised R means you are exiting early and leaving edge behind."),
  ("Why fixed mistake tags?", "They can be counted. After 50 trades a list says '60% of big losses came from moving stops' — a paragraph never will."),
  ("How often to review?", "Mistake tags weekly; expectancy only once a setup has 30+ trades. Weekly expectancy on five trades is noise."),
  ("Is win rate useful?", "Only with reward-to-risk attached. 70% at +0.3R against 30% at −1R is a losing system with a flattering headline."),
 ],
},

{
 "slug": "kelly-criterion",
 "title": "The Kelly Criterion, and Why Nobody Bets Full Kelly",
 "desc": "How the Kelly criterion works, the formula for trading with an R-multiple edge, why full Kelly is unusable in practice, and how half and quarter Kelly compare.",
 "og_title": "The Kelly Criterion, and Why Nobody Bets Full Kelly",
 "og_desc": "The formula, the worked example, and the reason practitioners cut it in half or worse.",
 "headline": "The Kelly Criterion, and Why Nobody Bets Full Kelly",
 "crumb": "Kelly Criterion",
 "about": ["Kelly criterion", "Position sizing", "Risk management"],
 "eyebrow": "Guide · Risk",
 "h1": "Kelly, fractional Kelly, and the gap between them",
 "lead": "Kelly answers a precise question: what fraction of capital maximises the long-run growth rate of a repeated bet. It answers it optimally, and the answer is usually too aggressive to trade.",
 "nav": NAV_TRADE,
 "body": [
  ("h2", "The formula"),
  ("p", "For a bet that wins with probability <em>p</em> and pays <em>b</em> to 1:"),
  ("formula", "f* = p − (1 − p) ÷ b\n\nwhere f* is the fraction of capital to risk,\n      p is the win probability,\n      b is the reward-to-risk ratio"),
  ("p", "A setup that wins 45% of the time at 2R:"),
  ("formula", "f* = 0.45 − 0.55 ÷ 2 = 0.45 − 0.275 = 0.175 → 17.5% of capital"),
  ("p", "Risking 17.5% of the account on one trade is not a plan, it is a countdown. That number is correct and unusable, and understanding why is the whole point of the guide."),
  ("h2", "Why full Kelly is unusable"),
  ("ul", ["<strong>Your inputs are estimates.</strong> Kelly assumes you know p and b exactly. You know them from a finite sample, and overestimating the edge overshoots the optimum badly — the growth curve falls off much faster above full Kelly than below it.",
          "<strong>The drawdowns are brutal.</strong> At full Kelly, drawdowns of 50% or more are routine, not tail events. Mathematically survivable, behaviourally not.",
          "<strong>Trades are not independent or sequential.</strong> Kelly assumes one bet resolves before the next. Real positions overlap and correlate, which stacks risk the formula never accounted for.",
          "<strong>Edges decay.</strong> The p you measured last year is not the p in force today."]),
  ("h2", "Fractional Kelly"),
  ("p", "Because the growth curve is flat near its peak but steep past it, taking a fraction of Kelly gives up little expected growth and removes most of the variance."),
  ("table", (["Sizing", "Fraction of f*", "Trade-off"],
             [["Full Kelly", "100%", "Maximum theoretical growth, ruinous variance, extremely sensitive to estimation error"],
              ["Half Kelly", "50%", "Roughly three quarters of the growth with dramatically lower drawdown — the common practitioner choice"],
              ["Quarter Kelly", "25%", "Modest growth, mild drawdowns, very tolerant of a wrong edge estimate"],
              ["Fixed 1% risk", "usually well under 25%", "Ignores the edge estimate entirely; robust, simple, and what most retail traders should start with"]])),
  ("p", "The practical reading: <strong>if your Kelly fraction says 17.5% and your rule says 1%, the rule is not being timid — it is pricing in the fact that you do not really know p.</strong>"),
  ("h2", "When Kelly is genuinely useful"),
  ("p", "Not usually as a sizing rule. It is most useful as a <em>ceiling</em> and as a diagnostic. If your fixed risk per trade is above quarter Kelly for your measured edge, you are oversized for the edge you can actually demonstrate. And if Kelly comes out negative, the formula is telling you the setup has no edge and should not be traded at all — which is the most valuable output it produces."),
  ("p", 'The <a href="/risk-tools.html">free risk toolkit</a> computes the Kelly fraction alongside expectancy, break-even win rate, and a Monte Carlo risk-of-ruin simulation, so you can see all four move together when you change the inputs.'),
  ("callout", DISCLAIMER),
 ],
 "tools": [("/risk-tools.html", "Trader's risk toolkit", "Kelly fraction, expectancy, break-even win rate, risk of ruin, position sizer."),
           ("/guides/r-multiple-expectancy.html", "R-multiple &amp; expectancy guide", "where p and b come from in the first place."),
           ("/apps/tradelog/", "TradeLog", "measures your real p and b per setup instead of guessing them.")],
 "faqs": [
  ("What is the Kelly criterion?", "The Kelly criterion gives the fraction of capital that maximises the long-run growth rate of a repeated bet. For a bet winning with probability p and paying b to 1, the optimal fraction is f* = p - (1 - p) / b."),
  ("How do you calculate Kelly for trading?", "Use your measured win rate as p and your reward-to-risk ratio as b. A setup winning 45% of the time at 2R gives f* = 0.45 - 0.55/2 = 0.175, or 17.5% of capital — a number that is mathematically correct and far too aggressive to trade."),
  ("Why do traders use half or quarter Kelly?", "Because the growth curve is flat just below the Kelly peak and steep just above it. Half Kelly captures roughly three quarters of the growth with far lower drawdowns, and fractional sizing protects against the near-certainty that your win rate and reward-to-risk estimates are wrong."),
  ("What happens if you bet more than full Kelly?", "Growth rate falls rapidly and drawdowns compound; overbetting past the optimum is much more damaging than underbetting by the same amount. Since edge estimates come from finite samples, overbetting is the more likely error."),
  ("What if the Kelly fraction is negative?", "A negative Kelly fraction means the bet has negative expectancy — there is no size at which it makes money. The correct position size is zero, which is arguably the most useful thing the formula tells you."),
  ("Should beginners use Kelly to size positions?", "Generally no. A fixed small risk per trade, typically around 1% of the account, is more robust because it does not depend on an accurate edge estimate. Kelly is more useful as a ceiling and a diagnostic than as a day-to-day sizing rule."),
 ],
 "faq_cards": [
  ("What is Kelly?", "The bet fraction that maximises long-run growth: f* = p − (1 − p) ÷ b, using win probability p and reward-to-risk b."),
  ("What does it give for trading?", "45% win rate at 2R gives 17.5% of capital per trade — correct arithmetic, unusable in practice."),
  ("Why fractional Kelly?", "The growth curve is flat below the peak and steep above it. Half Kelly keeps most of the growth and sheds most of the variance."),
  ("What if you overbet?", "Growth collapses fast past the optimum. Since edges are estimated from small samples, overbetting is the likely error."),
  ("Negative Kelly?", "The setup has negative expectancy. Correct size is zero — the most useful answer the formula gives."),
  ("Should beginners use it?", "Mostly no. A fixed ~1% risk is more robust because it does not depend on knowing your edge precisely."),
 ],
},

{
 "slug": "local-llm-ollama",
 "title": "Running a Local LLM With Ollama — A Practical Setup",
 "desc": "Running a local LLM with Ollama: picking a model for your RAM, the HTTP API, quantisation, context limits, and when local beats a cloud API.",
 "og_title": "Running a Local LLM With Ollama",
 "og_desc": "Model choice, the HTTP API, quantisation, context limits, and when local actually beats a cloud API.",
 "headline": "Running a Local LLM With Ollama: A Practical Setup",
 "crumb": "Local LLM With Ollama",
 "about": ["Ollama", "Local large language models", "Developer tooling"],
 "eyebrow": "Guide · AI",
 "h1": "Running a local LLM, and when it is actually the right call",
 "lead": "A local model is free per token, private by construction, and works offline. It is also slower and weaker than a frontier API. Knowing which jobs fall on which side of that trade is most of the skill.",
 "nav": NAV_AI,
 "body": [
  ("h2", "When local wins"),
  ("ul", ["<strong>High-volume, low-difficulty work</strong> — drafting, classifying, tagging, extracting fields, first-pass summarising. Thousands of calls a night cost nothing.",
          "<strong>Data that must not leave the machine</strong> — anything under an NDA, personal records, or client material.",
          "<strong>Batch jobs that run unattended</strong> — no rate limits, no API outage, no bill that scales with a runaway loop.",
          "<strong>Offline environments</strong> — flights, bad connections, air-gapped work."]),
  ("p", "When local loses: long multi-step reasoning, large-context work, anything where a subtle mistake is expensive, and code generation of any real complexity. Use the frontier API there and stop being precious about it."),
  ("h2", "Picking a model for your hardware"),
  ("p", "The binding constraint is memory. A rough guide for quantised weights:"),
  ("table", (["RAM / VRAM", "Realistic model size", "What it is good for"],
             [["8 GB", "3B–7B quantised", "Classification, tagging, short rewrites"],
              ["16 GB", "7B–14B quantised", "Drafting, summarising, structured extraction"],
              ["32 GB", "14B–32B, or a small MoE", "Solid general drafting, light code assistance"],
              ["64 GB+", "30B+ or mixture-of-experts models", "The point where local starts feeling genuinely useful"]])),
  ("p", "Mixture-of-experts models are worth knowing about: they hold a large parameter count in memory but only activate a fraction per token, so throughput feels much closer to a small model than the parameter count suggests. That is the sweet spot on a well-specced laptop."),
  ("h2", "Quantisation, briefly"),
  ("p", "Quantisation stores weights at lower precision — 4-bit and 5-bit variants being the common choices — which shrinks memory use several-fold for a modest quality loss. Practical rule: <strong>a larger model at 4-bit usually beats a smaller model at 8-bit</strong> at the same memory budget. Below 4-bit, quality degrades quickly."),
  ("h2", "Use the HTTP API, not the CLI"),
  ("p", "Ollama exposes a local HTTP endpoint on port 11434. Scripts should call that, not shell out to the interactive command."),
  ("formula", "curl http://localhost:11434/api/generate -d '{\n  \"model\": \"your-model\",\n  \"prompt\": \"Summarise this in one sentence: ...\",\n  \"stream\": false,\n  \"options\": {\"temperature\": 0.2}\n}'"),
  ("p", "This matters more than it sounds. The interactive CLI writes progress and control characters to stdout; capturing that from a script produces output that is subtly corrupted in ways that only show up in production. <strong>Automations should always talk to the HTTP API.</strong> I learned that the annoying way, and it is now a standing rule in my own tooling."),
  ("h2", "Settings that actually matter"),
  ("ul", ["<strong>temperature</strong> — 0.1–0.3 for extraction and classification, higher only when you want variety.",
          "<strong>context length</strong> — bigger contexts cost memory and speed. Set it to what the job needs, not to the maximum.",
          "<strong>reasoning / thinking modes</strong> — if the model supports an extended-thinking mode, it will happily spend a long time on a job that did not need it. Disable it for high-volume mechanical work; a request that used to take seconds can otherwise appear to hang.",
          "<strong>keep-alive</strong> — reloading weights per call dominates latency in batch jobs. Keep the model resident.",
          "<strong>structured output</strong> — ask for JSON and validate it. Local models drift from a schema more than frontier models do, so parse defensively and retry."]),
  ("h2", "A realistic architecture"),
  ("p", "The pattern that works is a two-tier one. A local model does the volume: drafting, tagging, first-pass extraction, overnight batches. A frontier model does the judgement: the final pass, the hard reasoning, anything that ships to a customer. A quality gate sits in between and rejects bad local output before it reaches the expensive step."),
  ("p", 'That is how my own outreach and automation pipelines run — local model drafts overnight, an automated quality audit quarantines anything that fails its checks, and only the passing output moves forward. <a href="/stack.html">The rest of the stack is here →</a>'),
 ],
 "tools": [("/stack.html", "My stack", "the actual tools behind the trading, the code, and the automation."),
           ("/freightdesk.html", "FreightDesk AI", "a production example of local-model drafting with a human-grade quality gate."),
           ("/guides/rag-explained.html", "RAG explained", "how to give a local model access to your own documents.")],
 "faqs": [
  ("What is Ollama?", "Ollama is a tool for running large language models locally on your own machine. It manages model downloads and serves them behind a local HTTP API on port 11434, so applications can call a local model the same way they would call a cloud API."),
  ("How much RAM do you need to run a local LLM?", "Roughly: 8 GB handles 3B-7B quantised models for classification and short rewrites, 16 GB handles 7B-14B for drafting and extraction, 32 GB handles 14B-32B or a small mixture-of-experts model, and 64 GB or more is where local models start feeling genuinely capable."),
  ("Should you call Ollama from the CLI or the HTTP API?", "Always the HTTP API for anything automated. The interactive CLI writes progress and control characters to stdout, so capturing its output from a script produces subtly corrupted text. Scripts should POST to http://localhost:11434 instead."),
  ("What is quantisation?", "Quantisation stores model weights at lower numeric precision, most commonly 4-bit or 5-bit, cutting memory use several-fold for a modest quality loss. At a fixed memory budget, a larger model at 4-bit usually outperforms a smaller model at 8-bit."),
  ("When is a local LLM better than a cloud API?", "When the work is high-volume and low-difficulty, when the data cannot leave the machine, when jobs run unattended overnight, or when there is no connection. Frontier APIs remain better for long multi-step reasoning, large contexts, and complex code generation."),
  ("Why does a local model sometimes seem to hang?", "Usually an extended reasoning or thinking mode is enabled, so the model spends a long time deliberating on a task that did not need it. Disabling thinking for mechanical high-volume work typically returns response times to seconds."),
 ],
 "faq_cards": [
  ("What is Ollama?", "A local model runner that serves LLMs behind an HTTP API on port 11434, so your code calls a local model like a cloud one."),
  ("How much RAM?", "8 GB for 3–7B, 16 GB for 7–14B, 32 GB for 14–32B or a small MoE, 64 GB+ before local really feels capable."),
  ("CLI or HTTP API?", "HTTP API, always, for automation. The interactive CLI emits control characters that quietly corrupt captured output."),
  ("What is quantisation?", "Lower-precision weights — usually 4-bit or 5-bit. At the same memory, a bigger 4-bit model usually beats a smaller 8-bit one."),
  ("When does local win?", "High-volume simple work, private data, unattended batches, offline. Frontier APIs still win on hard reasoning and complex code."),
  ("Why does it hang?", "Extended thinking mode left on for a mechanical task. Turn it off for batch work and responses drop back to seconds."),
 ],
},

{
 "slug": "rag-explained",
 "title": "RAG Explained — Retrieval-Augmented Generation, Plainly",
 "desc": "What retrieval-augmented generation is, how chunking, embeddings and reranking fit together, where RAG breaks, and when a graph beats vector search.",
 "og_title": "RAG Explained, Plainly",
 "og_desc": "Chunking, embeddings, reranking, and the four places RAG pipelines actually break.",
 "headline": "Retrieval-Augmented Generation (RAG), Explained Plainly",
 "crumb": "RAG Explained",
 "about": ["Retrieval-augmented generation", "Embeddings", "Applied AI"],
 "eyebrow": "Guide · AI",
 "h1": "RAG, without the diagram everyone reposts",
 "lead": "Retrieval-augmented generation is a simple idea wrapped in intimidating vocabulary: before answering, go and find the relevant text, then put it in the prompt. Everything hard about RAG is in the finding.",
 "nav": NAV_AI,
 "body": [
  ("h2", "What problem does RAG solve?"),
  ("p", "A language model knows what was in its training data and nothing about your documents, your database, or anything that happened after its cutoff. The two ways to fix that are fine-tuning, which bakes knowledge into weights and is expensive to update, and retrieval, which fetches the relevant text at question time and hands it to the model."),
  ("p", "<strong>Retrieval wins for facts that change.</strong> Fine-tuning wins for behaviour and format. Most people who think they need fine-tuning need retrieval and a better prompt."),
  ("h2", "The pipeline"),
  ("ol", ["<strong>Chunk</strong> — split documents into passages small enough to be precise and large enough to be self-contained.",
          "<strong>Embed</strong> — convert each chunk into a vector that encodes meaning, so similar text lands nearby in vector space.",
          "<strong>Index</strong> — store the vectors so nearest-neighbour lookups are fast.",
          "<strong>Retrieve</strong> — embed the question the same way and pull the closest chunks.",
          "<strong>Rerank</strong> — score the candidates with a stronger model and keep the best few.",
          "<strong>Generate</strong> — put those chunks in the prompt with an instruction to answer only from them, and to say so when they do not contain the answer."]),
  ("h2", "Chunking is where most quality is won or lost"),
  ("p", "Chunk too small and a passage loses the context that made it meaningful — a paragraph that says \"this is not permitted\" without the sentence naming what \"this\" is. Chunk too large and the embedding averages several topics into a vector that is close to nothing in particular."),
  ("ul", ["Split on structure — headings, sections, list items — before splitting on length.",
          "Overlap adjacent chunks slightly so a sentence spanning a boundary is not orphaned.",
          "Attach metadata: source, section title, date. It is needed for both filtering and citation.",
          "Keep tables and code blocks intact. Splitting them mid-structure destroys their meaning entirely."]),
  ("h2", "Where RAG pipelines actually fail"),
  ("table", (["Failure", "What it looks like", "Usual fix"],
             [["Retrieval miss", "The answer exists in the corpus but never reaches the prompt", "Hybrid search — combine keyword and vector retrieval; add reranking"],
              ["Right chunk, wrong slice", "The retrieved passage is adjacent to the answer", "Better chunk boundaries, overlap, retrieve neighbours of a hit"],
              ["Model ignores context", "Answer contradicts the supplied passages", "Instruct explicitly to answer only from context; require citations per claim"],
              ["Confident empty answer", "Nothing relevant was retrieved and the model invents something", "Give it permission to say the corpus does not contain the answer, and test that path"]])),
  ("p", "The second-order lesson: <strong>evaluate retrieval separately from generation.</strong> If you only measure final answers you cannot tell whether the retriever failed or the model did, and you will tune the wrong half of the system."),
  ("h2", "When plain vector search is not enough"),
  ("p", "Vector similarity is good at \"find text that means something like this\" and bad at relationships — prerequisites, dependencies, ordering, hierarchy. Ask \"what do I need to understand before this concept?\" and similarity search returns passages that <em>mention</em> the concept, not the ones that <em>precede</em> it."),
  ("p", "That is where a graph helps: model the entities and the edges between them, walk the graph to assemble context, and use retrieval to fill in the text. This graph-augmented approach is the subject of one of the two SIGCSE Technical Symposium 2026 papers I co-authored — using knowledge graphs to build adaptive curriculum maps, so a tutoring system can reason about prerequisite structure rather than topical similarity."),
  ("p", 'The companion paper looked at bilingual coding for inclusive CS learning (<a href="https://doi.org/10.1145/3770761.3777339" rel="noopener">DOI 10.1145/3770761.3777339</a>), a mixed-methods IRB study of 60 participants that reported significant pre-to-post gains in learner confidence. <a href="/about.html">More on the research →</a>'),
  ("h2", "A sane starting build"),
  ("ol", ["Start with 20 real questions and their correct answers. Without an evaluation set you are guessing.",
          "Chunk on structure, embed, and retrieve top-20 with hybrid keyword plus vector search.",
          "Rerank down to the 3–5 chunks you actually put in the prompt.",
          "Require the model to cite the chunk behind each claim, and to refuse when the context is insufficient.",
          "Measure retrieval hit rate and answer accuracy separately, then fix whichever is worse."]),
 ],
 "tools": [("/about.html", "About &amp; research", "the SIGCSE 2026 papers, including the graph-augmented retrieval work."),
           ("/guides/local-llm-ollama.html", "Local LLM guide", "how to run the generation half of this on your own machine."),
           ("/stack.html", "My stack", "the tools I actually use for this work.")],
 "faqs": [
  ("What is retrieval-augmented generation (RAG)?", "RAG is a pattern where relevant text is retrieved from your own documents at question time and placed into the model's prompt, so the answer is grounded in that source material rather than in the model's training data alone."),
  ("What is the difference between RAG and fine-tuning?", "Retrieval supplies facts that change and can be updated by re-indexing documents. Fine-tuning changes behaviour, tone, and format by adjusting weights, and is expensive to update. Most systems that seem to need fine-tuning actually need better retrieval and a better prompt."),
  ("What is chunking in RAG?", "Chunking is splitting documents into passages before embedding them. Chunks that are too small lose the context that made them meaningful; chunks that are too large average several topics into one vector. Splitting on document structure first, with slight overlap and attached metadata, works better than splitting purely on length."),
  ("Why does RAG return wrong answers?", "Four common causes: the retriever never surfaced the right passage, it surfaced an adjacent passage instead of the answer, the model ignored the supplied context, or nothing relevant was retrieved and the model invented an answer. Evaluating retrieval separately from generation is what tells you which one is happening."),
  ("What is reranking?", "Reranking takes the candidate passages returned by fast vector search and scores them with a stronger, slower model, keeping only the best few for the prompt. It substantially improves precision because vector similarity alone is a coarse relevance signal."),
  ("When is a knowledge graph better than vector search?", "When the question is about relationships rather than similarity — prerequisites, dependencies, ordering, or hierarchy. Vector search finds passages that mention a concept; a graph can find the concepts that must come before it. Combining the two is the basis of graph-augmented retrieval."),
 ],
 "faq_cards": [
  ("What is RAG?", "Fetch the relevant passages from your own documents at question time and put them in the prompt, so the answer is grounded in your sources."),
  ("RAG or fine-tuning?", "Retrieval for facts that change; fine-tuning for behaviour and format. Most 'we need fine-tuning' problems are retrieval problems."),
  ("Why does chunking matter?", "Too small loses context, too large blurs the vector. Split on structure, overlap slightly, keep tables and code intact, attach metadata."),
  ("Why do answers come back wrong?", "Retrieval miss, adjacent-passage miss, model ignoring context, or invention on an empty retrieval. Measure retrieval separately to tell which."),
  ("What is reranking?", "Rescoring the vector-search candidates with a stronger model and keeping only the best few. Big precision win for little work."),
  ("When do you need a graph?", "When the question is about prerequisites, dependencies, or ordering — relationships that similarity search cannot represent."),
 ],
},

]
