"""Guide content: security for student founders shipping a first product. Data only; rendering lives in engine.py."""

NAV_DEV = [("/", "Work"), ("/guides.html", "Guides"), ("/stack.html", "Stack"), ("/apps.html", "Apps")]

GUIDES = [

{
 "slug": "student-founder-security-checklist",
 "title": "The Student Founder's Security Checklist",
 "desc": "An 18-point security checklist for student founders shipping their first product: secrets, dependency CVEs, config, TLS, backups, and more.",
 "og_title": "The Student Founder's Security Checklist",
 "og_desc": "18 things to fix before your first user, your first security questionnaire, or the bot that finds your leaked key first.",
 "headline": "The Student Founder's Security Checklist: 18 Things to Fix Before Your First User",
 "crumb": "Security Checklist",
 "about": ["Application security", "Startup security", "DevSecOps"],
 "eyebrow": "Guide · Security",
 "h1": "18 things to fix before your first real user",
 "lead": "Nobody teaches this in the intro CS sequence, and by the time it matters, it usually matters all at once. None of these 18 items need a security team, a budget, or an expert. Most take under an hour. A few take five minutes.",
 "level": "Beginner",
 "nav": NAV_DEV,
 "body": [
  ("h2", "The week the checklist stops being optional"),
  ("p", "A hackathon project ships over a weekend. A domain, a signup form, a Stripe test key that quietly becomes a live key somewhere around week two. Three weeks later there is a first paying customer, or a mention somewhere that sends real traffic, or a procurement team sends a one-page security questionnaire asking about encryption at rest, key rotation, and the last time someone tested a restore. Nobody covered this in class, and the honest answer to most of those questions right now is \"I don't know\", which is a worse answer than admitting a real, specific gap."),
  ("p", "The good news is that this is not a 200-item enterprise framework. It is 18 things, all of them fixable by a single founder, most of them free. Do them before the questionnaire arrives, before the pentest is scheduled, or before an automated scanner finds the gap for you, and the first serious security conversation about the product goes very differently."),
  ("h2", "The 18-point checklist"),
  ("p", "A quick-reference list first. Each one gets a short explanation below, with the actual commands."),
  ("ol", [
   "Never commit a secret, not even for five minutes.",
   "Treat <code>.env.example</code> as the only env file that belongs in git.",
   "Audit git history, not just the working tree, for anything that leaked.",
   "Rotate first, investigate second.",
   "Pin your lockfile and scan it for known CVEs on every install.",
   "Know your dependency licenses before you take money for the product.",
   "Scope every API key to the least it needs to do its job.",
   "Never ship a secret key inside client-side JavaScript.",
   "Use separate keys per environment, and kill old ones when people leave.",
   "Change every default credential before anything goes live.",
   "Review Dockerfiles, Terraform, and CI config like you review application code.",
   "Put cloud storage and databases behind a private network, not the open internet.",
   "Force HTTPS everywhere and turn on HSTS.",
   "Set the handful of security headers that actually matter.",
   "Get CORS right, especially once cookies or auth headers are involved.",
   "Hash passwords properly and rate-limit anything that accepts one.",
   "Log enough to debug a problem, never enough to leak a secret.",
   "Back up your data, and prove the restore works before you need it.",
  ]),
  ("h2", "Secrets are the fastest way to lose the company"),
  ("p", "A leaked secret is not a hypothetical. GitHub's own secret-scanning partner program means a real subset of provider keys pushed to a public repo can be flagged and revoked by the provider within minutes of the push, not at the next audit. Attackers run the same kind of scan continuously and for free. The fix costs nothing and takes less time than this paragraph did to write."),
  ("h3", "1. Never commit a secret, not even for five minutes"),
  ("p", "Every key, token, password, and connection string belongs in an environment variable loaded from a file git never sees. The habit that actually holds: create <code>.env</code> before the first route, and put <code>.env</code> in <code>.gitignore</code> in that same first commit. \"I'll add it to .gitignore before I push\" is the sentence that precedes almost every leaked-key story."),
  ("h3", "2. Treat .env.example as the only env file that belongs in git"),
  ("p", "Commit a <code>.env.example</code> with variable names and placeholder values, never the real file. That gives the next person, or you on a new laptop in six months, the exact shape of what's required without a single real credential ever touching version control."),
  ("formula", ".env.example\nSTRIPE_SECRET_KEY=sk_live_placeholder_never_a_real_value\nDATABASE_URL=postgres://user:pass@host:5432/db"),
  ("h3", "3. Audit git history, not just the working tree"),
  ("p", "Deleting a file in a new commit does not remove it from history. Anyone who clones the repo can still read every version that ever existed, including the one from three commits ago before anyone noticed."),
  ("formula", "git log --all --full-history -- .env\ngit log -p --all -S \"sk_live\" -- ."),
  ("p", "If something real turns up, do not just delete it in a new commit. Purge it from history with <code>git filter-repo</code> (the maintained tool for this) or BFG Repo-Cleaner, then force-push to every remote, and treat the key as burned regardless, per the next point."),
  ("h3", "4. Rotate first, investigate second"),
  ("p", "The moment a leaked secret turns up, the order is: revoke it at the provider, issue a new one, update everywhere it's used, then figure out how it got there and for how long. Rewriting history removes it from future clones, but does nothing about copies already sitting in forks, CI logs, or a bot that already scraped it. A key that has ever been public is compromised, full stop, whether or not there's evidence of misuse yet."),
  ("h2", "Dependencies: someone else's bug becomes yours the moment you install it"),
  ("h3", "5. Pin your lockfile and scan it for known CVEs on every install"),
  ("p", "<code>package.json</code> and <code>requirements.txt</code> describe ranges; <code>package-lock.json</code>, <code>yarn.lock</code>, and <code>uv.lock</code> pin exact versions. Commit the lockfile, always. Then check the pinned versions against a vulnerability database, not just at launch but on a cadence: a dependency that was clean the day it was installed can pick up a CVE the following month with nothing on your side having changed."),
  ("formula", "npm audit --omit=dev\npip-audit -r requirements.txt\nosv-scanner -L package-lock.json"),
  ("p", "Most findings resolve with a version bump. The ones that don't, usually a transitive dependency stuck behind an unmaintained package, are worth a one-line comment explaining why it's accepted, so the next audit doesn't rediscover the same dead end."),
  ("h3", "6. Know your dependency licenses before you take money for the product"),
  ("p", "A permissive license (MIT, BSD, Apache-2.0) imposes almost no obligation. A copyleft license, especially AGPL, can require you to open-source your own server code if you distribute a modified version, a fact that has killed real acquisitions when it surfaces late in diligence. Check this once, before charging anyone, not during a term sheet."),
  ("h2", "Keys: the difference between a leak and a disaster is scope"),
  ("h3", "7. Scope every API key to the least it needs to do its job"),
  ("p", "Stripe, AWS, and most serious providers let you create a restricted key limited to specific actions or a specific resource, instead of the full-account key. Use the scoped version everywhere except the one place that genuinely needs full access. A leaked read-only key is an inconvenience. A leaked full-account key is the whole business."),
  ("h3", "8. Never ship a secret key inside client-side JavaScript"),
  ("p", "Anything prefixed for the browser (<code>NEXT_PUBLIC_</code>, <code>VITE_</code>, <code>REACT_APP_</code>) gets compiled directly into the bundle every visitor downloads. A \"secret\" key carrying one of those prefixes is not secret. It is public, indexed, and readable from dev tools by anyone who looks. Server-only secrets stay server-only; if the browser needs to reach a paid API, it calls your server, which holds the real key."),
  ("h3", "9. Use separate keys per environment, and kill old ones when people leave"),
  ("p", "Dev, staging, and production should never share a key. A staging key exposed in a public demo repo should not be able to touch a real customer's data. And a key issued to a cofounder or contractor who leaves the project is a live credential until someone actively revokes it, so put that one step in whatever passes for an offboarding process, even if the process is a single line in a note."),
  ("h2", "Config and infrastructure: the part most tutorials skip"),
  ("h3", "10. Change every default credential before anything goes live"),
  ("p", "Default database passwords, default admin panels, a Redis instance with no auth at all: these get found by automated scanners within hours of a port opening to the internet, not by an attacker who picked the project specifically. Change every default on day one, before the first deploy, not after the first incident."),
  ("h3", "11. Review Dockerfiles, Terraform, and CI config like you review application code"),
  ("p", "Infrastructure as code is still code, and it fails the same way application code does when nobody reviews it: containers running as root, security groups open to the entire internet on a port with no business being public, state files with plaintext secrets committed alongside everything else. These files get written once, work, and never get looked at again until something goes wrong."),
  ("h3", "12. Put cloud storage and databases behind a private network, not the open internet"),
  ("p", "A storage bucket or database that only needs to talk to your own application server has no reason to accept connections from anywhere else. Network-scoped access and security groups restricted to known sources turn \"the whole internet can reach it\" into \"only my application can reach it,\" at effectively zero cost."),
  ("h2", "What a browser or a scanner can see from the outside"),
  ("h3", "13. Force HTTPS everywhere and turn on HSTS"),
  ("p", "Most serious hosts do this by default now, which is exactly why it's easy to forget to verify. Confirm plain HTTP actually redirects rather than serving content, and confirm the HSTS header is present so a browser refuses to downgrade even if something tries to force it."),
  ("formula", "curl -sI http://yourapp.com   # should redirect, not serve content\ncurl -sI https://yourapp.com | grep -i strict-transport-security"),
  ("h3", "14. Set the handful of security headers that actually matter"),
  ("p", "This does not need a security team, it needs about six headers: a Content-Security-Policy, <code>X-Content-Type-Options: nosniff</code>, a frame-ancestors or X-Frame-Options rule, a sane cookie policy (<code>Secure</code>, <code>HttpOnly</code>, <code>SameSite</code>), and a referrer policy. Most frameworks ship a one-line helper for all of it. Check what's actually being sent, not what you think you configured."),
  ("formula", "curl -sI https://yourapp.com | grep -iE 'content-security-policy|x-frame-options|x-content-type-options'"),
  ("h3", "15. Get CORS right, especially once cookies or auth headers are involved"),
  ("p", "A wildcard <code>Access-Control-Allow-Origin: *</code> next to <code>Access-Control-Allow-Credentials: true</code> is a misconfiguration most browsers refuse to honor, but the version that does work, an explicit origin reflected back for every request, is just as bad in practice. Allow only the origins that genuinely need access, and treat the list like a firewall rule, not a formality."),
  ("h2", "Application basics that get skipped under deadline pressure"),
  ("h3", "16. Hash passwords properly and rate-limit anything that accepts one"),
  ("p", "bcrypt or argon2, never a home-rolled scheme, never plain SHA-256 with no salt. Put a rate limit on login, signup, and password-reset endpoints specifically: these are what automated credential-stuffing tools hit first, and they're cheap to protect because legitimate traffic (a human typing a password) looks nothing like the attack pattern of thousands of attempts a minute."),
  ("h3", "17. Log enough to debug a problem, never enough to leak a secret"),
  ("p", "Request IDs, timestamps, status codes, and sanitized error messages are genuinely useful at 2am. Full request bodies, tokens, and passwords in the same log are a second, less-protected copy of every secret already being protected elsewhere. Redact before logging, not after something goes wrong."),
  ("h3", "18. Back up your data, and prove the restore works before you need it"),
  ("p", "A backup that has never been restored from is a hypothesis, not a backup. The old rule of thumb (3 copies, 2 media, 1 offsite) is overkill for a two-person side project, but the restore test is not optional: schedule one actual restore onto a clean environment before there is a customer whose data cannot be lost, so the day the backup turns out to be silently broken isn't the day it's needed."),
  ("h2", "Before your first real user"),
  ("p", "Not all 18 matter equally on day one. If time is short, the ones that bite fastest are the secrets group (1 through 4), default credentials (10), forced HTTPS (13), and a tested backup (18). Everything else matters, but those are the ones an opportunistic scanner finds within hours of a public launch, not the ones that need a targeted attacker."),
  ("p", "One more thing worth doing that isn't on the numbered list, because it's a process rather than a control: write a one-paragraph incident response note before it's needed: who gets notified if a key leaks, what gets rotated first, where the postmortem gets written down. A plan written calmly in five minutes beats one improvised during the incident."),
  ("h2", "Before your first security questionnaire or pentest"),
  ("p", "This is the point where \"no known bad patterns\" stops being enough and a customer wants evidence: a disclosure policy (a <code>security.txt</code> file is the lightest version of this), branch protection with required reviews, CI that runs tests and a secret scan on every pull request, dependency updates on a schedule rather than never, and a documented, even lightweight, incident response process. None of it is exotic. All of it is exactly what shows up on the enterprise security questionnaires and SOC 2 readiness checklists that eventually land on a growing founder's desk, usually with a two-week deadline attached."),
  ("h2", "What DIRA checks for you automatically"),
  ("p", "A meaningful share of this checklist is mechanical enough to automate, which is the reason I built <a href=\"/dira.html\">DIRA</a>: a free, MIT-licensed command-line scanner that runs the secrets, dependency, config, and TLS checks above against your own codebase in under a second on a warm run, with zero telemetry and zero dependencies of its own."),
  ("table", (["Checklist items", "What DIRA covers"],
             [["1–4, secrets and git history", "Secret scanning across two dozen provider patterns plus an entropy-gated generic rule, redacted before they reach a report, plus a dedicated pass over git history for anything since removed from the working tree."],
              ["5–6, dependencies and licenses", "Every lockfile entry resolved against OSV.dev for known CVEs, and every dependency's license classified, so copyleft risk shows up before a diligence call instead of during one."],
              ["10–12, config and infrastructure", "38 misconfiguration rules across Docker, Kubernetes, Terraform, GitHub Actions, cloud IAM, frontend code, and LLM-specific patterns like a provider key shipped to the browser."],
              ["13–15, TLS and headers", "A live check of the domain's TLS validity and expiry, HSTS, and the same security headers covered above, plus whether <code>/.env</code> or <code>/.git/config</code> is being served to the public internet."],
              ["16–18 and the rest", "An 18-point security-readiness score modeled on what SOC 2 and enterprise questionnaires actually ask for: CI, tests, secret scanning, CODEOWNERS, IaC, backups, incident response, rolled into one percentage, with checks no scanner can verify, like MFA and access reviews, listed as manual attestations instead of silently skipped."]])),
  ("p", "<code>dira scan .</code> for a first pass, <code>dira scan . -t yourapp.com</code> to add the live TLS and header checks, <code>dira fix --apply</code> to write the policy files it can generate safely. It will not replace a real pentest or a SOC 2 audit, and it says so in its own report, but it closes most of this checklist in about the time it takes to read this sentence twice. <a href=\"/dira.html\">See the full scanner and install instructions →</a>"),
  ("h2", "When the checklist isn't enough on its own"),
  ("p", "DIRA is free because most of this list is mechanical, and mechanical problems don't need a person attached to them. What it can't do is sit on a call, read the actual architecture, and tell you which of the manual attestations in its own report are real for your specific setup. That's the gap <a href=\"/services.html#shield-audit\">Shield Audit</a> fills: DIRA runs against the repo and the live domain, then the findings get walked through together into a scored report with a fix plan attached, not just a list."),
  ("p", "And if the immediate need is smaller than a full audit, a chunk of what's above is also written up as templates and playbooks in <a href=\"/store.html\">the store</a>, the kind of thing that's faster to buy than to rebuild from scratch at 11pm before a demo."),
  ("h2", "The point of a checklist"),
  ("p", "The founder from the opening story didn't need a security team. They needed about ninety minutes, spread across a weekend, going down this exact list before the questionnaire arrived instead of after. That's the whole job a checklist does: not turning anyone into an expert, just making sure the easy, expensive mistakes never get the chance to become the story."),
 ],
 "tools": [("/dira.html", "DIRA", "the free scanner behind most of this checklist: secrets, dependency CVEs, config, TLS, and a startup readiness score."),
           ("/services.html#shield-audit", "Shield Audit", "a DIRA-powered audit with a human walkthrough and a fix plan, for when the checklist needs a second set of eyes."),
           ("/store.html", "Store", "templates and playbooks for the parts of shipping a product that aren't code.")],
 "faqs": [
  ("What is the fastest way to check if I've ever committed a secret?", "Run git log --all --full-history -- .env for a specific file, or better, run a dedicated secret scanner such as dira scan . or gitleaks against the full history, not just the current working tree. Deleting a file in a new commit does not remove it from earlier commits, so a search of only the current files misses anything that was already fixed the wrong way."),
  ("If a secret key leaked, do I need to rewrite git history?", "Rewriting history with git filter-repo or BFG Repo-Cleaner, then a force-push, removes the secret from future clones, but treat the key itself as compromised the moment it was ever public regardless of any history rewriting. Revoke and reissue the key first; clean the history second, since forks and cached clones can still hold the old commits."),
  ("What's the minimum security setup before a first paying customer?", "Secrets kept out of git and git history, default credentials changed everywhere, HTTPS forced with HSTS, a dependency CVE scan run at least once, and one tested backup restore. Those five catch the mistakes that automated scanners and bots find within hours of a public launch, before anything more targeted becomes relevant."),
  ("Can a free scanner like DIRA replace a real security audit?", "No, and it says so in its own report. Automated scanning finds known bad patterns; it cannot see MFA enforcement, access reviews, or an actual threat model, which is why those appear as manual attestations rather than pass or fail checks. It is a strong first pass and a good gate for pull requests, not a substitute for a human-reviewed pentest or a SOC 2 audit."),
  ("What should a student founder do before an enterprise security questionnaire?", "Have a disclosure policy, even a simple security.txt file, branch protection with required reviews, CI that runs tests and a secret scan on every pull request, a documented dependency-update cadence, and a one-paragraph incident response plan. Together these cover most of what a SOC 2 readiness checklist or an enterprise procurement questionnaire actually asks for."),
  ("How much does it cost to fix most of an 18-point security checklist?", "Close to nothing. Every item on this list uses free tooling: git itself, free-tier CVE scanners, a framework's built-in headers middleware, and a free scanner like DIRA for the mechanical checks. The real cost is time, roughly a couple of hours spread across a weekend, not money."),
 ],
 "faq_cards": [
  ("Check for a committed secret?", "git log --all --full-history on the file, or run a real scanner like dira scan . or gitleaks against full history, since deleting a file in a new commit doesn't remove it from old ones."),
  ("Leaked key, rewrite history?", "Revoke and reissue the key first, always. History rewriting (filter-repo/BFG + force-push) only stops future clones; forks and caches can still hold the old commits."),
  ("Minimum setup before a paying customer?", "Secrets out of git and history, default creds changed, HTTPS + HSTS forced, one CVE scan run, one tested backup restore. Those five get found fastest by bots."),
  ("Does DIRA replace an audit?", "No, it says so itself. It finds known bad patterns; MFA, access reviews, and real threat modeling stay manual attestations, not automated checks."),
  ("Before a security questionnaire?", "A security.txt, branch protection with required reviews, CI running tests + a secret scan per PR, a dependency-update cadence, and a one-paragraph incident response plan."),
  ("Cost to fix most of this list?", "Close to nothing: git, free-tier CVE scanners, a framework's headers middleware, and a free scanner for the mechanical checks. The real cost is a weekend, not money."),
 ],
},

]
