"""Guide content: under-served clusters — measurement noise, reading papers, interview study
systems, running a club, and macOS job scheduling. Data only; rendering lives in engine.py."""

NAV_BODY = [("/", "Work"), ("/guides.html", "Guides"), ("/apps.html", "Apps"), ("/media-kit.html", "Media Kit")]
NAV_EDU = [("/", "Work"), ("/guides.html", "Guides"), ("/research.html", "Research"), ("/about.html", "About")]
NAV_CAREER = [("/", "Work"), ("/guides.html", "Guides"), ("/resume.html", "Resume"), ("/apply.html", "Apply OS")]
NAV_DEV = [("/", "Work"), ("/guides.html", "Guides"), ("/stack.html", "Stack"), ("/apps.html", "Apps")]

GUIDES = [

{
 "slug": "weight-tracking-signal-vs-noise",
 "title": "Weight Tracking: Signal vs Noise",
 "desc": "Why a daily weigh-in is mostly noise, how big that noise actually is, what a moving average recovers, and how long to wait before a trend means anything.",
 "og_title": "Weight Tracking: Signal vs Noise",
 "og_desc": "The scale is a noisy instrument. Here is the noise level, the filter, and the wait time before a number means anything.",
 "headline": "Tracking Weight Without Losing Your Mind: Signal vs Noise",
 "crumb": "Signal vs Noise",
 "about": ["Body composition", "Measurement noise", "Habit tracking", "Calorie deficit"],
 "eyebrow": "Guide · Body",
 "h1": "The scale is a noisy instrument. Treat it like one.",
 "lead": "Almost every bad decision people make about their own body comes from reading a single measurement as if it were a fact. It is not a fact. It is one sample from a noisy signal, and the noise is bigger than the thing you are trying to measure.",
 "level": "Beginner",
 "nav": NAV_BODY,
 "body": [
  ("warn", "General information, not medical advice. Talk to a doctor or a registered dietitian before changing how you eat or train, especially with any medical condition, any medication, or any history of disordered eating. Nothing here is a diagnosis and nothing here is a prescription."),
  ("h2", "The instrument problem nobody warns you about"),
  ("p", "A bathroom scale is precise and inaccurate at the same time, which is the worst combination an instrument can have. Step on it twice and it gives the same number to a tenth of a pound, so it feels authoritative. Step on it tomorrow after a salty dinner and it is up 2.6 pounds, which is physically impossible as fat gain and completely normal as a reading."),
  ("p", "The result is a person doing everything right, watching a number go the wrong way, and concluding the plan is broken. It is not broken. The measurement is noisy, and nobody handed them the noise level."),
  ("p", "This guide is about the measurement, not the plan. If you need the plan — maintenance, deficit size, the protein floor — that is <a href=\"/guides/cut-calorie-math.html\">the calorie arithmetic guide</a>. This one answers a narrower and more useful question: <strong>given a number on a scale this morning, what are you actually allowed to conclude?</strong>"),
  ("h2", "Where the noise comes from, and roughly how big it is"),
  ("p", "Body mass on any given morning is fat, plus lean tissue, plus bone, plus whatever water, food, and waste happen to be inside you at that moment. Only the first two change slowly. Everything else moves fast, and it moves in pounds."),
  ("table", (["Source", "Typical same-week swing", "How fast it resolves"],
             [["Glycogen and its bound water", "1–4 lb", "Days. Every gram of stored carbohydrate carries roughly 3 g of water with it."],
              ["Sodium and fluid balance", "1–3 lb", "24–72 hours after intake normalises."],
              ["Gut contents (food and waste in transit)", "1–3 lb", "Hours to days. Fibre and meal timing dominate."],
              ["Hard or novel training", "1–3 lb", "2–5 days. Muscle damage draws water into the tissue."],
              ["Sleep debt and stress", "0.5–2 lb", "Variable. Cortisol-driven fluid retention, resolves with sleep."],
              ["Menstrual cycle, if applicable", "1–5 lb", "Predictable across a cycle, not across a week."],
              ["Actual fat change at a 500 cal/day deficit", "≈ 1 lb per week", "Slow, monotone, and completely buried by everything above."]])),
  ("p", "Read the last row against every row above it. The thing you are trying to detect moves about a pound a week. The things you are not trying to detect move several pounds in a day. <strong>Day-to-day, the noise is somewhere between three and ten times the size of the signal.</strong> That single ratio explains basically every stalled-scale panic in existence."),
  ("callout", "A useful reframe: you are not weighing fat. You are weighing fat plus a large, fast, random number. Your entire job as a tracker is to average that random number away, and averaging takes time. There is no clever workaround, no better scale, and no time of day that removes it."),
  ("h2", "The formulas disagree, which is itself the point"),
  ("p", "Before the tracking starts, most people run a TDEE calculator. Total daily energy expenditure is basal metabolic rate multiplied by an activity factor, and there are several competing estimators for the BMR half."),
  ("formula", "Mifflin-St Jeor (men):    BMR = 10W + 6.25H - 5A + 5\nMifflin-St Jeor (women):  BMR = 10W + 6.25H - 5A - 161\n   W = kg, H = cm, A = years\n\nKatch-McArdle:            BMR = 370 + 21.6 × LBM(kg)\n   LBM = lean body mass, so it needs a body-fat estimate\n\nTDEE = BMR × activity factor (roughly 1.2 sedentary to 1.9 very active)"),
  ("p", "Run your own numbers through two or three of these and they will disagree, often by 150 to 300 calories at the BMR step alone. Then the activity multiplier, which is a single number standing in for everything from a desk job to a construction shift, adds far more spread than that. Two defensible choices of multiplier for the same person can differ by 500 calories a day."),
  ("p", "People treat that disagreement as a flaw in the calculators. It is not. It is the calculators being honest about a population-level regression applied to one individual. Mifflin-St Jeor was validated against measured resting energy expenditure and is generally the better default for most people; Katch-McArdle is better if you have a genuinely reliable body-fat number, and worse if you are guessing. Neither one knows about your thyroid, your job, your fidgeting, or the fact that you take the stairs."),
  ("p", "<strong>The correct use of a TDEE formula is as a starting hypothesis with a wide error bar, not an answer.</strong> Pick one, eat at that number consistently for two to three weeks, measure the trend, and let the observed trend correct the estimate. Your own data has an error bar too, but it is the only estimate that is actually about you."),
  ("h2", "Why one weigh-in carries almost no information"),
  ("p", "Take the noise table seriously for a second and the arithmetic gets stark. Suppose your true rate of loss is 1 pound a week, so about 0.14 lb a day, and the day-to-day noise has a spread of roughly plus or minus 2 pounds. The chance that today's number is higher than yesterday's, while you are losing fat perfectly steadily, is close to a coin flip."),
  ("p", "That is not a metaphor. If you weigh daily during a genuinely successful cut, a large fraction of individual days will be up on the day before. People who weigh once a week are drawing one sample from that same distribution and treating it as the week's result, which is worse, not better: a single Monday reading inherits all of Sunday's sodium and none of the averaging."),
  ("p", "So the rule is not \"weigh less often.\" It is <strong>weigh more often and look less often.</strong> More samples make the average better. Looking at each sample individually is what causes the damage."),
  ("h2", "The moving average is the actual measurement"),
  ("p", "There are two filters worth knowing, and the difference between them matters more than it sounds."),
  ("h3", "Weekly averages"),
  ("p", "Average all seven days of the week, then compare that average to the previous week's average. Simple, robust, and it collapses seven noisy samples into one number whose noise is roughly a third of a single day's. The weakness is latency: you find out about last week at the end of this week, and a Wednesday-to-Wednesday comparison can still be pulled around by one outlier day at either edge."),
  ("h3", "Exponentially weighted averages"),
  ("p", "An exponentially weighted moving average updates every day, weights recent days more heavily, and never needs you to wait for a week boundary. It is one line of arithmetic."),
  ("formula", "trend(today) = trend(yesterday) + k × (weight(today) - trend(yesterday))\n\nk = 0.1  →  smooth, slow, roughly a 2-3 week memory\nk = 0.25 →  responsive, noisier, roughly a 1 week memory\n\nStart with trend = your first weigh-in, then just iterate."),
  ("p", "This is the same idea as the Hacker's Diet trend line, and it is what most decent tracking apps compute under the hood whether or not they say so. With k = 0.1, a single 3-pound water spike moves the trend line by 0.3 pounds. The spike is visible and it does not lie to you."),
  ("p", "Either filter is fine. What is not fine is comparing raw daily numbers to each other, which is the default behaviour of every scale ever sold and the source of most of the misery."),
  ("h2", "How long before a trend means anything"),
  ("p", "The honest answer depends on how aggressive the deficit is, because the signal size scales with it while the noise does not."),
  ("table", (["Target rate", "Weekly signal", "Minimum wait before judging"],
             [["0.5 lb/week (≈250 cal/day)", "0.5 lb", "4 weeks. The signal is small enough that three weeks of noise can hide it entirely."],
              ["1 lb/week (≈500 cal/day)", "1 lb", "3 weeks. The usual case, and the usual answer."],
              ["1.5–2 lb/week (≈750–1000 cal/day)", "1.5–2 lb", "2 weeks. Larger signal, faster confirmation, worse adherence and more lean-mass cost."],
              ["Recomposition or maintenance", "≈ 0", "6+ weeks, and the scale is the wrong instrument. Use the tape and the lifts."]])),
  ("p", "Three weeks is the number most people should internalise. Not three days, not \"the scale did not move since Tuesday.\" <strong>Three consecutive weekly averages, or three weeks of a trend line, before you are allowed to conclude anything and change something.</strong>"),
  ("p", "There is one legitimate exception, and it is the start. The first week of any deficit typically shows a large drop — often 3 to 6 pounds — that is overwhelmingly glycogen and water, not fat. It is real weight and it is not real progress. The corresponding trap is at the end: coming out of a deficit produces a fast regain of that same water, which is not fat regain either, and which has convinced an enormous number of people that their diet failed at the exact moment it succeeded."),
  ("h2", "A blown week, in actual arithmetic"),
  ("p", "This is the part that gets skipped, and it is the part that decides whether a plan survives its first bad week. So do the numbers instead of the guilt."),
  ("p", "Say you are running a 500 calorie daily deficit and you have a genuinely terrible weekend: a restaurant meal, drinks, and a next-day recovery meal, adding up to roughly 3,000 calories above maintenance across two days. What happened?"),
  ("formula", "Planned week:   -500 × 7        = -3,500 cal  ≈ -1.0 lb\nActual week:    -500 × 5 + 3,000 = +500 cal  ≈ +0.14 lb\n\nNet damage:  about one week of progress, not one month.\nScale damage: possibly +4 to +6 lb the next morning."),
  ("p", "Two numbers, wildly different. The real cost is roughly one week erased. The scale cost looks like a month, because a high-carbohydrate, high-sodium weekend refills glycogen and pulls water in with it. Nearly all of that visible number is gone within four to seven days of returning to normal eating, with no additional effort and no compensating starvation required."),
  ("p", "The reason this matters is that people do not quit because of the 500 calories. They quit because of the 5 pounds, which was never fat. <strong>The bad week costs a week. The reaction to the bad week is what costs the plan.</strong>"),
  ("h3", "The recovery protocol, such as it is"),
  ("ol", [
   "Eat normally at the next meal. Not less, not a fast, not a punishment session on a treadmill. The arithmetic above does not support any of those and they reliably set up the next binge.",
   "Keep weighing. Skipping the weigh-in because you know it will be bad is how a one-week gap becomes a three-month gap. The number is data, not a verdict.",
   "Expect the trend line to be wrong for about a week and do not act on it. Your filter is doing exactly its job by absorbing the spike slowly.",
   "Do not change the deficit. A blown week is not evidence that the plan is too aggressive; it is evidence that one weekend happened. Change the plan only on three weeks of trend, per the table above.",
   "Write down what actually preceded it — sleep, hunger, an unplanned event, alcohol. One line. That log is the only thing that turns a bad week into information rather than a mood.",
  ]),
  ("h2", "Plateau triage"),
  ("p", "Four weeks of a genuinely flat trend line is a real plateau and deserves a real diagnosis. Work the list in order, because the answer is almost always found before the last item."),
  ("ol", [
   "<strong>Is it actually flat?</strong> Check the trend line, not the daily readings, and check four weeks rather than two. Most reported plateaus are three weeks long and turn out to be noise.",
   "<strong>Is the intake real?</strong> Tracked intake drifts upward silently: untracked oils, drinks, bites while cooking, weekend meals estimated instead of measured. Weigh food for one honest week before touching anything else. This finds the problem far more often than anything below it does.",
   "<strong>Has non-exercise activity dropped?</strong> Spontaneous movement falls in a deficit without anyone noticing. Step count is the cheapest available proxy, and a drop from 9,000 to 5,000 steps a day is a real, invisible reduction in expenditure.",
   "<strong>Is bodyweight lower than when you started?</strong> A smaller body needs fewer calories. A deficit calculated at 200 lb is a smaller deficit at 185 lb, and eventually it is no deficit at all. Recalculate every 10 to 15 pounds.",
   "<strong>Only then, adjust.</strong> Cut roughly 100 to 200 calories or add activity. Cutting 500 more because the number felt stuck is how people end up eating too little to sustain the plan.",
  ]),
  ("h2", "The measurements the scale cannot make"),
  ("p", "Body mass is one number describing a thing that has several dimensions, which is why it goes flat during recomposition even when the body is visibly changing. Keep two or three cheap secondary measurements so the scale is never the only witness."),
  ("ul", [
   "<strong>Waist circumference</strong>, measured at the navel, same time of day, once a week. It tracks abdominal fat better than mass does and it keeps moving during scale plateaus.",
   "<strong>Photos, monthly</strong>, same lighting, same position, same time of day. The single most convincing measurement over a long timeline and the one people skip because month one feels pointless. Month one is the whole reason it works in month six.",
   "<strong>Strength on two or three main lifts.</strong> Strength holding steady in a deficit is the best available field evidence that the mass leaving is mostly fat rather than muscle.",
   "<strong>A single pair of jeans.</strong> Unscientific, zero effort, and completely immune to sodium.",
  ]),
  ("h2", "The one thing you do not renegotiate"),
  ("p", "Everything above is about measurement, with one intake exception worth repeating here because it interacts with the noise directly: the protein floor. Common practical guidance sits around 0.7 to 1.0 grams per pound of target bodyweight. It protects lean mass in a deficit, and it is the most satiating macronutrient per calorie, which makes the bad weeks less likely in the first place."),
  ("p", "Treat protein as a hard floor and everything else as a target. When a week goes sideways, the protein floor is the thing you keep, because it is the thing that determines what kind of weight comes off. The rest of the deficit arithmetic — maintenance estimation, deficit sizing, macro split — is in <a href=\"/guides/cut-calorie-math.html\">the calorie arithmetic guide</a>."),
  ("h2", "The same problem, in a different domain"),
  ("p", "If this framing feels familiar it is because it is the same problem as evaluating a trading system, and the same mistakes show up in both. A single trade tells you nothing. A single week of results is inside the noise band. People change a working system after three bad samples, and they conclude a broken system works after three good ones. The fix in both places is identical: a defined sample size before any conclusion, a filter instead of a raw reading, and a written log so the decision is made from data rather than from how the last data point felt. That is written up for markets in <a href=\"/guides/trading-journal.html\">the trading journal guide</a>, and the arithmetic there is uncomfortably similar."),
  ("h2", "What this looks like day to day"),
  ("ol", [
   "Weigh every morning, after the bathroom, before food or drink, minimal clothing. Same conditions, every time.",
   "Log the number and then stop looking at it. The daily number is an input, not a result.",
   "Look at the trend line or the weekly average once a week, on a fixed day.",
   "Judge nothing before three weeks. Change nothing before three weeks.",
   "Keep the protein floor, keep lifting, keep a waist measurement and a monthly photo.",
   "When a week blows up, do the arithmetic instead of the guilt, then go back to step one tomorrow.",
  ]),
  ("p", "That is the whole method. It is unexciting on purpose, because the failure mode is never a missing technique — it is reacting to noise. I built <a href=\"/apps/cut/\">Cut</a> to do exactly this shape of tracking: weight in, trend out, no account, no server, nothing leaving the device. <a href=\"/apps/fire/\">Fire</a> handles the habit side, for the same reason: the daily behaviour is the input, and the scale is just the instrument reading it back."),
 ],
 "tools": [("/apps/cut/", "Cut", "offline weight tracker that computes the trend line for you — local-only, no signup."),
           ("/apps/fire/", "Fire", "daily ritual checklist for the behaviours the scale is measuring."),
           ("/guides/cut-calorie-math.html", "Calorie arithmetic", "the companion guide: maintenance, deficit size, and the protein floor.")],
 "faqs": [
  ("Should I weigh myself every day or once a week?", "Weigh daily and look weekly. More samples make the average more accurate, but reading each individual sample is what causes bad decisions. A once-a-week weigh-in is actually worse than daily weighing with a weekly average, because that single reading inherits all of the previous day's water and sodium noise with nothing to average it against."),
  ("How much can body weight fluctuate in a day?", "Several pounds, routinely. Glycogen and its bound water can swing 1 to 4 pounds, sodium and fluid balance 1 to 3, gut contents 1 to 3, and hard training another 1 to 3 through muscle water retention. Since fat loss at a 500 calorie deficit is only about a pound per week, the daily noise is commonly three to ten times larger than the signal."),
  ("What is a weight trend line and how do I calculate one?", "It is an exponentially weighted moving average of your daily weigh-ins: trend today equals trend yesterday plus k times the difference between today's weight and yesterday's trend, with k around 0.1. It updates every day, weights recent readings more heavily, and absorbs a 3-pound water spike as roughly a 0.3-pound move, so spikes stay visible without distorting the picture."),
  ("How long should I wait before deciding a diet is not working?", "Three weeks at a roughly 1 pound per week target, and four weeks at a slower rate, judged on trend or weekly averages rather than individual days. Below three weeks the noise band is wide enough to hide a working deficit completely, which is why most reported plateaus turn out to be nothing when the fourth week is added."),
  ("Why do TDEE calculators give different numbers?", "Because they are population-level regressions applied to one person, and they disagree at both steps. Mifflin-St Jeor and Katch-McArdle can differ by 150 to 300 calories at the BMR stage, and the activity multiplier adds far more spread than that. Use a formula as a starting hypothesis with a wide error bar, then let two to three weeks of your own trend data correct it."),
  ("How much damage does one bad weekend actually do?", "Far less than the scale suggests. Roughly 3,000 calories above plan across a weekend erases about one week of a 500-calorie-per-day deficit, while the next-morning scale reading might be 4 to 6 pounds higher because carbohydrate and sodium pulled water in. Most of that visible number is gone within four to seven days of normal eating."),
  ("What should I do after a blown week?", "Eat normally at the next meal, keep weighing, expect the trend to be wrong for about a week, and do not change the deficit. Compensatory fasting or punishment cardio is not supported by the arithmetic and reliably sets up the next binge. Write one line about what preceded it so the week becomes information instead of a mood."),
  ("What should I track when the scale stops moving?", "Waist circumference weekly at the same time of day, a monthly photo under the same conditions, and strength on two or three main lifts. During recomposition the scale can be genuinely flat while body composition changes, so mass is the wrong instrument and the tape and the lifts are the right ones."),
 ],
 "faq_cards": [
  ("Daily or weekly weigh-ins?", "Weigh daily and look weekly. More samples make the average more accurate, but reading each individual sample is what causes bad decisions. A once-a-week weigh-in is actually worse than daily weighing with a weekly average, because that single reading inherits all of the previous day's water and sodium noise with nothing to average it against."),
  ("How much does weight fluctuate?", "Several pounds, routinely. Glycogen and its bound water can swing 1 to 4 pounds, sodium and fluid balance 1 to 3, gut contents 1 to 3, and hard training another 1 to 3 through muscle water retention. Since fat loss at a 500 calorie deficit is only about a pound per week, the daily noise is commonly three to ten times larger than the signal."),
  ("What is a trend line?", "It is an exponentially weighted moving average of your daily weigh-ins: trend today equals trend yesterday plus k times the difference between today's weight and yesterday's trend, with k around 0.1. It updates every day, weights recent readings more heavily, and absorbs a 3-pound water spike as roughly a 0.3-pound move, so spikes stay visible without distorting the picture."),
  ("When can I say it is not working?", "Three weeks at a roughly 1 pound per week target, and four weeks at a slower rate, judged on trend or weekly averages rather than individual days. Below three weeks the noise band is wide enough to hide a working deficit completely, which is why most reported plateaus turn out to be nothing when the fourth week is added."),
  ("Why do TDEE calculators disagree?", "Because they are population-level regressions applied to one person, and they disagree at both steps. Mifflin-St Jeor and Katch-McArdle can differ by 150 to 300 calories at the BMR stage, and the activity multiplier adds far more spread than that. Use a formula as a starting hypothesis with a wide error bar, then let two to three weeks of your own trend data correct it."),
  ("What does one bad weekend cost?", "Far less than the scale suggests. Roughly 3,000 calories above plan across a weekend erases about one week of a 500-calorie-per-day deficit, while the next-morning scale reading might be 4 to 6 pounds higher because carbohydrate and sodium pulled water in. Most of that visible number is gone within four to seven days of normal eating."),
  ("How do I recover from a blown week?", "Eat normally at the next meal, keep weighing, expect the trend to be wrong for about a week, and do not change the deficit. Compensatory fasting or punishment cardio is not supported by the arithmetic and reliably sets up the next binge. Write one line about what preceded it so the week becomes information instead of a mood."),
  ("What if the scale is stuck?", "Waist circumference weekly at the same time of day, a monthly photo under the same conditions, and strength on two or three main lifts. During recomposition the scale can be genuinely flat while body composition changes, so mass is the wrong instrument and the tape and the lifts are the right ones."),
 ],
},

{
 "slug": "reading-a-scientific-paper",
 "title": "Reading a Scientific Paper as a Non-Researcher",
 "desc": "The order to read sections in, how to judge a sample size, what p-values and effect sizes actually mean, and how to spot a claim the data does not support.",
 "og_title": "Reading a Scientific Paper as a Non-Researcher",
 "og_desc": "Read it out of order, check the effect size before the p-value, and find the limitations section first.",
 "headline": "Reading a Scientific Paper When You Are Not a Researcher",
 "crumb": "Reading a Paper",
 "about": ["Research literacy", "Statistics", "Peer review", "Undergraduate research"],
 "eyebrow": "Guide · Career",
 "h1": "Read it out of order, and check the effect size first",
 "lead": "A paper is not written to be read front to back by someone outside the field. It is written to survive review by four specialists. Once you know which sections are load-bearing and which are ceremony, most papers become readable in twenty minutes.",
 "level": "Beginner",
 "nav": NAV_EDU,
 "body": [
  ("h2", "The problem is the format, not you"),
  ("p", "Papers are hard to read for a specific and non-obvious reason: the audience is not a curious outsider, it is a reviewer deciding whether to reject. Every section is optimised for that. The introduction exists partly to pre-empt \"this has been done before.\" The methods section exists to answer \"could this be replicated and did they do it properly.\" The related-work section is often as much about citing the right people as informing the reader."),
  ("p", "That means reading front to back is close to the worst possible order. You spend the first fifteen minutes on the two sections least likely to change your mind about anything, and you arrive at the numbers already tired."),
  ("p", "I have been on the writing side of this, as a co-author on a peer-reviewed paper accepted to SIGCSE TS 2026. What that experience mostly taught me is how much of a finished paper is shaped by anticipating objections, and how much genuinely useful information gets pushed into the two sections nobody reads: methods and limitations."),
  ("h2", "The order that actually works"),
  ("ol", [
   "<strong>Title and abstract.</strong> Two minutes. You are extracting one thing: what did they claim, and on whom. If the abstract does not tell you the population and the sample size, that is already a small signal.",
   "<strong>Figures and tables.</strong> Before any prose. The figures are the paper's actual results, and a good figure is legible without its section. Read the captions in full; captions are where authors state what a chart shows more precisely than the body text usually does.",
   "<strong>The limitations section.</strong> Yes, this early. It is usually near the end of the discussion, sometimes labelled \"threats to validity.\" It is the most honest paragraph in most papers and it tells you exactly how far the claim can be carried.",
   "<strong>Methods.</strong> Now that you know what was found and what the authors admit is shaky, methods becomes a targeted read: who were the participants, how were they assigned, what was measured, and what was compared against what.",
   "<strong>Results.</strong> Match every number in the results to a claim. This is where you check whether the effect sizes are meaningful, not just whether the p-values are small.",
   "<strong>Discussion and conclusion.</strong> Read last and read sceptically. This is where a modest finding most often gets promoted into a broad claim.",
   "<strong>Introduction and related work.</strong> Only if you need the field context. Frequently you do not.",
  ]),
  ("callout", "If you have five minutes and not twenty: abstract, figures, limitations. That triple tells you what was claimed, what was actually observed, and what the authors themselves say it does not prove. It is a startling amount of a paper for five minutes of work."),
  ("h2", "How to judge a sample size"),
  ("p", "There is no universal threshold, which is why \"n = 60, is that a lot?\" has no answer in isolation. The right question is whether the sample is large enough to detect an effect of the size the authors are looking for, and whether it is representative of the population the claim is about."),
  ("table", (["Question", "What a good answer looks like", "What should worry you"],
             [["How many participants, and in each condition?",
               "Stated plainly in the abstract or early methods, with the per-group split",
               "Only a total, with the group sizes buried or absent"],
              ["Was there a power analysis?",
               "A stated target effect size and the sample needed to detect it, decided before data collection",
               "No mention, especially alongside a barely-significant result"],
              ["Who are the participants?",
               "Described specifically: setting, background, recruitment method",
               "\"Undergraduates\" with a claim generalised to \"learners\""],
              ["How many dropped out?",
               "Reported, with a comparison of who left versus who stayed",
               "A final n noticeably smaller than the recruited n, unexplained"],
              ["How many outcomes were measured?",
               "A small number, ideally pre-registered",
               "Fifteen measures, one of which is significant and features in the title"]])),
  ("p", "A small sample is not automatically bad. A carefully instrumented study of 20 people can be more informative than a sloppy survey of 5,000, and in fields like computing education the constraint is usually access to real classrooms rather than laziness. What a small sample does mean is that <strong>only large effects will show up at all</strong>, so a small study reporting a small significant effect deserves more scrutiny than a small study reporting a large one."),
  ("p", "The subtler failure is representativeness. A sample drawn entirely from one university's introductory course is a fine basis for a claim about that population and a weak basis for a claim about students generally. Most overreach in papers happens at exactly this joint, and the limitations section usually admits it in one sentence that the abstract does not."),
  ("h2", "What a p-value actually means"),
  ("p", "The formal definition is genuinely awkward, so here it is precisely and then in plain terms."),
  ("formula", "p = P(observing data at least this extreme | the null hypothesis is true)\n\nIt is NOT:  the probability the null hypothesis is true\nIt is NOT:  the probability the result was a fluke\nIt is NOT:  a measure of how big or important the effect is"),
  ("p", "Plainly: a small p-value says \"if there were genuinely no effect here, data this striking would be unusual.\" That is a statement about surprise under an assumption, not a statement about truth, and definitely not a statement about magnitude."),
  ("p", "The 0.05 convention is a convention. It was never a law of nature, and treating it as a hard line produces two symmetric errors: dismissing p = 0.06 as nothing, and treating p = 0.04 as proof. Both readings ignore the number that actually matters, which is the effect size."),
  ("h3", "The traps worth recognising"),
  ("ul", [
   "<strong>Multiple comparisons.</strong> Test twenty independent things at p &lt; 0.05 and roughly one comes back significant by chance alone. If a paper reports many outcomes and highlights one, ask whether any correction (Bonferroni, Holm, false discovery rate) was applied.",
   "<strong>\"Trending toward significance.\"</strong> This phrase means the result was not significant. It is not wrong to report a non-significant trend, but it should not be doing load-bearing work in a conclusion.",
   "<strong>Outcome switching.</strong> A pre-registered study declares its primary outcome in advance. If the reported primary outcome differs from the registered one, the paper is reporting the winner of a search rather than a test.",
   "<strong>Subgroup mining.</strong> \"No overall effect, but a significant effect among first-year women in the evening section\" is a hypothesis for a future study, not a finding.",
   "<strong>Significance from sheer size.</strong> With a large enough n, a trivially small difference becomes statistically significant. Significance answers \"is it distinguishable from zero,\" not \"is it big enough to care about.\"",
  ]),
  ("h2", "Effect size is the number you actually wanted"),
  ("p", "An effect size says how big the difference is, in units that survive comparison across studies. For a difference between two group means, the standard measure is Cohen's d."),
  ("formula", "Cohen's d = (mean_A - mean_B) / pooled standard deviation\n\nRough conventions (and they are only conventions):\n  d ≈ 0.2   small\n  d ≈ 0.5   medium\n  d ≈ 0.8   large\n\nAlso common: r and R² for correlation, odds ratios for binary outcomes,\nand confidence intervals, which carry more information than any of them."),
  ("p", "The confidence interval deserves special attention because it does two jobs at once: it gives the estimate and it gives the uncertainty. An interval of [0.05, 0.90] and an interval of [0.44, 0.52] can have the same midpoint and mean entirely different things. And an interval that crosses zero is telling you the same thing a non-significant p-value would, but with the added and useful information of how large the effect could plausibly be in either direction."),
  ("p", "<strong>The practical rule: read the effect size and the interval first, and let the p-value be a footnote.</strong> A significant result with a tiny effect and a wide interval is a weaker finding than a non-significant result with a moderate effect in a small sample, even though the first one is the one that gets a headline."),
  ("h2", "A worked example from a paper I co-authored"),
  ("p", "Concrete beats abstract, and it is easier to be honest about a paper with my own name on it. The SIGCSE TS 2026 paper I co-authored studied bilingual coding as a support for computer science learners, with 60 participants."),
  ("p", "The paper reports statistically significant pre-to-post gains in programming confidence, computing identity, enjoyment, and motivation across those 60 participants, with novices gaining significantly more than experienced programmers. That is the real result and it is a good one."),
  ("p", "Now the part that a casual reader would get wrong. The obvious headline someone would want from a bilingual coding study is \"bilingual instruction beats English-only instruction.\" The paper does not support that. <strong>The bilingual-versus-English comparison produced a Cohen's d in the range of 0.25 to 0.40 and was not statistically significant.</strong> A d of 0.25 to 0.40 is a small-to-moderate effect in the direction you might hope for, and with this sample it is not distinguishable from no effect at all."),
  ("p", "Two useful lessons come out of that, and they generalise well beyond this paper:"),
  ("ul", [
   "<strong>A non-significant effect is not a zero effect.</strong> It means this study could not distinguish it from zero. A larger sample might; that is precisely why the effect size is reported alongside the null result rather than the finding being buried.",
   "<strong>The significant result and the interesting result are often different results.</strong> The significant finding here is about pre-to-post growth across the whole cohort. The comparison people care about is the one that came back inconclusive. Anyone reading only the abstract could easily blur those two into a claim the data does not make.",
  ]),
  ("p", "This is also a decent illustration of why exact numbers matter more than remembered impressions. A percentage figure attached to this study in casual retelling would be an invention, because the paper reports no percentage figures at all. If you cannot point to the number in the paper, do not repeat the number. The broader context of that work is in <a href=\"/guides/bilingual-coding-cs-education.html\">the bilingual coding guide</a>, and the paper is described on <a href=\"/research.html\">the research page</a>."),
  ("h2", "Spotting a claim the data does not support"),
  ("p", "Most overreach is not fraud. It is a chain of small, individually defensible steps that ends somewhere the evidence never went. These are the joints where the chain usually slips."),
  ("table", (["What the paper shows", "What the discussion says", "The gap"],
             [["A correlation in observational data",
               "\"X improves Y\"",
               "Causal language on non-causal data. Look for random assignment; without it, be suspicious of any verb implying causation."],
              ["An effect in one specific population",
               "\"Students benefit from…\"",
               "Generalisation past the sample. Check who was actually enrolled."],
              ["A short-term outcome, measured immediately",
               "\"Improves learning\"",
               "Durability was never measured. Post-tests taken minutes after an intervention frequently do not survive a delayed re-test."],
              ["A self-reported survey measure",
               "\"Increases ability\"",
               "Confidence and competence are different constructs, and interventions routinely move one without the other."],
              ["One significant outcome among many",
               "Headlined in the abstract",
               "Multiple comparisons. Ask what else was measured and did not make the abstract."],
              ["A statistically significant tiny difference",
               "\"Substantially better\"",
               "Significance mistaken for magnitude. Go find the effect size."]])),
  ("p", "One quick heuristic that catches a surprising share of this: <strong>read the abstract's final sentence and the limitations section back to back.</strong> They are written by the same authors about the same study, and when they disagree in tone, the limitations section is the one telling the truth."),
  ("h2", "What peer review actually catches"),
  ("p", "Having been through the process, the useful correction to most people's mental model is this: peer review is a check on <em>reasoning and reporting</em>, not a verification of the data. Reviewers do not re-run the study. They usually do not see the raw data at all."),
  ("table", (["Peer review reliably catches", "Peer review does not catch"],
             [["Claims not supported by the reported results",
               "Fabricated or mistaken data"],
              ["Missing methodological detail that blocks replication",
               "Whether the study replicates"],
              ["Inappropriate statistical tests for the design",
               "Analyses that were tried and abandoned before submission"],
              ["Unacknowledged limitations and threats to validity",
               "Whether the sample generalises in practice"],
              ["Missing related work and mis-stated prior findings",
               "Whether the effect matters in the real world"]])),
  ("p", "So \"peer reviewed\" means a few knowledgeable people agreed the argument follows from the reported evidence and that the paper is worth the field's attention. It does not mean true. Replication, not review, is what does that job, and it happens on a much longer timescale than publication does."),
  ("p", "Venue matters more than the phrase \"peer reviewed\" does. In computer science, top conferences are frequently the primary venue rather than journals, with acceptance rates and review processes that are public information. A preprint on arXiv has had no review at all, which is not disqualifying but is worth knowing before citing it. And any journal that solicits submissions by email with a fast fee-based turnaround should be treated as a marketing operation until proven otherwise."),
  ("h2", "Getting past the paywall, legitimately"),
  ("ul", [
   "<strong>Check arXiv and the author's own page first.</strong> Most venues permit an author-hosted preprint or accepted version, and authors post them.",
   "<strong>Use your institution.</strong> A university login usually covers the ACM Digital Library, IEEE Xplore, and the major publishers, and it works off campus through the library proxy.",
   "<strong>Look for an open-access flag.</strong> A growing share of papers are open by default, including via the ACM Open programme.",
   "<strong>Email the author.</strong> This works far more often than people expect. Authors are generally delighted that someone outside the field wants to read the paper, and sending a copy is entirely normal practice.",
  ]),
  ("h2", "A checklist for the next paper you open"),
  ("ol", [
   "What exactly is claimed, and about whom?",
   "How many participants, split how, and how many dropped out?",
   "Was assignment random? If not, treat every causal verb as a hypothesis.",
   "What is the effect size, and how wide is the confidence interval?",
   "How many outcomes were measured, and was any correction applied?",
   "What does the limitations section admit that the abstract does not?",
   "Does the conclusion stay inside the population that was actually studied?",
   "Has anyone replicated it, and if not, is it being cited as if they had?",
  ]),
  ("p", "That list takes a couple of minutes and it is most of what a reviewer does on a first pass. It will not make you a specialist in the field, and it does not need to. It is enough to tell a solid result from a stretched one, which is the entire practical skill. If you are heading in the other direction and want to be on the writing side, <a href=\"/guides/undergraduate-research.html\">the undergraduate research guide</a> covers how to get into a lab and what the first year actually looks like."),
  ("h2", "The same statistics, somewhere else entirely"),
  ("p", "Multiple comparisons, effect sizes, and confidence intervals are not academic trivia. They are the same machinery that decides whether a trading strategy is real or a coincidence found by testing hundreds of parameter combinations against the same data. The failure mode is identical, and it is written up in exactly those terms in <a href=\"/guides/backtest-overfitting.html\">the backtest overfitting guide</a>. If you understand why a paper that measured fifteen outcomes and reported one is weak evidence, you already understand why a strategy chosen from a thousand backtests is too."),
 ],
 "tools": [("/research.html", "Research", "the SIGCSE TS 2026 paper, and what the lab actually does."),
           ("/guides/undergraduate-research.html", "Undergraduate research guide", "how to get into a lab and what the first year looks like."),
           ("/guides/backtest-overfitting.html", "Backtest overfitting", "the same statistics, applied to trading strategies instead of studies.")],
 "faqs": [
  ("What order should you read a scientific paper in?", "Abstract, then figures and their captions, then the limitations section, then methods, then results, then the discussion, and the introduction only if you need field context. Reading front to back spends your freshest attention on the two sections least likely to change your mind. If you only have five minutes, read the abstract, the figures, and the limitations."),
  ("Is a sample size of 60 participants enough?", "It depends entirely on the effect being looked for and the population being claimed about. A small sample can only detect large effects, so a small study reporting a small significant result deserves more scrutiny than one reporting a large effect. Check whether a power analysis was done in advance and whether the participants represent the population in the conclusion."),
  ("What does a p-value actually mean?", "It is the probability of observing data at least this extreme if the null hypothesis were true. It is not the probability that the hypothesis is true, not the probability the result was a fluke, and not a measure of how large the effect is. A small p-value says data this striking would be unusual if there were no effect, which is a statement about surprise, not about magnitude."),
  ("What is the difference between statistical significance and effect size?", "Significance answers whether an effect is distinguishable from zero; effect size answers how big it is. With a large enough sample a trivial difference becomes significant, and in a small sample a meaningful effect can fail to reach significance. Read the effect size and its confidence interval first and treat the p-value as a footnote."),
  ("Does a non-significant result mean there is no effect?", "No. It means this study could not distinguish the effect from zero, which is a statement about the study's resolving power as much as about reality. One of the papers I co-authored found a Cohen's d of roughly 0.25 to 0.40 on a bilingual-versus-English comparison that was not statistically significant, which is a small-to-moderate effect a larger sample might have resolved."),
  ("How do you tell if a paper's claim goes beyond its data?", "Read the abstract's last sentence and the limitations section back to back. The usual gaps are causal language on observational data, generalising past the sample that was actually studied, treating an immediate post-test as evidence of durable learning, and confusing a self-reported confidence measure with measured ability."),
  ("What does peer review actually catch?", "It checks reasoning and reporting, not data. Reviewers catch claims that outrun the results, missing methodological detail, inappropriate statistical tests, and unacknowledged limitations. They do not re-run the study, usually never see the raw data, and cannot tell you whether the finding replicates. Peer reviewed means the argument survived scrutiny, not that the conclusion is true."),
  ("How can you read a paywalled paper legally?", "Check arXiv and the author's own website first, since most venues permit an author-hosted version. Use an institutional login through a university library proxy for the ACM Digital Library, IEEE Xplore, and the major publishers. Look for an open-access flag. Failing all of that, email the author, which works far more often than people expect."),
 ],
 "faq_cards": [
  ("What order do I read it in?", "Abstract, then figures and their captions, then the limitations section, then methods, then results, then the discussion, and the introduction only if you need field context. Reading front to back spends your freshest attention on the two sections least likely to change your mind. If you only have five minutes, read the abstract, the figures, and the limitations."),
  ("Is n = 60 enough?", "It depends entirely on the effect being looked for and the population being claimed about. A small sample can only detect large effects, so a small study reporting a small significant result deserves more scrutiny than one reporting a large effect. Check whether a power analysis was done in advance and whether the participants represent the population in the conclusion."),
  ("What is a p-value really?", "It is the probability of observing data at least this extreme if the null hypothesis were true. It is not the probability that the hypothesis is true, not the probability the result was a fluke, and not a measure of how large the effect is. A small p-value says data this striking would be unusual if there were no effect, which is a statement about surprise, not about magnitude."),
  ("Significance vs effect size?", "Significance answers whether an effect is distinguishable from zero; effect size answers how big it is. With a large enough sample a trivial difference becomes significant, and in a small sample a meaningful effect can fail to reach significance. Read the effect size and its confidence interval first and treat the p-value as a footnote."),
  ("Does non-significant mean no effect?", "No. It means this study could not distinguish the effect from zero, which is a statement about the study's resolving power as much as about reality. One of the papers I co-authored found a Cohen's d of roughly 0.25 to 0.40 on a bilingual-versus-English comparison that was not statistically significant, which is a small-to-moderate effect a larger sample might have resolved."),
  ("Is the claim bigger than the data?", "Read the abstract's last sentence and the limitations section back to back. The usual gaps are causal language on observational data, generalising past the sample that was actually studied, treating an immediate post-test as evidence of durable learning, and confusing a self-reported confidence measure with measured ability."),
  ("What does peer review catch?", "It checks reasoning and reporting, not data. Reviewers catch claims that outrun the results, missing methodological detail, inappropriate statistical tests, and unacknowledged limitations. They do not re-run the study, usually never see the raw data, and cannot tell you whether the finding replicates. Peer reviewed means the argument survived scrutiny, not that the conclusion is true."),
  ("How do I get past a paywall?", "Check arXiv and the author's own website first, since most venues permit an author-hosted version. Use an institutional login through a university library proxy for the ACM Digital Library, IEEE Xplore, and the major publishers. Look for an open-access flag. Failing all of that, email the author, which works far more often than people expect."),
 ],
},

{
 "slug": "technical-interview-study-system",
 "title": "How to Actually Study for a Technical Interview",
 "desc": "The study system, not the problem list: Leitner spaced repetition, how to review a solved problem, timeboxing, and a hint ladder for when you are stuck.",
 "og_title": "How to Actually Study for a Technical Interview",
 "og_desc": "Volume without review fails. Here is the Leitner schedule, the review protocol, the timebox, and the stuck ladder.",
 "headline": "How to Actually Study for a Technical Interview",
 "crumb": "Interview Study System",
 "about": ["Technical interviews", "Spaced repetition", "Deliberate practice", "Algorithms"],
 "eyebrow": "Guide · Career",
 "h1": "The schedule is the skill, not the problem count",
 "lead": "Most people preparing for technical interviews have a list of problems and no system for retaining them. Three months later the early problems are gone, the count looks impressive, and the interview goes badly for reasons that feel mysterious and are not.",
 "level": "Beginner",
 "nav": NAV_CAREER,
 "body": [
  ("h2", "Two different guides, on purpose"),
  ("p", "<a href=\"/guides/coding-interview-patterns.html\">The interview patterns guide</a> covers <em>what</em> to study: the ten recurring problem shapes, the recognition cues, and why tagging failures by pattern beats counting solves. This guide covers <em>how</em> to study, which is a separate problem with separate failure modes. If you have never seen the pattern taxonomy, start there and come back."),
  ("h2", "Why volume without review reliably fails"),
  ("p", "The default plan is a list and a streak: solve a problem a day, keep going, feel prepared. It fails for a reason that has nothing to do with effort. Memory for a solved problem decays on a curve, and the curve is steeper than anyone expects. A problem you solved cleanly in March, with no intervening contact, is frequently a blank page in June. Not \"a bit rusty.\" Blank."),
  ("p", "So the person who solved 300 problems over four months and never revisited one has not banked 300 problems. They have banked whatever survives from the last few weeks, plus a general sense of familiarity that evaporates the moment a whiteboard is involved. The count is real and the retention is not."),
  ("p", "The second failure is subtler and worse, because it feels like studying. Reading a solution and thinking \"yes, that makes sense\" produces a strong feeling of understanding and almost no retrievable memory. This is the fluency illusion: comprehension while reading is not the same operation as generation from a blank page, and only the second one is what an interview tests. <strong>If you did not produce it yourself, you did not learn it, no matter how clearly you followed it.</strong>"),
  ("p", "Both failures have the same fix, which is uncomfortable and cheap: spend a substantial fraction of your study time re-solving things you have already solved, from memory, on a schedule."),
  ("h2", "The Leitner system, operationally"),
  ("p", "Leitner is the simplest workable implementation of spaced repetition. Items live in numbered boxes; each box has a review interval; a clean recall promotes an item one box, a failure sends it back to box one. That is the whole algorithm and it needs no software."),
  ("table", (["Box", "Review interval", "Meaning", "On success / on failure"],
             [["1", "1 day", "Failed recently, or never solved unaided", "→ box 2 / stays in box 1"],
              ["2", "3 days", "Solved with a hint", "→ box 3 / back to box 1"],
              ["3", "1 week", "Solved unaided but slowly", "→ box 4 / back to box 1"],
              ["4", "3 weeks", "Solved unaided and fluently", "→ box 5 / back to box 2"],
              ["5", "8 weeks", "Retired to maintenance", "stays in box 5 / back to box 2"]])),
  ("p", "Two details do most of the work and both get skipped."),
  ("p", "<strong>A failure demotes hard, not gently.</strong> From boxes 1 through 3, a failure goes all the way back to box one. That is the mechanism that concentrates your time on exactly the material you cannot do, which is the only material worth studying. A system that demotes by one box lets weak items drift forever."),
  ("p", "<strong>Box one has a size limit.</strong> If box one holds forty items, you are not studying, you are drowning, and you will start skipping reviews, which breaks the whole system. Cap it at around ten. When it is full, you do not add new problems that day. New material waits until the backlog clears. This rule feels like it slows you down and it is the single highest-leverage constraint in the system."),
  ("h3", "What is actually on a card"),
  ("p", "This is where most people implement it wrong. The card is not the problem statement, because re-solving a full problem takes 30 minutes and you cannot review 15 of those in a session. The card is the retrievable unit."),
  ("formula", "Front:  the recognition cue\n        \"Contiguous subarray, longest satisfying a condition\"\n\nBack:   1. pattern name           sliding window\n        2. the template, written from memory, not pasted\n        3. the complexity target   O(n)\n        4. the pitfall that got you  \"shrink condition ran before the\n                                      update, off-by-one on the answer\"\n\nReview = write 2 from a blank page in under 5 minutes, then diff."),
  ("p", "With cards shaped like that, a review is five minutes and a session can clear ten to fifteen of them. You periodically re-solve a full problem end to end, but that is a different activity with a different budget, not your review mechanism."),
  ("h3", "Implementing it without buying anything"),
  ("ul", [
   "<strong>Index cards and five physical boxes.</strong> Genuinely fine, and the tactile version has a compliance advantage most people underrate.",
   "<strong>A spreadsheet.</strong> Columns: cue, pattern, box, last reviewed, next due. Sort by due date. That is the entire application.",
   "<strong>Anki.</strong> Free on desktop and Android, uses a more sophisticated scheduler than Leitner, and works well if you already use it. It is not required.",
   "<strong>A script and a text file.</strong> I ended up writing a small drill runner for my own prep with problems tagged by pattern and Leitner boxes over a plain file, mostly because the review step needed to be one command with no friction. The tooling matters far less than doing the reviews.",
  ]),
  ("h2", "How to review a solved problem"),
  ("p", "\"Review\" usually means re-reading an old solution, nodding, and closing the tab. That produces the fluency illusion described above and close to zero retention. Here is a protocol that takes ten minutes and actually works."),
  ("ol", [
   "<strong>Read only the cue, then look away.</strong> Name the pattern and the complexity target out loud before anything else. If you cannot, that is the failure and the card goes to box one. Stop here and re-learn it rather than pushing through.",
   "<strong>Write the template from a blank page.</strong> Not the full problem solution, the canonical implementation of the pattern. Handwritten or in an editor with autocomplete off. This is the actual retrieval event, and everything else in this list is support for it.",
   "<strong>Diff it against your previous solution.</strong> Not to see if it looks similar, but to find every place they differ. Differences are where your memory is reconstructing rather than recalling, and that is exactly what will break under pressure.",
   "<strong>Say the invariant out loud.</strong> One sentence: what is true at every step of the loop. \"The window always contains at most k distinct characters.\" If you cannot state the invariant, you have memorised syntax rather than the idea, and syntax does not transfer to a variant.",
   "<strong>Name the edge case that would break it.</strong> Empty input, a single element, all duplicates, integer overflow, a cycle. One is enough. This is the step that separates people who pass from people who nearly pass.",
   "<strong>Write one line in the log.</strong> What broke, and where — recognition, approach, implementation, or edge cases. Those four locations need four different fixes, and by the end of a month the log tells you what to work on without any guessing.",
  ]),
  ("callout", "The diff step is the one to protect when time is short. A template you can nearly write is worth much less than one you can write exactly, and \"nearly\" is invisible until you compare the two side by side. Most people who feel prepared and then blank in an interview were living in the gap between nearly and exactly."),
  ("h2", "Timeboxing, and what to do when the box expires"),
  ("p", "Unbounded struggle is the most common way study time gets wasted. Ninety minutes on one problem feels like commitment and mostly produces frustration plus one data point. A timebox converts the same ninety minutes into three problems and three diagnoses."),
  ("table", (["Phase", "Budget", "What must exist when the timer ends"],
             [["Understand", "0–5 min", "The input shape, the output, and two examples worked by hand"],
              ["Approach", "5–15 min", "A named pattern and a complexity target, said out loud"],
              ["Implement", "15–35 min", "Working code, or a specific known blocker"],
              ["Verify", "35–45 min", "Edge cases walked manually, complexity stated"],
              ["Hard stop", "45 min", "Escalate to the hint ladder — do not extend the timer"]])),
  ("p", "The approach phase is the one to enforce ruthlessly. Fifteen minutes with no named pattern means the problem is currently above your level, and the useful move is to get a hint and turn it into a study item, not to spend another forty minutes rediscovering the pattern by brute force. <strong>An interview gives you about 35 minutes. Practising in unbounded time trains a skill you will not be allowed to use.</strong>"),
  ("h2", "The stuck ladder"),
  ("p", "When the timer expires, escalate in the smallest possible steps. The goal is to take the least amount of help that unblocks you, because every rung you climb without help is a rung you can climb alone next time."),
  ("ol", [
   "<strong>Re-read the constraints.</strong> If n is up to 10^5, an O(n²) approach is not intended, and that observation alone identifies the pattern surprisingly often.",
   "<strong>Say the brute force out loud, then ask what it repeats.</strong> Nearly every optimisation is the elimination of repeated work. Naming the repetition names the data structure.",
   "<strong>Do a small case entirely by hand.</strong> Four or five elements, on paper. The mechanism you use by hand is usually the algorithm, and people skip this step because it feels beneath them.",
   "<strong>Ask what has to stay true.</strong> The invariant question again. Being unable to answer it usually means the state you are tracking is wrong, not that the code is wrong.",
   "<strong>Look at the tags only.</strong> Not the editorial, the tags. Knowing it is a heap problem and finishing it yourself is worth vastly more than reading the solution.",
   "<strong>Read only the first sentence of the editorial.</strong> Then close it and try again. This is the highest-value rung on the ladder and almost nobody stops there.",
   "<strong>Read the full approach, close it, implement from memory.</strong> Never copy code. If you cannot implement it after reading the approach, you did not understand it, and copying it will hide that fact from you.",
   "<strong>Write the card.</strong> Mandatory. A problem you needed help on and did not turn into a card is a problem you will need help on again in six weeks.",
  ]),
  ("h2", "A session template"),
  ("p", "Ninety minutes, in this order, every time. The order matters more than the durations."),
  ("ol", [
   "<strong>0–20 min, due reviews.</strong> Clear whatever the box schedule says is due. Reviews come first because if they come last they do not happen.",
   "<strong>20–35 min, recognition drills.</strong> Read problem statements, name the pattern and the complexity, do not implement. Ten to fifteen of these in fifteen minutes. This trains the step interviews test first and it is absurdly cheap.",
   "<strong>35–80 min, one or two timed solves.</strong> Full timebox, out loud, from a blank page.",
   "<strong>80–90 min, write the cards and the log lines.</strong> Non-negotiable. This is the step that makes today's work exist next month.",
  ]),
  ("p", "If you only have thirty minutes, do the first block and stop. Twenty minutes of reviews with no new problem beats a new problem with no reviews, every single time, and the fact that it feels like less progress is exactly why people get this backwards."),
  ("h2", "A schedule that fits a semester"),
  ("table", (["Phase", "Weeks", "Focus", "The honest signal you are ready to move on"],
             [["Foundations", "1–2", "Complexity analysis, the language's data structures cold, two or three patterns", "You can state the complexity of any built-in operation you use without checking"],
              ["Pattern acquisition", "3–6", "One new pattern per week; template written from memory; deck fills up", "Box one clears most days without a backlog"],
              ["Mixed practice", "7–9", "Random problems across all patterns, no advance warning of the pattern", "Unaided first-attempt rate above roughly two thirds on mixed sets"],
              ["Interview simulation", "10–12", "Timed, verbal, with another person, plus behavioural answers", "You can talk continuously through a solve without losing the thread"]])),
  ("p", "The transition from phase two to phase three is where most preparation quietly breaks. Studying one pattern per week means every problem that week arrives pre-labelled, and pattern recognition is never tested. Mixed practice removes the label, performance drops sharply, and that drop is the honest measurement. It is supposed to be uncomfortable. It is also the closest thing to the real conditions you will get before the real conditions."),
  ("h2", "Talking while you think"),
  ("p", "Interviews are verbal, and silence reads as being stuck even when it is not. This is a separate skill from solving and it degrades solving performance the first several times you attempt both at once, which is precisely why it needs its own practice."),
  ("ul", [
   "<strong>Solve out loud, alone, from the beginning.</strong> Narrate the four approach questions every time until it is automatic.",
   "<strong>Record one solve a week and watch it back.</strong> Uncomfortable and unreasonably effective. You will find long silent stretches you had no idea were there.",
   "<strong>Do real mocks with a person.</strong> Peers are free; interviewing another student is as instructive as being interviewed. The pressure of another human being present is the variable that no amount of solo practice reproduces.",
   "<strong>Practise the recovery script.</strong> \"Let me restate what I have, then try a different angle\" is a sentence worth having ready, because the moment you need it is the moment you are least able to compose it.",
  ]),
  ("h2", "What to measure"),
  ("p", "Total problems solved is the metric that feels like progress and measures almost nothing. Three alternatives that actually track readiness:"),
  ("ul", [
   "<strong>Due-card clear rate.</strong> The share of scheduled reviews you actually complete. Below about 80 percent, the schedule is too aggressive and everything downstream is unreliable.",
   "<strong>Unaided first-attempt rate, by pattern.</strong> Computed per pattern, not overall, because the overall number hides the one pattern that will end the interview.",
   "<strong>Median time to a correct named approach.</strong> Under five minutes is a strong signal. This is the number that most directly predicts interview performance, and it is the one nobody tracks.",
  ]),
  ("h2", "The week before"),
  ("ol", [
   "Stop adding new material. Nothing learned in the final week will be retrievable under pressure anyway, and the attempt costs you review time.",
   "Clear the deck. Every box, once, even the eight-week ones.",
   "Re-write every template once from memory, in one sitting. It takes about an hour and it is the highest-value hour of the whole final week.",
   "Two full mocks, with a person, at the actual interview time of day.",
   "Prepare the non-algorithmic half: the project walkthrough, the behavioural answers, the questions you ask them. A strong solve with a vague project story is still a mixed signal, and <a href=\"/guides/portfolio-that-gets-interviews.html\">the portfolio guide</a> covers how to make that half land.",
   "Sleep. Genuinely load-bearing, and the first thing people trade away in the final 48 hours.",
  ]),
  ("h2", "The uncomfortable summary"),
  ("p", "The system is not clever. Review before new material, cap the backlog, write templates from a blank page instead of reading them, timebox everything, escalate in the smallest steps when stuck, and measure per-pattern rather than in total. None of that is a secret and almost nobody does it, because every part of it feels slower than grinding through a fresh problem list."),
  ("p", "It is slower per week and much faster per month. That trade is the entire point, and it is the same trade in every skill worth having. Getting to the interview in the first place is a separate pipeline problem, handled in <a href=\"/guides/ats-resume.html\">the resume guide</a> and tracked in <a href=\"/apply.html\">Apply OS</a>; the international-student timing and sponsorship layer is in <a href=\"/guides/swe-internship-international-student.html\">the internship guide</a>."),
 ],
 "tools": [("/guides/coding-interview-patterns.html", "Interview patterns", "the companion guide: what to study, and the ten recurring problem shapes."),
           ("/apply.html", "Apply OS", "application pipeline and deadline tracking, free and browser-only."),
           ("/guides/portfolio-that-gets-interviews.html", "Portfolio guide", "the non-algorithmic half of the loop: projects that survive a walkthrough.")],
 "faqs": [
  ("Why does solving lots of problems not work?", "Because memory for a solved problem decays steeply without review, so a large solved count mostly measures what you did in the last few weeks. The second reason is the fluency illusion: reading a solution and understanding it feels like learning but produces almost no retrievable memory, since comprehension while reading is a different operation from generating a solution from a blank page."),
  ("What is the Leitner system and how do you use it for coding?", "Items live in numbered boxes with review intervals of roughly 1 day, 3 days, 1 week, 3 weeks, and 8 weeks. A clean recall promotes an item one box and a failure sends it back to box one. For coding, the card is not the whole problem but the recognition cue on the front and the pattern name, template, complexity target, and your specific pitfall on the back."),
  ("How do you review a coding problem you already solved?", "Read only the cue and name the pattern and complexity from memory, write the template from a blank page with autocomplete off, then diff it against your previous solution and investigate every difference. Then state the loop invariant out loud, name one edge case that would break it, and log where the attempt broke. About ten minutes per problem."),
  ("How long should you spend on a problem before looking at the solution?", "Around 45 minutes total, split as five minutes to understand, ten to name an approach, twenty to implement, and ten to verify. If fifteen minutes pass with no named pattern, the problem is above your current level and the useful move is to take a hint and turn it into a study item rather than rediscovering the pattern by brute force."),
  ("What should you do when you are stuck on a problem?", "Escalate in the smallest steps: re-read the constraints, say the brute force out loud and ask what it repeats, work a five-element case by hand, ask what invariant must hold, then look at the tags only, then read one sentence of the editorial and close it. Never copy code, and always turn the problem into a card afterwards."),
  ("How much of a study session should be review versus new problems?", "Review first, always, taking roughly the first 20 minutes of a 90-minute session, followed by recognition drills and one or two timed solves. If you only have 30 minutes, do the reviews and skip the new problem. Reviews scheduled last do not happen, which is the most common way a spaced repetition system quietly dies."),
  ("How long does it take to prepare for technical interviews?", "A workable structure is 10 to 12 weeks: two weeks on complexity and data structures, four on acquiring patterns one per week, three on mixed practice with no advance label, and two to three on timed verbal mocks. The phase-two to phase-three transition is where performance visibly drops, and that drop is the honest measurement of pattern recognition."),
  ("What should you measure instead of problems solved?", "Due-card clear rate, which should stay above roughly 80 percent or the schedule is too aggressive; unaided first-attempt rate computed per pattern rather than overall; and median time to a correct named approach, where under five minutes is a strong signal. That last number predicts interview performance better than any total does."),
 ],
 "faq_cards": [
  ("Why doesn't volume work?", "Because memory for a solved problem decays steeply without review, so a large solved count mostly measures what you did in the last few weeks. The second reason is the fluency illusion: reading a solution and understanding it feels like learning but produces almost no retrievable memory, since comprehension while reading is a different operation from generating a solution from a blank page."),
  ("What is the Leitner system?", "Items live in numbered boxes with review intervals of roughly 1 day, 3 days, 1 week, 3 weeks, and 8 weeks. A clean recall promotes an item one box and a failure sends it back to box one. For coding, the card is not the whole problem but the recognition cue on the front and the pattern name, template, complexity target, and your specific pitfall on the back."),
  ("How do I review a solved problem?", "Read only the cue and name the pattern and complexity from memory, write the template from a blank page with autocomplete off, then diff it against your previous solution and investigate every difference. Then state the loop invariant out loud, name one edge case that would break it, and log where the attempt broke. About ten minutes per problem."),
  ("How long before I look at the solution?", "Around 45 minutes total, split as five minutes to understand, ten to name an approach, twenty to implement, and ten to verify. If fifteen minutes pass with no named pattern, the problem is above your current level and the useful move is to take a hint and turn it into a study item rather than rediscovering the pattern by brute force."),
  ("What do I do when stuck?", "Escalate in the smallest steps: re-read the constraints, say the brute force out loud and ask what it repeats, work a five-element case by hand, ask what invariant must hold, then look at the tags only, then read one sentence of the editorial and close it. Never copy code, and always turn the problem into a card afterwards."),
  ("Review or new problems?", "Review first, always, taking roughly the first 20 minutes of a 90-minute session, followed by recognition drills and one or two timed solves. If you only have 30 minutes, do the reviews and skip the new problem. Reviews scheduled last do not happen, which is the most common way a spaced repetition system quietly dies."),
  ("How many weeks of prep?", "A workable structure is 10 to 12 weeks: two weeks on complexity and data structures, four on acquiring patterns one per week, three on mixed practice with no advance label, and two to three on timed verbal mocks. The phase-two to phase-three transition is where performance visibly drops, and that drop is the honest measurement of pattern recognition."),
  ("What should I measure?", "Due-card clear rate, which should stay above roughly 80 percent or the schedule is too aggressive; unaided first-attempt rate computed per pattern rather than overall; and median time to a correct named approach, where under five minutes is a strong signal. That last number predicts interview performance better than any total does."),
 ],
},

]
