"""Glossary cluster: Freight. Data only; rendering lives in engine.py."""

CLUSTER = {
    "order": 7,
    "slug": "freight",
    "short_name": "Freight",
    "set_name": "Freight Glossary",
    "title": "Freight Glossary: Broker, Carrier, BOL, Detention and More",
    "desc": "Plain definitions of freight brokerage terms: broker vs carrier vs shipper, MC and DOT numbers, BOL, POD, LTL, FTL, detention, demurrage, factoring.",
    "og_title": "Freight Glossary: Broker, Carrier, BOL, Detention and More",
    "og_desc": "14 freight terms defined precisely, with the misconceptions and mechanics that matter in a claim or an audit.",
    "crumb": "Freight",
    "about": ["Freight brokerage", "Trucking operations", "Logistics terminology"],
    "eyebrow": "Glossary · Freight",
    "h1": "Freight terms, defined the way they show up on an invoice",
    "lead": "Freight vocabulary is full of words that sound interchangeable and are not. Getting <a href=\"#detention\">detention</a> and <a href=\"#demurrage\">demurrage</a> backwards, or treating an <a href=\"#mc-number\">MC number</a> as proof of anything, is how a load turns into a dispute.",
    "card_title": "Freight",
    "card_desc": "Broker, carrier, and shipper roles, MC and DOT numbers, BOL and POD, LTL vs FTL, detention vs demurrage, and factoring.",
    "intro": [
        ("p", "This set covers the vocabulary that shows up on a rate confirmation, a bill of lading, and an accessorial invoice, defined the way it actually gets used rather than the way a dictionary would phrase it. Several of these terms get confused with each other constantly, and the confusion is not cosmetic: billing demurrage when the contract says detention gets an invoice rejected, and treating a DOT number as authority to haul for hire can get a load covered by a carrier that was never allowed to take it."),
        ("callout", "Regulatory requirements, authority types, and liability rules differ by jurisdiction, by mode, and by the specific contract in front of you. The definitions here describe how these terms operate in practice, not legal advice. Verify anything load-bearing against FMCSA, the relevant tariff, or your own counsel before it becomes policy."),
        ("p", "The free <a href=\"/freight-tools.html\">freight calculators</a> (rate per mile, deadhead, detention, margin) put several of these terms into arithmetic, and <a href=\"/freightdesk.html\">FreightDesk</a> is built around the operational side of a few of them: watching insurance expiry, matching accessorials to invoices, and chasing the paperwork a claim depends on."),
    ],
    "terms": [
        {
            "slug": "broker-carrier-shipper",
            "term": "Broker vs carrier vs shipper",
            "short": "A shipper owns and tenders freight, a carrier physically transports it using its own or leased equipment, and a broker arranges transportation between the two without ever taking possession of the cargo.",
            "body": [
                ("p", "These three roles are defined by what each party does to the freight, not by company size or how the paperwork reads. The shipper is the party with goods that need to move: it owns or controls the cargo and is the one tendering it for transport. The carrier is the party that physically hauls it, which means it holds the truck (or vessel, or railcar), the driver, and the insurance that covers the freight and the equipment while it is in motion. The broker sits between them, arranging the transportation, negotiating the rate, and often handling the paperwork, but never taking possession of the goods and never operating the equipment that moves them."),
                ("p", "The distinction matters most when something goes wrong. A carrier's liability for cargo loss or damage runs under a different framework than a broker's, and a broker who never touches the freight is generally not liable for cargo damage the way a carrier is, though negligent-selection claims (choosing an obviously unfit carrier) are the exception brokers actually get sued over. That is a large part of why <a href=\"/guides/carrier-vetting-checklist.html\">carrier vetting</a> exists as a formal process rather than a habit: the broker's real exposure is picking the wrong carrier, not the freight itself."),
                ("p", "Acting as a broker is not something any company can decide to do informally. Broker authority is its own registration with FMCSA, separate from carrier authority, and it requires posting a surety bond in an amount set by federal rule (verify the current figure directly with FMCSA rather than trusting a secondhand number). Some entities hold both carrier and broker authority at once, which is legal, but it is also the exact setup that produces double-brokering: a load contracted to a carrier gets quietly re-brokered to a third party under that same entity's broker authority, and the party that actually hauls it may never see the rate you agreed to."),
                ("p", "A fourth role, the <strong>freight forwarder</strong>, is easy to fold into this by mistake. A forwarder consolidates shipments and takes on carrier-like responsibility for the cargo (issuing its own bill of lading, in many cases) without owning the trucks that ultimately move it, which puts it operationally between a broker and a carrier rather than cleanly matching either definition."),
            ],
            "example": "A furniture manufacturer (shipper) needs 40 pallets moved from its warehouse to a distributor. It calls a brokerage, which finds a trucking company with an available dry van and books the load. The trucking company (carrier) dispatches the truck, hauls the freight, and is liable for it in transit; the brokerage never touches a pallet and is not the party whose insurance covers cargo damage.",
            "misconception": "People assume a company with a DOT number and a truck in the yard is automatically a carrier for hire on every load it accepts, and that a broker who \"just found the truck\" carries no risk if that truck turns out to be unfit. Both assumptions are wrong: authority type is specific, and broker liability for negligent carrier selection is real.",
            "guide": ("/guides/freight-broker-margin.html", "Freight broker margin guide"),
            "see": ["mc-number", "dot-number", "bol", "factoring"],
        },
        {
            "slug": "mc-number",
            "term": "MC number",
            "aka": ["Motor carrier number", "Operating authority number"],
            "short": "An MC number is the FMCSA-issued operating authority that grants a company legal permission to transport regulated commodities or passengers for hire in interstate commerce.",
            "body": [
                ("p", "An MC number is not an identifier the way a DOT number is; it is a grant of permission. FMCSA issues it after a company applies for operating authority, and the authority comes in distinct types: property (general freight), household goods, passenger, and broker authority among them. Holding one type does not imply another. A company authorized to move household goods is not authorized to haul your dry van of packaging film, and a carrier with property authority is not automatically authorized to broker loads, even though some entities hold both grants at once."),
                ("p", "The number itself is cheap to look up and easy to treat as sufficient verification, which is the mistake. \"The MC number came back active\" confirms that authority exists and has not been revoked; it does not confirm the authority type matches the freight, that insurance is currently valid, that the safety record is acceptable, or that the entity contacting you is the one the number actually belongs to. Pulling the FMCSA record and reading past the status field is the whole job."),
                ("p", "Authority can also be pending revocation while still showing active, most often because an insurance filing lapsed and the clock on a cure period is running. A carrier can look clean today and be gone in thirty days for a reason that was already visible in the record if someone had read the pending-actions field instead of just the status line."),
            ],
            "example": "A dispatcher sourcing a last-minute reefer load pulls up a carrier's MC number and sees \"active.\" A closer read of the FMCSA record shows the authority was granted for household goods only, three weeks ago, with no property authority on file, meaning that carrier is not legally allowed to haul the reefer load at all.",
            "misconception": "That an MC number existing and reading \"active\" is itself a verification. It confirms authority was granted and has not (yet) been pulled; it says nothing about authority type, insurance currency, or whether the party on the phone is who the record says they are.",
            "guide": ("/guides/carrier-vetting-checklist.html", "Carrier vetting checklist"),
            "see": ["dot-number", "broker-carrier-shipper"],
        },
        {
            "slug": "dot-number",
            "term": "DOT number",
            "aka": ["USDOT number"],
            "short": "A USDOT number is a unique identifier the federal government assigns to a company that operates commercial motor vehicles, used to track its safety records, inspections, and compliance history.",
            "body": [
                ("p", "A USDOT number identifies a company for safety-oversight purposes. Any business operating commercial motor vehicles above certain weight, passenger-count, or hazmat thresholds in interstate commerce needs one, and FMCSA uses it to attach inspection results, crash reports, and compliance-review outcomes to that entity over time. It is the number the SMS and CSA safety data is filed under."),
                ("p", "The distinction that trips people up: a DOT number is about being tracked for safety, while an MC number is about being permitted to haul for hire. A company can hold a DOT number and never obtain operating authority at all, for example a private fleet moving only its own company's goods, which needs no MC number because it is not for-hire transportation. The reverse also happens: a fresh-looking MC number sitting on a very old DOT number is a pattern worth a second look, since it can mean an existing entity with a rough safety history recently acquired new operating authority under the same registration."),
                ("p", "Not every entity with a DOT number holds for-hire authority, and not every authority type is the same grant. Property, household goods, and passenger authority are separate approvals under the same broader system, so confirming a DOT number is registered tells you a company exists and is tracked; it does not tell you what, or whether, it is authorized to haul."),
            ],
            "example": "A private grocery chain runs its own delivery trucks between warehouses and stores. It has a USDOT number because its trucks are commercial motor vehicles subject to safety oversight, but it has no MC number because it never transports goods for hire, only its own.",
            "misconception": "Conflating a DOT number with authority to operate for hire. A DOT number is a safety-tracking identifier; the MC number is the separate, specific grant of for-hire authority, and a company can have one without the other.",
            "guide": ("/guides/carrier-vetting-checklist.html", "Carrier vetting checklist"),
            "see": ["mc-number", "broker-carrier-shipper"],
        },
        {
            "slug": "bol",
            "term": "Bill of lading (BOL)",
            "aka": ["BOL", "Waybill"],
            "short": "A bill of lading is the shipping document that serves as a receipt for the goods tendered, evidence of the contract of carriage between shipper and carrier, and in negotiable form, a document of title to the cargo.",
            "body": [
                ("p", "A BOL does three separate jobs, and most of the confusion around it comes from treating it as just a shipping label when it is actually performing all three at once. First, it is a <strong>receipt</strong>: the carrier's acknowledgment that it took possession of a described quantity and condition of goods at a specific place and time. Second, it is <strong>evidence of the contract of carriage</strong>, referencing or incorporating the terms under which the carrier agreed to move the freight. Third, in its negotiable form, it can function as a <strong>document of title</strong>, meaning possession of the properly endorsed document controls the right to the goods, which is why ocean and some rail shipments rely on it for exactly that purpose. Most domestic truckload BOLs are straight (non-negotiable) and function mainly as receipt and contract evidence rather than title documents."),
                ("p", "The receipt function is where BOLs earn their keep in a dispute. A BOL signed clean at pickup and signed clean at delivery, with no exceptions noted, is strong evidence the freight arrived in the same condition it left in. The moment a driver or receiver writes an exception, such as damaged pallet count or a torn shrink wrap, the document flips from routine paperwork into the single most important piece of evidence in whatever claim follows. This is the mechanical reason a blank exceptions field is not a good sign; it can mean nothing happened, or it can mean nobody was paying attention when something did."),
                ("p", "A BOL is written by the shipper or generated from the shipper's tender information, describes the commodity, weight, and piece count, states who is responsible for freight charges (prepaid or collect), and often states the released or declared value that governs the carrier's maximum liability. It is a per-load document, distinct from the rate confirmation, which sets the commercial terms (rate, free time, accessorial handling) that govern the relationship between broker and carrier for that trip."),
            ],
            "example": "A driver picks up 20 pallets and signs the BOL without noting any exceptions. At delivery, three pallets show visible water damage. The receiver writes \"3 pallets water damaged\" on the BOL and signs it. That single annotation is what turns the claim from a dispute about what happened into a documented fact about when the damage was already present.",
            "misconception": "That the BOL is just a packing slip. It is simultaneously a receipt, contract evidence, and in negotiable form a title document, and the exceptions noted (or not noted) on it at pickup and delivery are usually what a damage claim turns on.",
            "guide": ("/guides/freight-back-office.html", "Freight back office guide"),
            "see": ["pod", "broker-carrier-shipper", "factoring"],
        },
        {
            "slug": "pod",
            "term": "Proof of delivery (POD)",
            "aka": ["POD"],
            "short": "Proof of delivery is the signed and dated confirmation, usually the delivered copy of the bill of lading, that establishes freight arrived at its destination and marks the point payment obligations and the carrier's liability window are triggered.",
            "body": [
                ("p", "A POD is functionally the delivery half of the BOL's life cycle: the same document, signed a second time, at the other end of the trip. It records who received the freight, when, in what condition, and with what exceptions if any. Its practical importance is that it is usually the trigger for two separate clocks: the carrier submits it to get paid, and it marks the point at which the carrier's responsibility for the freight's condition generally ends (subject to any concealed-damage provisions in the applicable liability terms)."),
                ("p", "In practice a POD can be a signed paper BOL handed back, a photo of the signed document, or an electronic signature captured through a driver app or telematics system, and increasingly it is timestamped and geotagged automatically rather than typed in after the fact. The move toward automatic capture exists for the same reason electronic detention logging does: a POD reconstructed from memory hours or days later is a weaker document than one captured at the moment, and disputes get resolved in favor of whichever party has the better timestamp."),
                ("p", "A missing or incomplete POD is one of the most common reasons an invoice sits unpaid. Customers and factoring companies alike commonly require it before releasing payment, which makes POD collection a back-office bottleneck rather than a formality, especially at brokerages moving high volume with drivers who are not incentivized to chase paperwork after the truck is already empty."),
            ],
            "example": "A load delivers on a Friday afternoon. The driver's signed POD does not reach the brokerage's inbox until the following Tuesday because it was sitting in a text message thread. The invoice cannot go out until the POD is attached, so a load that delivered on time still shows as an open, unbilled receivable for four extra days.",
            "misconception": "Treating the POD as an afterthought once the freight has physically arrived. It is the document that actually unlocks payment and closes the liability window, so a delivered load with no POD attached is, from a billing and legal standpoint, still an open question.",
            "guide": ("/guides/freight-back-office.html", "Freight back office guide"),
            "see": ["bol", "factoring", "detention"],
        },
        {
            "slug": "ltl",
            "term": "LTL (less-than-truckload)",
            "aka": ["Less-than-truckload"],
            "short": "LTL is a freight mode in which a shipment too small to fill a trailer is combined with other shippers' freight in the same trailer, with each shipper paying only for the space and weight their freight occupies.",
            "body": [
                ("p", "LTL exists because most shipments do not need an entire 53-foot trailer. A pallet or two moving from a small manufacturer to a distributor gets consolidated at a carrier's terminal with freight from other shippers headed in a similar direction, moved on a linehaul trailer, then broken down and redistributed at a destination terminal for final delivery. The shipper pays for a fraction of the trailer rather than the whole thing, which is cheaper per shipment but slower and involves more handling, since freight typically gets loaded and unloaded at multiple terminals along the way."),
                ("p", "Pricing works differently from truckload freight. Rather than a single rate per mile, LTL pricing is built from freight class (a classification based on density, stowability, handling, and liability, running from class 50 to class 500), weight breaks, and a base rate published in a carrier's tariff, then adjusted by negotiated discounts. Getting the freight class wrong on the BOL is a common, expensive mistake, because carriers reweigh and reclassify shipments and rebill the difference, sometimes well after the freight has already delivered."),
                ("p", "The extra handling is also where LTL freight is most exposed to damage, since a pallet gets touched by forklifts and dock workers multiple times rather than staying on one trailer from pickup to delivery. That is part of why LTL bills of lading and the exceptions noted on them carry particular weight in a claim; more handoffs means more opportunities for something to happen, and more ambiguity about which handoff it happened at."),
            ],
            "example": "A small business ships two pallets of packaged goods from Ohio to Texas. Rather than book a whole truck, it uses an LTL carrier, whose trailer also carries freight from four other shippers on the same route. The shipper pays for roughly the trailer space its two pallets occupy, not the whole truck.",
            "misconception": "Assuming LTL pricing works like truckload pricing, as a straightforward rate times distance. It is driven by freight class, weight breaks, and tariff structure, which is why the same two pallets can price very differently depending on how they are classified on the BOL.",
            "see": ["ftl", "bol", "accessorial"],
        },
        {
            "slug": "ftl",
            "term": "FTL (full truckload)",
            "aka": ["Full truckload", "Truckload", "TL"],
            "short": "FTL is a freight mode in which a single shipper's freight fills an entire trailer, moving directly from origin to destination without being combined with other shippers' freight or handled at intermediate terminals.",
            "body": [
                ("p", "In FTL, one shipper's freight occupies the whole trailer, whether or not it physically fills every inch of it, and the truck typically moves directly from pickup to delivery with no intermediate terminal handling. That directness is the main advantage over LTL: fewer touches means less damage risk and a faster, more predictable transit time, which is why freight that is time-sensitive, high-value, or fragile often moves FTL even when it would technically fit on an LTL trailer."),
                ("p", "Pricing is simpler in structure than LTL, usually built around an all-in rate for the lane, often expressed as a rate per mile, and negotiated per load or per lane rather than pulled from a published class-based tariff. That simplicity is also why FTL rates move quickly with market capacity and fuel costs; a lane can reprice significantly week to week based on truck availability in that region, in a way an LTL tariff generally does not."),
                ("p", "A shipper does not need to physically fill the trailer to book FTL. A shipper moving three pallets of extremely fragile or high-value goods might still book a full truck rather than risk LTL handling, paying for capacity it is not using in exchange for the directness and reduced handling. That tradeoff, capacity utilization against handling risk and speed, is the core decision between the two modes."),
            ],
            "example": "A manufacturer needs 26 pallets moved 800 miles on a tight delivery window. It books FTL: one truck, one pickup, one delivery, no intermediate terminals, at an all-in linehaul rate for that lane.",
            "misconception": "That FTL requires the trailer to be physically full. It means one shipper controls the entire trailer for that move, regardless of how much freight actually occupies it, which is why low-volume but high-value or fragile freight often still ships FTL.",
            "guide": ("/guides/freight-broker-margin.html", "Freight broker margin guide"),
            "see": ["ltl", "deadhead", "reefer"],
        },
        {
            "slug": "reefer",
            "term": "Reefer",
            "aka": ["Refrigerated trailer", "Temperature-controlled trailer"],
            "short": "A reefer is a refrigerated trailer with an onboard cooling unit that maintains a set temperature range for perishable or temperature-sensitive freight throughout transit.",
            "body": [
                ("p", "A reefer trailer carries its own diesel- or electric-powered refrigeration unit mounted at the nose of the trailer, capable of holding a specified temperature range for the duration of a trip regardless of outside conditions. It moves the same categories of freight a dry van would be unsuitable for: fresh and frozen food, pharmaceuticals, some chemicals, and anything else with a spoilage or stability window."),
                ("p", "Reefer freight carries operational costs and risks a dry van load does not. The refrigeration unit runs continuously, burning its own fuel supply separate from the tractor, which is a real accessorial cost when the trailer sits idle at a dock with the unit running to hold temperature; this is part of why reefer detention rates tend to run higher than dry van rates, the truck is not just idle, it is actively consuming fuel to protect the cargo. Reefer freight is also more exposed on the insurance side: a certificate of insurance that carries a reefer breakdown exclusion, common on some policies, can leave an entire load of frozen product uncovered if the unit fails mid-transit, which is exactly the kind of exclusion worth reading rather than assuming away."),
                ("p", "Temperature logging matters more on reefer freight than on almost any other cargo type, because a claim over spoiled product typically turns on whether the trailer actually held the required range for the whole trip, not just whether it was set correctly at pickup. Continuous temperature recorders, checked at delivery against the required range stated on the BOL, are the reefer equivalent of the timestamped in/out logs that make a detention claim survive."),
            ],
            "example": "A load of frozen seafood requires the trailer held at 0°F for the full 30-hour transit. The carrier's reefer unit maintains the range and the temperature recorder confirms it at delivery, closing out any question of spoilage before it can become a claim.",
            "misconception": "Treating reefer freight as dry van freight that happens to be cold. The continuously running unit, the separate fuel draw, the higher detention exposure, and the specific insurance exclusions that apply to reefer breakdown make it a materially different risk and cost profile.",
            "guide": ("/guides/detention-demurrage-accessorials.html", "Detention, demurrage &amp; accessorials guide"),
            "see": ["ftl", "detention", "accessorial"],
        },
        {
            "slug": "drayage",
            "term": "Drayage",
            "short": "Drayage is the short-distance trucking movement of a container between a port, rail ramp, or intermodal terminal and a nearby warehouse, distribution center, or another mode of transport.",
            "body": [
                ("p", "Drayage covers the first or last leg of an intermodal shipment's journey, the piece that connects a ship or a train to the road network. A container arriving by vessel at a port needs to get to a warehouse or a rail ramp; a container arriving by rail at an intermodal terminal needs to get to its final destination or to a port for export. Both of those short hauls, often under 50 miles though sometimes considerably farther, are drayage."),
                ("p", "Drayage pricing and operations are distinct from standard truckload freight because the container itself, not just the trailer or chassis it rides on, is a tracked, billable object with its own set of clocks. The trucking company doing the drayage move is typically working against terminal appointment systems, chassis availability (the container needs a chassis to be road-legal, and chassis shortages are a chronic bottleneck at busy ports), and the demurrage and per diem clocks running on the container independent of anything the drayage carrier controls."),
                ("p", "A drayage move that seems simple on paper, one container, one short haul, can be delayed for reasons entirely outside the trucker's control: no chassis available, a missed terminal appointment window, or a customs hold on the container. Those delays are exactly what generate the detention and demurrage charges covered elsewhere in this glossary, which is why drayage is where those two terms show up constantly in practice."),
            ],
            "example": "A container of imported electronics arrives at a West Coast port. A drayage carrier picks it up from the terminal and hauls it 18 miles to a distribution center for unloading, then returns the empty container to a container yard.",
            "misconception": "Assuming drayage is interchangeable with any short-haul trucking. It specifically refers to the intermodal connector move, container in or out of a port, rail ramp, or terminal, and it inherits the container-specific clocks (demurrage, per diem) and appointment-system constraints that ordinary short-haul trucking does not have.",
            "see": ["deadhead", "demurrage", "detention"],
        },
        {
            "slug": "deadhead",
            "term": "Deadhead",
            "aka": ["Empty mile", "Non-revenue mile"],
            "short": "Deadhead is the distance a truck travels empty, without a paying load, most commonly between where it dropped off one shipment and where it picks up the next.",
            "body": [
                ("p", "Every mile a truck drives costs roughly the same in fuel, wear, and driver time whether or not there is freight on it. Deadhead miles are the ones with no freight, which means no revenue is generated to offset that cost. A carrier delivering in one city and picking up the next load in another city 120 miles away is deadheading those 120 miles, and that distance is a real cost that has to be recovered somewhere in the rates the carrier charges on the loads it does haul."),
                ("p", "Deadhead is central to how carriers and brokers think about lane profitability, because a lane's real cost is not just the loaded miles quoted on a rate confirmation, it is the loaded miles plus whatever deadhead the carrier expects to drive to reposition afterward. A lane that pays well on paper but reliably strands trucks in a location with no return freight is a lane carriers price up or avoid, and a broker who ignores that dynamic will find capacity gets harder to source on that lane over time regardless of the rate offered."),
                ("p", "Carriers manage deadhead by favoring round-trip or triangle routes where a return load is likely, and by building an implicit deadhead cost into their rate expectations on one-way lanes. This is also why load boards and broker relationships that reliably provide return freight in both directions get preferential treatment from carriers: consistently low deadhead is worth more to a carrier's bottom line than a marginally higher rate on any single load."),
            ],
            "example": "A carrier delivers a load in Phoenix with no return freight booked. It drives 90 empty miles to Tucson to pick up its next load. Those 90 miles are deadhead: fuel and driver hours spent with no freight generating revenue, a cost the carrier has to recover through the rates on the loads it does book.",
            "misconception": "Thinking of deadhead as a minor rounding error in a lane's economics. On lanes with structurally poor return freight, deadhead miles can approach or exceed the loaded miles, which is often the real reason a lane's rate is high, not the loaded distance itself.",
            "guide": ("/guides/freight-broker-margin.html", "Freight broker margin guide"),
            "see": ["ftl", "broker-carrier-shipper"],
        },
        {
            "slug": "detention",
            "term": "Detention",
            "short": "Detention is the charge billed for holding a truck, driver, or in intermodal a container outside the terminal, beyond the agreed free time at a facility, distinguishing it from demurrage, which applies to cargo held inside a terminal or port.",
            "body": [
                ("p", "Detention is a charge tied to the equipment and the driver being held past the time both parties agreed was reasonable for loading or unloading. In over-the-road trucking, that means the truck and driver sitting at a shipper's or receiver's dock beyond the free time stated on the rate confirmation, commonly framed as a couple of hours free before an hourly rate kicks in, though the actual number is whatever that specific rate confirmation says, not a fixed industry standard. In intermodal and drayage, the same word describes a related but distinct clock: a container held outside the port or rail terminal, at a yard or a consignee's dock, beyond its free days, which is often called per diem."),
                ("p", "The single most common mix-up in this whole vocabulary is detention versus demurrage, and the distinction is about location, not about the freight or equipment itself. <strong>Detention is charged for holding the truck, driver, or a container that is outside the terminal. Demurrage is charged for cargo or a container sitting inside a terminal, port, or rail ramp.</strong> A container can generate both charges on the same trip: demurrage while it waits inside the port past its free days, then detention (per diem) once it is pulled out and sits at the consignee's dock past a separate free-time window. Two different clocks, two different invoices, frequently confused because it is physically the same box."),
                ("p", "A detention charge is only as strong as its documentation. What a broker owes a carrier is whatever the signed rate confirmation states for free time and hourly rate; what a broker can bill a customer is whatever that customer's contract allows, and the two numbers are frequently not the same, with the gap coming directly out of margin. Getting paid on either side generally requires independent, contemporaneous evidence of arrival and departure times (an ELD or geofence event, a signed in/out time on the BOL, a timestamped check call), plus notice given before or as free time expires rather than after the fact, since most contracts require the notification while the delay is still fixable."),
            ],
            "example": "A dry van arrives at a receiver at 9:00am. The rate confirmation states two hours free, then $60 an hour. The truck is not released until 1:00pm. Four hours over free time at $60 is $240 owed to the carrier, recoverable from the customer only if the contract allows it and the arrival and departure times were documented and reported before the two-hour window closed.",
            "misconception": "Using detention and demurrage interchangeably, or applying detention to cargo sitting inside a port terminal. Detention is about the truck, driver, or an out-of-terminal container; demurrage is about cargo or a container inside a terminal or port. Billing one when the contract specifies the other is a common way a legitimate charge gets rejected.",
            "guide": ("/guides/detention-demurrage-accessorials.html", "Detention, demurrage &amp; accessorials guide"),
            "see": ["demurrage", "accessorial", "drayage"],
        },
        {
            "slug": "demurrage",
            "term": "Demurrage",
            "short": "Demurrage is the charge billed for cargo or a container sitting inside a terminal, port, or rail ramp beyond free time, distinguishing it from detention, which applies to a truck, driver, or container held outside the terminal.",
            "body": [
                ("p", "Demurrage originated in ocean shipping as a charge for a vessel held at berth beyond its allotted time, and the term now most commonly applies to containerized cargo sitting inside a marine terminal, port facility, or rail ramp past the free days allowed for pickup. The terminal has finite space, and every container that stays past its free time is occupying a slot the terminal needs for the next vessel or train's cargo, which is the actual economic reason the charge exists and escalates."),
                ("p", "The location test is what separates demurrage from detention, and it is worth restating because it is the single most-confused pair of terms in freight: <strong>demurrage applies while the container is inside the terminal; once it is pulled out, any further delay in returning it (say, sitting at the consignee's dock, or in a trucker's yard) shifts to detention, also called per diem.</strong> The same physical container can rack up demurrage first and detention second on the same import move, on two separate invoices from two separate parties, which is exactly the setup that produces billing disputes when someone assumes only one clock was running."),
                ("p", "Demurrage rates typically escalate in tiers rather than charging a flat daily rate: the first few days past free time cost noticeably less per day than day ten or day fifteen, which is a deliberate structure meant to pressure faster pickup rather than let a shipper treat the terminal as free storage. In the US, recent Federal Maritime Commission rulemaking has also constrained who a demurrage invoice can legally be billed to and what it must contain, along with the windows for issuing and disputing it; the specifics of that rule are the kind of detail worth checking against the current FMC text rather than assuming, since agencies revise rules and this is an area that has moved."),
            ],
            "example": "An imported container is discharged at a port with five free days before demurrage begins. Customs clearance takes eight days. Three days of demurrage accrue while the container sits inside the terminal; once it is finally pulled and trucked to the importer's warehouse, a separate detention (per diem) clock starts if it is not returned to the terminal within its own free-day window.",
            "misconception": "Using demurrage to describe a truck sitting at a shipper's dock, or assuming it is just another word for detention. Demurrage is specifically about cargo or a container held inside a terminal, port, or rail ramp; a truck held at a dock outside the terminal is detention, not demurrage, even though the underlying complaint (something is stuck too long) feels the same.",
            "guide": ("/guides/detention-demurrage-accessorials.html", "Detention, demurrage &amp; accessorials guide"),
            "see": ["detention", "drayage", "accessorial"],
        },
        {
            "slug": "accessorial",
            "term": "Accessorial",
            "aka": ["Accessorial charge"],
            "short": "An accessorial is any freight charge that is not the base linehaul rate, covering the roughly thirty additional billable events, such as detention, lumper fees, liftgate service, and residential delivery, that can occur around a shipment.",
            "body": [
                ("p", "Accessorial is the umbrella term for everything a carrier or terminal can legitimately charge for beyond simply moving freight from point A to point B at the quoted rate. The category is large: time-based charges like detention and layover, labor charges like lumper fees and driver assist, equipment charges like liftgate service and tarping, access charges like residential or limited-access delivery, routing changes like stop-offs and reconsignment, and cancellation charges like a truck ordered but not used. Most brokerages bill only four or five of these regularly and lose money on the rest simply because nobody recognized the event as billable when it happened."),
                ("p", "The pattern worth internalizing is that almost every accessorial is <em>an event that happened to the driver</em> at a specific place and time, not a line item that appears automatically. If the only record of a trip is a rate confirmation and a proof of delivery, the accessorial event is invisible by the time an invoice gets assembled unless something captured it in the moment: a lumper receipt photographed at the dock, a check call logged when a facility held the truck, a note that the delivery required a liftgate. That capture problem, not the existence of the charges, is the reason accessorials are described as a silent margin leak."),
                ("p", "Accessorial terms are set by the rate confirmation on the carrier side and by the customer contract or tariff on the customer side, and those two documents rarely specify identical terms unless someone has deliberately negotiated them to match. The gap between what a broker owes a carrier for an accessorial and what it can recover from the customer for the same event comes directly out of margin, which is why matching free time, rates, caps, and notice requirements across both sides of a relationship is one of the highest-leverage habits in freight brokerage."),
            ],
            "example": "A load requires a liftgate at delivery because the receiver has no dock, and the driver waits 45 minutes past free time while the receiver locates a forklift operator. Both the liftgate fee and the detention are accessorials; if neither is captured on a document at the time it happened, neither makes it onto the invoice, and the load's margin absorbs both costs silently.",
            "misconception": "Treating accessorials as rare exceptions rather than routine, recurring parts of freight movement. On a meaningful share of loads, something accessorial happens; the failure mode is not that these charges are unusual, it is that most of them are never captured well enough to bill.",
            "guide": ("/guides/detention-demurrage-accessorials.html", "Detention, demurrage &amp; accessorials guide"),
            "see": ["detention", "demurrage", "bol"],
        },
        {
            "slug": "factoring",
            "term": "Factoring",
            "aka": ["Invoice factoring", "Freight factoring"],
            "short": "Factoring is selling an unpaid freight invoice to a third-party factoring company at a discount in exchange for immediate cash, rather than waiting the typical 30 to 45 days a broker or shipper takes to pay.",
            "body": [
                ("p", "Carriers, especially small ones, often cannot afford to wait 30 to 45 days for a broker or shipper to pay an invoice while still covering fuel, payroll, and truck payments in the meantime. Factoring solves that cash-flow gap: the factoring company buys the invoice at a discount, typically a few percent depending on the factor, the customer's creditworthiness, and the payment terms, and pays the carrier most of the invoice value within a day or two. The factor then collects the full amount from the broker or shipper when it is actually due, and its profit is the spread between the discounted price and the full invoice amount."),
                ("p", "Factoring comes in two structures that carry very different risk. <strong>Recourse factoring</strong> is cheaper because the factor can charge the invoice back to the carrier if the broker or shipper never pays; the carrier still bears the credit risk. <strong>Non-recourse factoring</strong> costs more because the factor absorbs the loss if the debtor does not pay, though non-recourse contracts commonly carve out exceptions, such as disputes over the freight itself, so \"non-recourse\" is a term worth reading the actual contract on rather than trusting at face value."),
                ("p", "The operational trap that catches brokers and shippers, not carriers, is the <strong>notice of assignment (NOA)</strong>. Once a carrier factors an invoice, the factor sends an NOA instructing the debtor to pay the factor directly rather than the carrier, and that instruction is legally binding once received and valid. If a broker pays the carrier directly after a valid NOA is on file, that payment generally does not discharge the debt, since the obligation was assigned to the factor; the broker can end up owing the invoice amount a second time, this time to the factor. Tracking which carriers are currently factored, and to whom, is exactly the kind of structured, easy-to-neglect back-office task that produces expensive mistakes when it is handled from memory instead of a system."),
            ],
            "example": "A carrier hauls a load and factors the resulting invoice the same day, receiving 97% of its value immediately from the factoring company instead of waiting 40 days for the broker to pay. The factor sends the broker a notice of assignment. Two months later, a new dispatcher at the brokerage who never saw that notice pays the carrier directly by mistake; the brokerage may now owe the invoice amount again, this time to the factor, since the original obligation had already been legally assigned.",
            "misconception": "Assuming a factored invoice can be paid to whichever party asks first, or that \"non-recourse\" means the carrier bears zero risk under any circumstance. Once a valid notice of assignment is on file, payment has to go to the factor, and non-recourse contracts typically still leave the carrier exposed on invoices disputed for reasons unrelated to the debtor's ability to pay.",
            "guide": ("/guides/freight-back-office.html", "Freight back office guide"),
            "see": ["bol", "pod", "broker-carrier-shipper"],
        },
    ],
}
